unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ServicioAsignacionInventario.cls
@RestResource(urlMapping='/AsignacionInventario/*')
global class ServicioAsignacionInventario {
    
    @testVisible
    private Static Boolean throwEx = false;
    
    @HttpPost
    global static void createRecord() {
        RestRequest pedido = RestContext.request;
        RestResponse respuesta = RestContext.response;
        try {                     
            RequestBody requestBody = (RequestBody)JSON.deserialize(pedido.requestBody.toString(), RequestBody.class);
            RespuestaTraxion respuestaTraxion = new RespuestaTraxion();
            respuestaTraxion.completedSuccessfully = true;
            respuestaTraxion.response = new ResponseData();
            respuestaTraxion.response.message = 'successful';
            respuestaTraxion.response.data = new DataInfo();
          
            String orderNumber = requestBody.order_number;
            List<SkuInfo> skus = requestBody.skus; 

            Order__c order = [SELECT Id, Name, Estatus__c, Order_Number__c, (SELECT Id, name, Product__r.Product_Code_ID__c FROM Order_Line_Items__r) FROM Order__c WHERE Order_Number__c =: orderNumber LIMIT 1];
            
            order.Estatus__c = 'Preparando Envío';


            List<Order_Line_Item__c> orderLineItems = order.Order_Line_Items__r;
            
            Map<String, Order_Line_Item__c> productCodeToOrderLineItemMap = new Map<String, Order_Line_Item__c>();

            for(Order_Line_Item__c oli : orderLineItems) {
                productCodeToOrderLineItemMap.put(oli.Product__r.Product_Code_ID__c, oli);
            }
        
            List<Order_Line_Item__c> skuListToUpdate = new List<Order_Line_Item__c>();
            
            
            for(SkuInfo sku : skus){
                if (productCodeToOrderLineItemMap.containsKey(sku.sku)) {
                    Order_Line_Item__c skuLineRecord = productCodeToOrderLineItemMap.get(sku.sku);
                    skuLineRecord.Cantidad_de_Piezas__c = sku.quantity;
                    skuLineRecord.Estatus__c = 'Preparando Envío';
                    skuListToUpdate.add(skuLineRecord);
                }
            }

            update skuListToUpdate;

            update order;

            System.debug(skuListToUpdate);
          
            String responseBody = JSON.serialize(respuestaTraxion);
            
            respuesta.responseBody = Blob.valueOf(responseBody);
            respuesta.statusCode = 200;
            
            if(Test.isRunningTest() && throwEx){
                throw new CustomException('Error during testing.');
            }
            
        } catch (Exception ex) {
            respuesta.responseBody = Blob.valueOf('Error: ' + ex.getMessage());
            respuesta.statusCode = 500;
        }
    }
    
    global class RespuestaTraxion {
        public Boolean completedSuccessfully;
        public ResponseData response;
    }
    
    global class ResponseData {
        public String message;
        public DataInfo data;
    }
    
    global class DataInfo {
    }
    
    global class RequestBody {
        public String order_number;
        public List<SkuInfo> skus;
    }
    
    global class SkuInfo {
        public String sku;
        public Integer quantity;
    }
    
    public class CustomException extends Exception {}

}