unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>La funcion de este field es poder mostrar la clave al usuario.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/DPNLIConsumidoUpdateBatch.cls
global class DPNLIConsumidoUpdateBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start( Database.BatchableContext BC ) {
        String query = 'SELECT Id, Activo__c FROM DPN_Line_Item__c';
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<DPN_Line_Item__c> scope){
         for (DPN_Line_Item__c dpnli : scope)
         {
             dpnli.Activo__c = true;   
         }
         update scope;
    }   
    
    global void finish( Database.BatchableContext BC ) {
        
    }
 
}