unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Consumido__c.field-meta.xml
<CustomField>
    <fullName>Consumido__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/BatchDPNLineItemProcessor.cls
global class BatchDPNLineItemProcessor implements Database.Batchable<sObject> {
   global Database.QueryLocator start(Database.BatchableContext bc) {
      return Database.getQueryLocator('SELECT Id, Name, Consumido__c FROM DPN_Line_Item__c');
   }

   global void execute(Database.BatchableContext bc, List<DPN_Line_Item__c> scope) {
      // process each batch of records
      for (DPN_Line_Item__c dpnLineItem : scope) {
          if(dpnLineItem.Consumido__c == 16){
              dpnLineItem.Consumido__c = 0;
          }
         
      }
      update scope;
   }

   global void finish(Database.BatchableContext bc) {
      System.debug('Batch Job Completed Successfully.');
   }
}