unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OrderTriggerHandler.cls
public class OrderTriggerHandler {
    public static void orderBeforeUpdateHandler(List<Order__c> newOrderList, Map<Id, Order__c> oldOrderMap){
    	OrderFields.updateSeguimiento(newOrderList, oldOrderMap);
    }

    public static void orderAfterUpdateHandler(List<Order__c> newOrderList, Map<Id, Order__c> oldOrderMap){
    	OrderFields.updateDates(newOrderList, oldOrderMap);
    }

    public static void orderAfterUpdateDeliveryHandler(List<Order__c> newOrderList, Map<Id, Order__c> oldOrderMap) {
        Set<String> orderIdSet = new Set<String>(); 
        for(Order__c ord : newOrderList){
            if(ord.Estatus__c == 'Preparando Envío' && 
               (oldOrderMap.get(ord.Id).Estatus__c == 'Verificando Disponibilidad' || oldOrderMap.get(ord.Id).Estatus__c == 'Preparando Envío')){
                orderIdSet.add(ord.Id);
            } 
        } 
        List<String> orderIdList = new List<String>(orderIdSet);
        if(!orderIdList.isEmpty()){
            OrderFields.confirmOrder(orderIdList);
        } 
    }
}