unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ImageId__c.field-meta.xml
<CustomField>
    <fullName>ImageId__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ImageId</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/ImageUploadController.cls
public class ImageUploadController {

    @AuraEnabled
    public static String saveImage(String fileName, String base64Data, String parentId, Boolean isCheckin) {
        try {
            // Extract only base64 part of the string by removing data type prefix (if exists)
            String base64Prefix = 'base64,';
            Integer indexOfBase64Start = base64Data.indexOf(base64Prefix);

            if (indexOfBase64Start != -1) {
                base64Data = base64Data.substring(indexOfBase64Start + base64Prefix.length());
            }

            Blob imageBlob = EncodingUtil.base64Decode(base64Data);

            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = ' Evidencia ' + fileName;
            contentVersion.PathOnClient = fileName;
            contentVersion.VersionData = imageBlob;

            insert contentVersion;

            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.ContentDocumentId = 
                [SELECT Id, ContentDocumentId 
                 FROM ContentVersion 
                 WHERE Id = :contentVersion.Id WITH SECURITY_ENFORCED].ContentDocumentId;

            contentDocumentLink.LinkedEntityId = parentId;
            contentDocumentLink.ShareType = 'V'; // V – Viewer permission. C – Collaborator permission. I – Inferred permission.

            insert contentDocumentLink;

            List<Order__c> OrderImg = [
                SELECT id, ImageId__c, Estatus__c
                FROM Order__c
                WHERE Id = :parentId
            ];
            List<Order__c> orderUpdate = new List<Order__c>();

            if (OrderImg.size() > 0) {
                for (Order__c orden : OrderImg) {
                    orden.ImageId__c = true;
                    orderUpdate.add(orden);

                    if (isCheckin == true) {
                        orden.Estatus__c = 'Llegada de Transporte';
                    }
                }
                update orderUpdate;
            }

            return contentVersion.Id;
        } catch (Exception e) {
            System.debug('Exception occurred: ' + e.getMessage());
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }
}