unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <label>Tipo UMU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CMCT</fullName>
            </value>
            <value>
                <fullName>CMF</fullName>
            </value>
            <value>
                <fullName>CMFE</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>UE</fullName>
            </value>
            <value>
                <fullName>UMF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Aprobado_Por__c.field-meta.xml
<CustomField>
    <fullName>Aprobado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprobado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes (Aprobado Por)</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Autorizado_Por__c.field-meta.xml
<CustomField>
    <fullName>Autorizado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autorizado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes (Autorizado Por?)</relationshipLabel>
    <relationshipName>Ordenes1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Revision_Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Revision_Delegacion__c</fullName>
    <label>Fecha Revision Delegacion</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Revision_SICORA__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Revision_SICORA__c</fullName>
    <label>Fecha Revision SICORA</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ID_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Pedido__c</fullName>
    <label>ID de Pedido</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Aprobada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Aprobada__c</fullName>
    <label>Cantidad Aprobada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Autorizada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Autorizada__c</fullName>
    <label>Cantidad Autorizada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus_Aprobaci_n__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Aprobaci_n__c</fullName>
    <defaultValue>&#39;Pendiente&#39;</defaultValue>
    <label>Estatus Aprobación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Modificado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus_Autorizaci_n__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Autorizaci_n__c</fullName>
    <label>Estatus Autorización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
            <value>
                <fullName>Modificado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Motivo_No_Aprobaci_n__c.field-meta.xml
<CustomField>
    <fullName>Motivo_No_Aprobaci_n__c</fullName>
    <label>Motivo No Aprobación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Motivo_No_Autorizaci_n__c.field-meta.xml
<CustomField>
    <fullName>Motivo_No_Autorizaci_n__c</fullName>
    <label>Motivo No Autorización</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Aprobado_Por__c.field-meta.xml
<CustomField>
    <fullName>Aprobado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprobado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Aprobado Por)</relationshipLabel>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Autorizado_Por__c.field-meta.xml
<CustomField>
    <fullName>Autorizado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autorizado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Autorizado Por)</relationshipLabel>
    <relationshipName>Pedidos2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Creado_Por__c.field-meta.xml
<CustomField>
    <fullName>Creado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Fecha_Revision_Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Revision_Delegacion__c</fullName>
    <label>Fecha Revisión Delegación</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Fecha_Revision_SICORA__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Revision_SICORA__c</fullName>
    <label>Fecha Revisión SICORA</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/PreAutorizacionClass.cls
public without sharing class PreAutorizacionClass {

    private String pedidoId {get;set;}
    public Pedido__c pedido {get;set;}
    private List<Id> listaProductos {get;set;}
    public Order__c orden {get;set;}
    public Account umu {get;set;}
    public Contact contact {get;set;}
    public List<Product2> productos {get;set;}
    public String idSubalmacen{get;set;}
    public String aprobadoPor { get; set; }
    public String fechaRevisionDelegacion { get; set; }
    public String autorizadoPor { get; set; }
    public String fechaAutorizacion { get; set; }
    public Decimal totalCantidadSolicitada { get; set; }
    public Decimal totalCantidadAprobada { get; set; }
    public Decimal totalCantidadAutorizada { get; set; }
    public Decimal totalPiezasSolicitadas { get; set; }
    public Decimal totalPiezasAprobadas { get; set; }
    public Decimal totalPiezasAutorizadas { get; set; }
    public List<Order_Line_Item__c> allOlisFromPedidosList {get;set;}

    public PreAutorizacionClass() {
        try{ 
            pedidoId = ApexPages.currentPage().getParameters().get('id'); 
        } catch(Exception e){
            System.debug(e.getMessage());
        }  
        
        try{
            pedido = [
                SELECT Id, ID_de_Pedido__c, Tipo_de_Pedido__c, CreatedDate, UMU__c, Creado_Por__c, Aprobado_Por__c, Aprobado_Por__r.Name, 
                    Autorizado_Por__c, Autorizado_Por__r.Name, Fecha_Revision_Delegacion__c, Fecha_Revision_SICORA__c
                FROM Pedido__c 
                WHERE Id =: pedidoId 
                LIMIT 1
            ];

            String basePedidoId = pedido.ID_de_Pedido__c.substring(0, 6);
            String likeValue = basePedidoId + '%';
            List<Pedido__c> pedidosList = [
                SELECT Id 
                FROM Pedido__c
                WHERE ID_de_Pedido__c LIKE: likeValue
            ]; 

            Set<Id> pedidosIdSet = new Set<Id>();
            for(Pedido__c pedido : pedidosList){
                pedidosIdSet.add(pedido.Id);
            }

            allOlisFromPedidosList = [
                SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_Autorizada__c,
                    Estatus_Aprobaci_n__c, Estatus_Autorizaci_n__c, Motivo_No_Aprobaci_n__c, Motivo_No_Autorizaci_n__c, 
                    Product__r.Product_Code_ID__c, Product__r.Name
                FROM Order_Line_Item__c
                WHERE Pedido__c IN: pedidosIdSet 
            ]; 


            totalCantidadSolicitada = 0;
            totalCantidadAprobada = 0;
            totalCantidadAutorizada = 0;

            totalPiezasSolicitadas = 0; 
            totalPiezasAprobadas = 0; 
            totalPiezasAutorizadas = 0; 

            for (Order_Line_Item__c oli : allOlisFromPedidosList) {
                if(oli.Cantidad_Solicitada__c != null) {
                    totalCantidadSolicitada += oli.Cantidad_Solicitada__c;
                    totalPiezasSolicitadas++;
                }
                if(oli.Cantidad_Aprobada__c != null){
                    totalCantidadAprobada += oli.Cantidad_Aprobada__c;
                    if(oli.Estatus_Aprobaci_n__c == 'Aprobado'  || oli.Estatus_Aprobaci_n__c == 'Modificado'){
                        totalPiezasAprobadas++;
                    } 
                }
                if(oli.Cantidad_Autorizada__c != null){
                    totalCantidadAutorizada += oli.Cantidad_Autorizada__c; 
                    if(oli.Estatus_Autorizaci_n__c == 'Autorizado'  || oli.Estatus_Autorizaci_n__c == 'Modificado'){
                        totalPiezasAutorizadas++;
                    }   
                }
            }  

        } catch(Exception e){
            System.debug(e.getMessage());
        }
        
        try{
            Id contactId = UserContactClass.getContactIdFromUser();
            List<Contact> contactList = [
                SELECT Name 
                FROM Contact 
                WHERE Id =: contactId
            ];
            if(!contactList.isEmpty()){
                aprobadoPor = contactList[0].Name;
                fechaRevisionDelegacion = String.valueOf(Datetime.now()); 
                autorizadoPor = contactList[0].Name;
                fechaAutorizacion = String.valueOf(Datetime.now());
            } 
        } catch(Exception e){
            System.debug(e.getMessage());
        } 

        try{
            umu = [
                SELECT Id, Name, Ciudad__c, Calle__c, Colonia__c, Delegacion__c, Estado__c, Tipo_UMU__c, Clave_Presupuestal__c, UMU__c 
                FROM Account 
                WHERE Id =: pedido.UMU__c 
                LIMIT 1
            ];
        } catch(Exception e){
            System.debug(e.getMessage());
        } 

        try{
            contact = [
                SELECT Id, Name 
                FROM Contact 
                WHERE Id =: pedido.Creado_Por__c
            ];
        } catch(Exception e){
            System.debug(e.getMessage());
        } 

        try{ 
            String urlProductos = (ApexPages.currentPage().getParameters().get('listaProductos')); 
            listaProductos = new List<String>(urlProductos.split(','));  
            productos = [
                SELECT Id, Product_Code_ID__c, Name, 
                    (SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_Autorizada__c,
                        Estatus_Aprobaci_n__c, Estatus_Autorizaci_n__c, Motivo_No_Aprobaci_n__c, Motivo_No_Autorizaci_n__c
                     FROM Order_Line_Items__r
                     WHERE Pedido__c =: pedidoId LIMIT 1) 
                FROM Product2 
                WHERE Id IN: listaProductos
            ]; 

            List<Order_Line_Item__c> oliList = [
                SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_Autorizada__c,
                    Estatus_Aprobaci_n__c, Estatus_Autorizaci_n__c, Motivo_No_Aprobaci_n__c, Motivo_No_Autorizaci_n__c
                FROM Order_Line_Item__c 
                WHERE Pedido__c =: pedidoId
            ]; 
        } catch(Exception e){
            System.debug(e.getMessage());
        } 
    }
}