unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Fecha_Planeada_de_Finalizacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Planeada_de_Finalizacion__c</fullName>
    <label>Fecha Planeada de Finalizacion</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario ANS al que se le transfirieron las ordenes de la entrega.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ImageId__c.field-meta.xml
<CustomField>
    <fullName>ImageId__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ImageId</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario al que el transportista le transfiere las ordenes de la entrega por UMU.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EntreAsignadaController.cls
public with sharing class EntreAsignadaController {
  @AuraEnabled(cacheable=true)
  public static List<Object> getEntregasAsignadas(String userId) {
    try {
      List<Order__c> entrega = [
        SELECT
          id,
          ImageId__c,
          Entrega__r.Name,
          Estatus__c,
          Entrega__r.Fecha_Planeada_de_Finalizacion__c,
          UMU__r.Name,
          Entrega__r.Estado__c,
          Entrega__r.OwnerId,
          Usuario_ANS__c,
          UMU__r.Ciudad__c,
          UMU__r.Calle__c,
          UMU__r.Colonia__c,
          UMU__r.Estado__c
        FROM order__c
        WHERE Entrega__r.OwnerId = :userId AND Entrega__r.Estado__c = 'Asignado'
        WITH SECURITY_ENFORCED
      ];

      // Map<String, List<Order__c>> orden = new Map<String, List<Order__c>>();
      // Map<String, List<String>> ids = new Map<String, List<String>>();

      // for (Order__c ord : entrega) {
      //   List<Order__c> newOrderList = new List<Order__c>();
      //   newOrderList.add(ord);
      //   orden.put(ord.UMU__r.Name, newOrderList);

      //   if (ids.containsKey(ord.UMU__r.Name)) {
      //     List<String> idList = ids.get(ord.UMU__r.Name);
      //     idList.add(ord.Id);
      //     ids.put(ord.UMU__r.Name, idList);
      //   } else {
      //     List<String> idList = new List<String>();
      //     idList.add(ord.Id);
      //     ids.put(ord.UMU__r.Name, idList);
      //   }
      // }

      // List<Object> entregaList = new List<Object>();
      // for (String key : orden.keySet()) {
      //   Map<String, Object> obj = new Map<String, Object>();
      //   obj.put('UMUName', key);
      //   obj.put('records', orden.get(key));
      //   obj.put('ids', ids.get(key));
      //   entregaList.add(obj);
      // }

      // return entregaList;
      Map<String, List<Order__c>> orden = new Map<String, List<Order__c>>();
      Map<String, String> ids = new Map<String, String>();

      for (Order__c ord : entrega) {
        List<Order__c> newOrderList = new List<Order__c>();
        newOrderList.add(ord);
        orden.put(ord.UMU__r.Name, newOrderList);

        if (ids.containsKey(ord.UMU__r.Name)) {
          String idString = ids.get(ord.UMU__r.Name);
          idString += ', ' + ord.Id;
          ids.put(ord.UMU__r.Name, idString);
        } else {
          ids.put(ord.UMU__r.Name, ord.Id);
        }
      }

      List<Object> entregaList = new List<Object>();
      for (String key : orden.keySet()) {
        Map<String, Object> obj = new Map<String, Object>();
        obj.put('UMUName', key);
        obj.put('records', orden.get(key));
        obj.put('ids', ids.get(key));
        entregaList.add(obj);
      }

      return entregaList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}