unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <label>Delegación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001-AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>002-BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>003-BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>004-CAMPECHE</fullName>
            </value>
            <value>
                <fullName>005-COAHUILA</fullName>
            </value>
            <value>
                <fullName>006-COLIMA</fullName>
            </value>
            <value>
                <fullName>007-CHIAPAS</fullName>
            </value>
            <value>
                <fullName>008-CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>009-DISTRITO FEDERAL</fullName>
            </value>
            <value>
                <fullName>010-DURANGO</fullName>
            </value>
            <value>
                <fullName>011-GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>012-GUERRERO</fullName>
            </value>
            <value>
                <fullName>013-HIDALGO</fullName>
            </value>
            <value>
                <fullName>014-JALISCO</fullName>
            </value>
            <value>
                <fullName>015-ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>016-MICHOACAN</fullName>
            </value>
            <value>
                <fullName>017-MORELOS</fullName>
            </value>
            <value>
                <fullName>018-NAYARIT</fullName>
            </value>
            <value>
                <fullName>019-NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>020-OAXACA</fullName>
            </value>
            <value>
                <fullName>021-PUEBLA</fullName>
            </value>
            <value>
                <fullName>022-QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>023-QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>024-SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>025-SINALOA</fullName>
            </value>
            <value>
                <fullName>026-SONORA</fullName>
            </value>
            <value>
                <fullName>027-TABASCO</fullName>
            </value>
            <value>
                <fullName>028-TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>029-TLAXCALA</fullName>
            </value>
            <value>
                <fullName>030-VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <label>Tipo UMU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CMCT</fullName>
            </value>
            <value>
                <fullName>CMF</fullName>
            </value>
            <value>
                <fullName>CMFE</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>UE</fullName>
            </value>
            <value>
                <fullName>UMF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Folio_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Folio_de_Entrega__c</fullName>
    <formula>Order_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Folio de Entrega</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Folio_de_Remision__c.field-meta.xml
<CustomField>
    <fullName>Folio_de_Remision__c</fullName>
    <formula>RIGHT(Folio_de_Entrega__c, 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Folio de Remisión</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Folio_del_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Folio_del_Pedido__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Folio del Pedido</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ID_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Pedido__c</fullName>
    <label>ID de Pedido</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <formula>LEFT(Order_Number__c, 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero de Subalmacen</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <formula>VALUE(Product__r.Subalmacen__r.Numero_de_Subalmacen__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero de Subalmacen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/controladorOrden.cls
public without sharing class controladorOrden {
    private String ordenId {get;set;}
    private List<Id> listaProductos {get;set;}
    public Order__c orden {get;set;}
    public Account umu {get;set;}
    public Contact contact {get;set;}
    public List<Product2> productos {get;set;}
    public String idSubalmacen{get;set;}
    public Decimal totalCantidadSolicitada { get; set; }
    public Decimal totalCantidadAprobada { get; set; }
    public Decimal totalPiezasAprobadas { get; set; }
    public Decimal totalPiezasSolicitadas { get; set; }
    public Decimal totalCantidadConfirmada { get; set; }
    public Decimal totalPiezasConfirmadas { get; set; }
    public String folioDeEntrega {get;set;}
    public String folioDeRemision {get;set;}
    List<String> ordenIdList = new List<string>();

    public controladorOrden() {
        ordenId = ApexPages.currentPage().getParameters().get('id');
        orden = new Order__c();
        orden = [
            SELECT Id, Pedido__c, Folio_de_Entrega__c, Folio_de_Remision__c, Pedido__r.ID_de_Pedido__c, 
                Contacto__r.FirstName, UMU__c, Folio_del_Pedido__c, Tipo_de_Pedido__c, Entrega__c, Entrega__r.Name, CreatedDate,
                (SELECT Id, Order__c, Product__c, Numero_de_Subalmacen__c, UMU__c 
                 FROM Order_Line_Items__r) 
            FROM Order__c 
            WHERE Id =: ordenId 
            LIMIT 1
        ];
        
        // Get ids parameters
        List<Id> productIds = new List<Id>();
        List<String> oliIdList = new List<String>();
        for(Order_Line_Item__c oli: orden.Order_Line_Items__r){
            productIds.add(oli.Product__c);
            oliIdList.add(oli.Id);
        }
        String idsParameters = String.join(productIds, ','); 
        listaProductos = new List<String>(idsParameters.split(','));

        umu = [SELECT Id, Name, Ciudad__c, Calle__c, Colonia__c, Delegaci_n__c, Estado__c, Tipo_UMU__c, Clave_Presupuestal__c, UMU__c FROM Account WHERE Id = :orden.UMU__c LIMIT 1];
        contact = [SELECT Id, Name FROM Contact WHERE Id =: orden.Contacto__c];
        
        idSubalmacen = (ApexPages.currentPage().getParameters().get('idsubalmacen'));

        //productos = [SELECT Id, Product_Code_ID__c, Name FROM Product2 WHERE Id IN :(listaProductos)];
        ordenIdList.add(ordenId); // Assuming ordenId is a single ID value
        productos = [SELECT Id, Name, Product_Code_ID__c, 
                     (SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_de_Piezas__c
                      FROM Order_Line_Items__r WHERE Order__c IN :ordenIdList LIMIT 1) 
					FROM Product2 
					WHERE Id IN :listaProductos];

        List<Order_Line_Item__c> oliList = [
            SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_de_Piezas__c
            FROM Order_Line_Item__c
            WHERE Order__c IN :ordenIdList
        ];

        totalCantidadSolicitada = 0; 
        totalCantidadConfirmada = 0;

        totalPiezasSolicitadas = 0;  
        totalPiezasConfirmadas = 0; 

        for(Order_Line_Item__c oli : oliList){
            if(oli.Cantidad_Solicitada__c != null && oli.Cantidad_Solicitada__c != 0) {
                totalCantidadSolicitada += oli.Cantidad_Solicitada__c;
                totalPiezasSolicitadas++;
            }
            if(oli.Cantidad_de_Piezas__c != null && oli.Cantidad_de_Piezas__c != 0){
                totalCantidadConfirmada += oli.Cantidad_de_Piezas__c; 
                totalPiezasConfirmadas++; 
            }
        } 
    }
}