unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <label>Ciudad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <externalId>true</externalId>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <label>Tipo UMU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CMCT</fullName>
            </value>
            <value>
                <fullName>CMF</fullName>
            </value>
            <value>
                <fullName>CMFE</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>UE</fullName>
            </value>
            <value>
                <fullName>UMF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/ID_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Viaje__c</fullName>
    <externalId>true</externalId>
    <label>ID de Viaje</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario ANS al que se le transfirieron las ordenes de la entrega.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Certificado_Por__c.field-meta.xml
<CustomField>
    <fullName>Certificado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certificado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes (Certificado Por)</relationshipLabel>
    <relationshipName>Ordenes3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <formula>UMU__r.Clave_Presupuestal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clave Presupuestal</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Delegacion__c.field-meta.xml
<CustomField>
    <fullName>Delegacion__c</fullName>
    <label>Delegacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_de_certificacion_de_la_remision__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_certificacion_de_la_remision__c</fullName>
    <label>Fecha de Certificación</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_De_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_De_Entrega__c</fullName>
    <label>Fecha De Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Firmado_Por__c.field-meta.xml
<CustomField>
    <fullName>Firmado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firmado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes (Firmado Por)</relationshipLabel>
    <relationshipName>Ordenes2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Folio_de_Remision__c.field-meta.xml
<CustomField>
    <fullName>Folio_de_Remision__c</fullName>
    <formula>RIGHT(Folio_de_Entrega__c, 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Folio de Remisión</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Folio_del_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Folio_del_Pedido__c</fullName>
    <displayFormat>{0000000000}</displayFormat>
    <label>Folio del Pedido</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ID_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Pedido__c</fullName>
    <label>ID de Pedido</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Id_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Viaje__c</fullName>
    <formula>Entrega__r.Name</formula>
    <label>Id de Viaje</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Seguimiento__c.field-meta.xml
<CustomField>
    <fullName>Seguimiento__c</fullName>
    <label>Seguimiento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario al que el transportista le transfiere las ordenes de la entrega por UMU.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Creado_Por__c.field-meta.xml
<CustomField>
    <fullName>Creado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CertificacionClass.cls
public without sharing class CertificacionClass {

    private String ordenId {get;set;}
    private String pedidoId {get;set;}
    public Pedido__c pedido {get;set;}
    public Contact ansUser {get;set;}
    private List<Id> listaProductos {get;set;}
    public Order__c orden {get;set;}
    public Account umu {get;set;}
    public Contact contact {get;set;}
    public List<Product2> productos {get;set;}
    public String idSubalmacen {get;set;} 
    public List<Order_Line_Item__c> olis {get;set;} 
    public String fecharecepcion {get;set;}
    public String fechallegadatransporte {get;set;}
    public String fechahorallegadatransporte {get;set;}
    public String fechaderemision {get;set;}
    public String fechacertificacion {get;set;}
    public String fechaconfirmacion {get;set;}
    public Integer totaldepiezas {get;set;}
    public Decimal subtotal {get;set;}
    public String subtotaltexto {get;set;}
    public String cadenadecontenido {get;set;} 
    public Integer totalclaves {get;set;}

    public List<CertificationWrapper> certificationDataList {get;set;}
    public class CertificationWrapper{
        public Integer cons {get;set;}
        public String clave {get;set;}
        public Decimal cantidadsurtida {get;set;}
        public String unidad {get;set;}
        public String clavepresupuestal {get;set;}
        public String descripcion {get;set;}
        public Set<String> loteList {get;set;}
        public Set<String> caducidadList {get;set;}
        public Decimal costopromedio {get;set;}
        public Decimal importe {get;set;}
    }

    public CertificacionClass() {

        try{ 
            ordenId = ApexPages.currentPage().getParameters().get('id'); 
        } catch(Exception e){
            System.debug(e.getMessage());
        } 
        
        try{
            orden = [
                SELECT Id, CreatedDate, UMU__c, Order_Number__c, Folio_de_Remision__c, Fecha_de_certificacion_de_la_remision__c, 
                    Folio_del_Pedido__c, Seguimiento__c, Firmado_Por__r.Name, Firmado_Por__r.Email, Certificado_Por__r.Name, Certificado_Por__r.Email,                    
                    Pedido__r.ID_de_Pedido__c, Pedido__r.Creado_Por__c, Pedido__r.Tipo_de_Pedido__c, Fecha_De_Entrega__c,Entrega__r.ID_de_Viaje__c,
                    Pedido__r.CreatedDate, Usuario_ANS__r.Name, Usuario_ANS__r.Email
                FROM Order__c 
                WHERE Id =: ordenId 
                LIMIT 1
            ];
            
            Id ansId = ApexPages.currentPage().getParameters().get('firmadoPor');
            ansUser = [SELECT Name, Email 
                       FROM Contact
                       WHERE Id = :ansId];

            System.debug(orden);
            System.debug(orden.Seguimiento__c);

            if(!String.isBlank(orden.Seguimiento__c)){
                Map<String, String> seguimientoMap = (Map<String, String>)JSON.deserialize(orden.Seguimiento__c, Map<String, String>.class);
                if(seguimientoMap.containsKey('Recibido')){
                    fecharecepcion = Datetime.valueOf(seguimientoMap.get('Recibido').substringAfter(':')).format('dd-MM-yyyy');
                } else if(seguimientoMap.containsKey('Recibido Parcial')){
                    fecharecepcion = Datetime.valueOf(seguimientoMap.get('Recibido Parcial').substringAfter(':')).format('dd-MM-yyyy');
                } else if(seguimientoMap.containsKey('En Firma')){
                    fecharecepcion = Datetime.valueOf(seguimientoMap.get('En Firma').substringAfter(':')).format('dd-MM-yyyy');
                }
                if(seguimientoMap.containsKey('Certificado')){
                    fechacertificacion = Datetime.valueOf(seguimientoMap.get('Certificado').substringAfter(':')).format('dd-MM-yyyy h:mm a');
                }

                if(seguimientoMap.containsKey('Llegada de Transporte')){
                    fechallegadatransporte = Datetime.valueOf(seguimientoMap.get('Llegada de Transporte').substringAfter(':')).format('dd-MM-yyyy');
                    fechahorallegadatransporte = Datetime.valueOf(seguimientoMap.get('Llegada de Transporte').substringAfter(':')).format('dd-MM-yyyy h:mm a');
                }else if(seguimientoMap.containsKey('Transferido')){
                    fechallegadatransporte = Datetime.valueOf(seguimientoMap.get('Transferido').substringAfter(':')).format('dd-MM-yyyy');
                    fechahorallegadatransporte = Datetime.valueOf(seguimientoMap.get('Transferido').substringAfter(':')).format('dd-MM-yyyy h:mm a');
                }

                if(seguimientoMap.containsKey('Preparando Envío')){
                    fechaconfirmacion = Datetime.valueOf(seguimientoMap.get('Preparando Envío').substringAfter(':')).format('dd-MM-yyyy h:mm a');
                }
            }

            fechaderemision = Datetime.now().format('dd-MM-yyyy');

        } catch(Exception e){
            System.debug(e.getMessage());
        }
        System.debug(orden);

        try{
            umu = [
                SELECT Id, Name, Ciudad__c, Calle__c, Colonia__c, Delegacion__c, Estado__c, Tipo_UMU__c, Clave_Presupuestal__c, UMU__c,
                    Razon_Social__c, Direccion_de_Licencia_Sanitaria__c
                FROM Account 
                WHERE Id =: orden.UMU__c 
                LIMIT 1
            ];
        } catch(Exception e){
            System.debug(e.getMessage());
        }
        System.debug(umu);

        try{
            contact = [
                SELECT Id, Name 
                FROM Contact 
                WHERE Id =: orden.Pedido__r.Creado_Por__c
            ];
        } catch(Exception e){
            System.debug(e.getMessage());
        }
        System.debug(contact);

        try{ 
            String urlProductos = (ApexPages.currentPage().getParameters().get('listaProductos')); 
            listaProductos = new List<String>(urlProductos.split(','));  
            olis = [
                SELECT Id, Name, Product__c, Order__c, Cantidad_Solicitada__c, Cantidad_Aprobada__c, Cantidad_Entregada__c, Cantidad_Autorizada__c, Importe__c,
                    Cantidad_Surtida__c, Estatus_Aprobaci_n__c, Estatus_Autorizaci_n__c, Motivo_No_Aprobaci_n__c, Motivo_No_Autorizaci_n__c, 
                    Product__r.Name, Product__r.Product_Code_ID__c, Product__r.Partida_Presupuestal__c, Product__r.Description__c, Costo_Promedio__c,
                    (SELECT Numero_de_Lote__c, Fecha_de_Expiracion__c FROM Informacion_De_Lotes__r) 
                FROM Order_Line_Item__c 
                WHERE Order__c =: ordenId
                    AND Product__c IN: listaProductos
            ]; 

            Integer localTotalDePiezas = 0;
            Decimal localCostoTotal = 0;
            Integer contador = 1;
            totalclaves = 0;

            certificationDataList = new List<CertificationWrapper>(); 
            for(Integer i = 0; i < olis.size(); i++){
                CertificationWrapper certData = new CertificationWrapper();
                
                certData.clave = olis[i].Product__r.Product_Code_ID__c;
                certData.cantidadsurtida = olis[i].Cantidad_Entregada__c;
                certData.unidad = 'UN';
                certData.clavepresupuestal = olis[i].Product__r.Partida_Presupuestal__c;
                certData.descripcion = olis[i].Product__r.Description__c; 

                Set<String> loteList = new Set<String>(); 
                Set<String> caducidadList = new Set<String>(); 
                if(!olis[i].Informacion_De_Lotes__r.isEmpty()){
                    for(Integer j = 0; j < olis[i].Informacion_De_Lotes__r.size(); j++){
                        String loteInfo = olis[i].Informacion_De_Lotes__r[j].Numero_de_Lote__c;
                        Date caducidadInfo = olis[i].Informacion_De_Lotes__r[j].Fecha_de_Expiracion__c;

                        if(!String.isBlank(loteInfo)){ 
                            loteList.add(loteInfo);
                        } else{
                            loteList.add('N/A');
                        }

                        if(caducidadInfo != null){
                            caducidadList.add(String.valueOf(caducidadInfo));
                        } else{
                            caducidadList.add('N/A');
                        } 
                    } 
                } else{
                    loteList.add('N/A');
                    caducidadList.add('N/A');
                }
                certData.loteList = loteList; 
                certData.caducidadList = caducidadList; 
                certData.costopromedio = olis[i].Costo_Promedio__c != null ? olis[i].Costo_Promedio__c.setscale(2) : 0;
                
                Decimal subimporte = olis[i].Costo_Promedio__c != null && olis[i].Cantidad_Entregada__c != null ? olis[i].Costo_Promedio__c * olis[i].Cantidad_Entregada__c : 0;
                certData.importe = subimporte.setscale(2);

                if(olis[i].Cantidad_Entregada__c == null || olis[i].Cantidad_Entregada__c == 0){
                    continue;
                }  
                certData.cons = contador++;
                totalclaves++;
                certificationDataList.add(certData);
                localTotalDePiezas += Integer.valueOf(olis[i].Cantidad_Entregada__c);
                localCostoTotal += subimporte.setscale(2); 
            }
            totaldepiezas = localTotalDePiezas;
            subtotal = localCostoTotal;
            subtotaltexto = ConversorNumeroTexto.convertToWord(Integer.valueOf(subtotal)).toUpperCase() + ' M.N';
        } catch(Exception e){
            System.debug(e.getMessage());
        } 
        System.debug(productos);

        String remision = orden.Folio_de_Remision__c != null ? String.valueOf(orden.Folio_de_Remision__c) + ', ' : ''; //FOLIO REMISION
        String idpedido = orden.Pedido__r.ID_de_Pedido__c != null ? String.valueOf(orden.Pedido__r.ID_de_Pedido__c) + ', ' : ''; //PEDIDO
        //String createdate = orden.Pedido__r.CreatedDate != null ? String.valueOf(orden.Pedido__r.CreatedDate) + ', ' : ''; //FECHA Y HORA DE SOLICITUD
        String createdate = orden.Pedido__r.CreatedDate != null ? String.valueOf(Datetime.valueOf(orden.Pedido__r.CreatedDate).format('dd-MM-yyyy')) + ', ' : '';
        String clavepresupuestal = umu.Clave_Presupuestal__c != null ? String.valueOf(umu.Clave_Presupuestal__c) + ', ' : '';//CLAVE PRESUPUESTAL DE LA UMU
        String umu =  umu.UMU__c != null ? String.valueOf(umu.UMU__c) + ', ' : ''; //NUMERO DE LA UMU
        String numeroentrega = orden.Entrega__r.ID_de_Viaje__c != null ? String.valueOf(orden.Entrega__r.ID_de_Viaje__c) + ', ' : ''; //NUMERO DE ENTREGA
        String fechaconfi = fechaconfirmacion != null ? String.valueOf(fechaconfirmacion) + ', ' : ''; //FECHA Y HORA DE CONFIRMACION DE PEDIDO
        String totalpiezas = totaldepiezas != null ? String.valueOf(totaldepiezas) + ', ' : '';//TOTAL DE PIEZAS
        String totalclaves = totalclaves != null ? String.valueOf(totalclaves) + ', ' : '';//TOTAL DE CLAVES
        String subtotalimporte = subtotal != null ? String.valueOf(subtotal) + ', ' : '';//SUBTOAL DEL IMPORTE
        
        String firmadoporname = ansUser.Name != null ? String.valueOf(ansUser.Name) + ', ' : ''; //NOMBRE COMPLETO DE JEFE DE FARMACIA / ALMACEN
        String firmadoporemail = ansUser.Email != null ? String.valueOf(ansUser.Email) + ', ' : ''; //CORREO ELECTRÓNICO DE JEFE DE FARMACIA / ALMACEN
        
        String nombreans = orden.Usuario_ANS__r.Name != null ? String.valueOf(orden.Usuario_ANS__r.Name) + ', ' : ''; //NOMBRE COMPLETO DEL ANS
        String correoans =  orden.Usuario_ANS__r.Email != null ? String.valueOf(orden.Usuario_ANS__r.Email) + ', ' : ''; //CORREO ELECTRÓNICO DEL ANS

        String dateCert = Datetime.valueOf(System.now()).format('dd-MM-yyyy h:mm a');
        String fechallegadacamion = fechahorallegadatransporte != null ? String.valueOf(fechahorallegadatransporte) + ', ' : ''; //FECHA Y HORA DE LLEGADA DEL CAMIÓN
        //String fecharem = fechacertificacion != null ? String.valueOf(fechacertificacion) + ', ' : ''; //FECHA Y HORA DE FIRMA DE LA REMISIÓN
        //String fechacerti = fechacertificacion != null ? String.valueOf(fechacertificacion) + '.' : '.'; //FECHA Y HORA DE CERTIFICACIÓN
        
       
        
        cadenadecontenido = remision + idpedido + createdate + clavepresupuestal + umu + numeroentrega + fechaconfi + totalpiezas + totalclaves 
            + subtotalimporte + firmadoporname + firmadoporemail + nombreans + correoans + fechallegadacamion + dateCert + ', ' + dateCert + '.';
        
        
        system.debug('Cadena test data');
        System.debug(firmadoporname + firmadoporemail + nombreans + correoans + fechallegadacamion + dateCert);
        system.debug('Cadena test data 2');
        System.debug(remision);
        System.debug(idpedido);
        System.debug(createdate);
        System.debug(clavepresupuestal);
        System.debug(umu);
        System.debug(numeroentrega);
        System.debug(fechaconfi);
        System.debug(totalpiezas);
        System.debug(totalclaves);
        System.debug(subtotalimporte);
        System.debug(firmadoporname);
        System.debug(firmadoporemail);
		System.debug(nombreans);
		System.debug(correoans);
		System.debug(fechallegadacamion);
        System.debug(ansUser);
		//System.debug(fecharem);
		//System.debug(fechacerti);
        
        
        system.debug('Certification data');
        system.debug(certificationDataList);
        system.debug(cadenadecontenido);

    }
}