unpackaged/main/default/objects/Account/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <externalId>true</externalId>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <label>Delegación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001-AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>002-BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>003-BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>004-CAMPECHE</fullName>
            </value>
            <value>
                <fullName>005-COAHUILA</fullName>
            </value>
            <value>
                <fullName>006-COLIMA</fullName>
            </value>
            <value>
                <fullName>007-CHIAPAS</fullName>
            </value>
            <value>
                <fullName>008-CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>009-DISTRITO FEDERAL</fullName>
            </value>
            <value>
                <fullName>010-DURANGO</fullName>
            </value>
            <value>
                <fullName>011-GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>012-GUERRERO</fullName>
            </value>
            <value>
                <fullName>013-HIDALGO</fullName>
            </value>
            <value>
                <fullName>014-JALISCO</fullName>
            </value>
            <value>
                <fullName>015-ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>016-MICHOACAN</fullName>
            </value>
            <value>
                <fullName>017-MORELOS</fullName>
            </value>
            <value>
                <fullName>018-NAYARIT</fullName>
            </value>
            <value>
                <fullName>019-NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>020-OAXACA</fullName>
            </value>
            <value>
                <fullName>021-PUEBLA</fullName>
            </value>
            <value>
                <fullName>022-QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>023-QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>024-SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>025-SINALOA</fullName>
            </value>
            <value>
                <fullName>026-SONORA</fullName>
            </value>
            <value>
                <fullName>027-TABASCO</fullName>
            </value>
            <value>
                <fullName>028-TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>029-TLAXCALA</fullName>
            </value>
            <value>
                <fullName>030-VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <label>Tipo UMU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CMCT</fullName>
            </value>
            <value>
                <fullName>CMF</fullName>
            </value>
            <value>
                <fullName>CMFE</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>UE</fullName>
            </value>
            <value>
                <fullName>UMF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU_Cerrada__c.field-meta.xml
<CustomField>
    <fullName>UMU_Cerrada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UMU Cerrada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <formula>UMU__r.Clave_Presupuestal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clave Presupuestal</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UmuController.cls
public with sharing class UmuController {
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmu(String userId){
        List<Account> userRelatedAccountList = new List<Account>();
        try {
            userRelatedAccountList = UserContactClass.getAccountListFromUser();
            return userRelatedAccountList;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            return userRelatedAccountList;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Order__c> getUmuOrders(String umuName) {
        try {
            List<Order__c> ordList = [
                SELECT
                Id,
                Fecha_Limite_de_Entrega__c,
                Tipo_de_Pedido__c,
                Total_de_Piezas__c,
                UMU__r.Name,
                Entrega__r.Estado__c
                FROM Order__c
                WHERE UMU__r.Name = :umuName 
                AND Entrega__r.Estado__c = 'Asignado'
                // WITH SECURITY_ENFORCED
            ];
            
            return ordList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getAllUmus(){
        List<Account> accountsList = new List<Account>();
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c
                    FROM ACCOUNT
                    WHERE UMU_Cerrada__c = false];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmuByType(List<String> umuTypes){
        List<Account> accountsList = new List<Account>();
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c
                    FROM ACCOUNT
                    WHERE Tipo_UMU__c IN :umuTypes
                    AND UMU_Cerrada__c = false];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmuByTypeAndDelegation(List<String> umuTypes, List<String> umuDelegations){
        List<Account> accountsList = new List<Account>();
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c
                    FROM ACCOUNT
                    WHERE Tipo_UMU__c IN :umuTypes
                    AND Delegaci_n__c IN :umuDelegations
                    AND UMU_Cerrada__c = false];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmuByDelegation(List<String> umuDelegations){
        List<Account> accountsList = new List<Account>();
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c
                    FROM ACCOUNT
                    WHERE Delegaci_n__c IN :umuDelegations
                    AND UMU_Cerrada__c = false];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmuDelegationByType(List<String> umuTypes){
        List<Account> accountsList = new List<Account>();
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c
                    FROM ACCOUNT
                    WHERE Tipo_UMU__c IN :umuTypes
                    AND UMU_Cerrada__c = false
                    ORDER BY Delegaci_n__c ASC];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Account> getUmusById(List<String> umuIds){
        try {
            return [SELECT Id, Name, Tipo_UMU__c, Delegaci_n__c, Clave_Presupuestal__c, UMU__c
                    FROM ACCOUNT
                    WHERE Id IN :umuIds
                    AND UMU_Cerrada__c = false
                    ORDER BY Delegaci_n__c ASC];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SelectOptionWrapper> getUmuMultiSelectOptions(String objectName, String fieldName) {
        List<SelectOptionWrapper> options = new List<SelectOptionWrapper>();
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe()
            .get(objectName).getDescribe().fields.getMap().get(fieldName).getDescribe();
        
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOptionWrapper(entry.getValue(), entry.getLabel()));
        }
        return options;
    }
    
    public class SelectOptionWrapper {
        @AuraEnabled
        public String value { get; set; }
        @AuraEnabled
        public String label { get; set; }
        
        public SelectOptionWrapper(String value, String label) {
            this.value = value;
            this.label = label;
        }
    }
    
    //   @AuraEnabled(cacheable=true)
    //   public static List<AccountContactRelation> getUmu(String userId) {
    //     try {
    //       List<Id> accId = new List<Id>();
    //       List<User> activeUser = [
    //         SELECT ContactId
    //         FROM User
    //         WHERE Id = :userId
    //         WITH SECURITY_ENFORCED
    //       ];
    
    //       Id contactId = activeUser[0].ContactId;
    //       List<Contact> conList = [
    //         SELECT AccountId
    //         FROM Contact
    //         WHERE id = :contactId
    //         WITH SECURITY_ENFORCED
    //       ];
    
    //       for (Contact con : conList) {
    //         accId.add(con.AccountId);
    //       }
    
    //       return [
    //         SELECT AccountId, Account.Name
    //         FROM AccountContactRelation
    //         WHERE ContactId = :contactId
    //         WITH SECURITY_ENFORCED
    //       ];
    //     } catch (Exception e) {
    //       throw new AuraHandledException(e.getMessage());
    //     }
    //   }
}