unpackaged/main/default/objects/Account/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <externalId>true</externalId>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <label>Delegación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001-AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>002-BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>003-BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>004-CAMPECHE</fullName>
            </value>
            <value>
                <fullName>005-COAHUILA</fullName>
            </value>
            <value>
                <fullName>006-COLIMA</fullName>
            </value>
            <value>
                <fullName>007-CHIAPAS</fullName>
            </value>
            <value>
                <fullName>008-CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>009-DISTRITO FEDERAL</fullName>
            </value>
            <value>
                <fullName>010-DURANGO</fullName>
            </value>
            <value>
                <fullName>011-GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>012-GUERRERO</fullName>
            </value>
            <value>
                <fullName>013-HIDALGO</fullName>
            </value>
            <value>
                <fullName>014-JALISCO</fullName>
            </value>
            <value>
                <fullName>015-ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>016-MICHOACAN</fullName>
            </value>
            <value>
                <fullName>017-MORELOS</fullName>
            </value>
            <value>
                <fullName>018-NAYARIT</fullName>
            </value>
            <value>
                <fullName>019-NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>020-OAXACA</fullName>
            </value>
            <value>
                <fullName>021-PUEBLA</fullName>
            </value>
            <value>
                <fullName>022-QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>023-QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>024-SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>025-SINALOA</fullName>
            </value>
            <value>
                <fullName>026-SONORA</fullName>
            </value>
            <value>
                <fullName>027-TABASCO</fullName>
            </value>
            <value>
                <fullName>028-TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>029-TLAXCALA</fullName>
            </value>
            <value>
                <fullName>030-VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs (UMU)</relationshipLabel>
    <relationshipName>DPNs1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Historico</fullName>
            </value>
            <value>
                <fullName>No Ordinario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>La funcion de este field es poder mostrar la clave al usuario.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Consumido__c.field-meta.xml
<CustomField>
    <fullName>Consumido__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/L_mite_Mensual__c.field-meta.xml
<CustomField>
    <fullName>L_mite_Mensual__c</fullName>
    <label>Lìmite Mensual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Fraction__c.field-meta.xml
<CustomField>
    <fullName>Fraction__c</fullName>
    <label>Fraction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Controlado 1</fullName>
            </value>
            <value>
                <fullName>Controlado 2</fullName>
            </value>
            <value>
                <fullName>Controlado 3</fullName>
            </value>
            <value>
                <fullName>No Controlado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/listaDeClavesControladorTest.cls
@isTest
public with sharing class listaDeClavesControladorTest {
    
    @TestSetup
    static void makeData(){

        // Crear Account 

        Account account = new Account(
            Name = 'AGUASCALIENTESTEST',
            Delegaci_n__c = '001-AGUASCALIENTES',
            Clave_Presupuestal__c = '00412452'
        );

        insert account;

        // Crear DPN
        
        DPN__c dpn = new DPN__c(
            Account__c = account.Id,
            Estatus__c = 'Activo'
        );

        insert dpn;

        // Crear productos
        List<Product2> productList = new List<Product2>();
        List<DPN_Line_Item__c> dpnLineItemList = new List<DPN_Line_Item__c>();

        for(Integer x = 1; x <= 3; x++){
            Product2 product = new Product2(
                Name = 'Omeprazol ' + x,
                Fraction__c = 'Controlado ' + x
            );

            productList.add(product);
        }

        insert productList;

        // Crear DPN line items
        for (Product2 product: productList){
            DPN_Line_Item__c dpnLineItem = new DPN_Line_Item__c(
                Consumido__c = 2,
                L_mite_Mensual__c = 100,
                Product__c = product.Id,
                Activo__c = true,
                DPN__c = dpn.Id
            );
            dpnLineItemList.add(dpnLineItem);
        }

        insert dpnLineItemList;
    }

    @isTest
    static void obtenerListaDeClavesControlado23Test(){

        Account account = [SELECT Id FROM Account WHERE Name = 'AGUASCALIENTESTEST' LIMIT 1];
        DPN__c dpn = [SELECT Id, Estatus__c, Account__c FROM DPN__c];
        List<Product2> productList = [SELECT Id, Fraction__c FROM Product2];
        List<DPN_Line_Item__c> dpnLineItem = [SELECT Id FROM DPN_Line_Item__c];

        Test.startTest();
            List<DPN_Line_Item__c> dpnLineItemTest = listaDeClavesControlador.obtenerListaDeClaves(account.Id, false, true, true);
        Test.stopTest();

        System.assertEquals(2, dpnLineItemTest.size(), 'El resultado debe de ser 2.');
    }

    @isTest
    static void obtenerListaDeClavesControlado1Test(){

        Account account = [SELECT Id FROM Account WHERE Name = 'AGUASCALIENTESTEST' LIMIT 1];
        DPN__c dpn = [SELECT Id, Estatus__c, Account__c FROM DPN__c];
        List<Product2> productList = [SELECT Id, Fraction__c FROM Product2];
        List<DPN_Line_Item__c> dpnLineItem = [SELECT Id FROM DPN_Line_Item__c];

        Test.startTest();
            List<DPN_Line_Item__c> dpnLineItemTest = listaDeClavesControlador.obtenerListaDeClaves(account.Id, true, false, false);
        Test.stopTest();

        System.assertEquals(1, dpnLineItemTest.size(), 'El resultado debe de ser 1.');
    }


    @isTest
    static void mostrarDpnLineItemTest(){
        
        List<DPN_Line_Item__c> dpnLineItem = [SELECT Id, Activo__c FROM DPN_Line_Item__c];
        List<DPN_Line_Item__c> dpnLineItemToUpdate = new List<DPN_Line_Item__c>();

        for(DPN_Line_Item__c dpnLine: dpnLineItem){
            dpnLine.Activo__c = false;
            dpnLineItemToUpdate.add(dpnLine);
        }
        
        Test.startTest();
         List<DPN_Line_Item__c> dpnLineItemUpdate = listaDeClavesControlador.mostrarDpnLineItem(dpnLineItemToUpdate);
        Test.stopTest();

        for(DPN_Line_Item__c dpnLineItemCheck: dpnLineItemUpdate){
            system.assert(dpnLineItemCheck.Activo__c == false);
        }
    }

    @isTest
    static void mostrarDpnLineItemTryCatchTest(){
        
        List<DPN_Line_Item__c> dpnLineItemToUpdate = new List<DPN_Line_Item__c>();
        
        try {
            Test.startTest();
                List<DPN_Line_Item__c> dpnLineItemUpdate = listaDeClavesControlador.mostrarDpnLineItem(dpnLineItemToUpdate);
            Test.stopTest();
        } catch (listaDeClavesControlador.MyCustomException e) {
            System.assertEquals('An error has ocurred.', e.getMessage());
        }

    }

}