unpackaged/main/default/objects/Account/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <externalId>true</externalId>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <label>Clave Presupuestal</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <formula>UMU__r.Clave_Presupuestal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clave Presupuestal</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ClassToDeleteTest.cls
@isTest
public class ClassToDeleteTest {
    @isTest
    public static void getFilteredOrdersTest() {
        User user = TestDataFactory.initCommunityLoginUser('testuser');

        Contact con = [
            SELECT Id, AccountId FROM Contact
            WHERE Id = :user.ContactId
        ];
        
        Entrega__c e = TestDataFactory.createSingleDelivery('Asignado');
        
        Product2 p1 = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        Product2 p2 = TestDataFactory.createSingleProduct2('JARABE PARA GRIPA');
        
        String jsonToSend = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            con.AccountId + '","TipoDePedido": "Soporte de Vida","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' +
            p2.Id + '","CantidadSolicitada": 5}]}]';
        
        System.runAs(user) {
            Test.startTest();
            List<Order__c> orders = controladorGeneracionPedidos.deserializeOrders(jsonToSend);
            
            orders[0].Entrega__c = e.Id;
            update orders[0];
            
            List<Order__c> orderList = [
                SELECT Id, UMU__c, Tipo_de_Pedido__c, UMU__r.Clave_Presupuestal__c, UMU__r.Estado__c, Entrega__c
                FROM Order__c 
                WHERE Id = :orders[0].Id
            ];
            
            List<String> codes = new List<String>{p1.Product_Code_ID__c, p2.Product_Code_ID__c};
                List<String> umus = new List<String>();
            List<String> states = new List<String>();
            List<String> orderTypes = new List<String>();
            List<String> deliveries = new List<String>();
            
            for(Order__c order : orderList) {
                umus.add(order.UMU__r.Clave_Presupuestal__c);
                states.add(order.UMU__r.Estado__c);
                orderTypes.add(order.Tipo_de_Pedido__c);
                deliveries.add(order.Entrega__c);
            }
            
            Date startDate = Date.today();
            Date endDate =  startDate.addDays(3);
            
            
            List<Order__c> result = ClassToDelete_RetrieveAccounts.getFilteredOrders(codes, umus, states, orderTypes, deliveries, startDate, endDate);
            System.assertEquals(1, result.size(), 'The order list size must be 1');
            Test.stopTest(); 
        }
    }
    
    @isTest
    public static void getOrderLineItemsTest() {
        User user = TestDataFactory.initCommunityLoginUser('testuser');

        Contact con = [
            SELECT Id, AccountId FROM Contact
            WHERE Id = :user.ContactId
        ];
        
        Entrega__c e = TestDataFactory.createSingleDelivery('Asignado');
        
        Product2 p1 = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        Product2 p2 = TestDataFactory.createSingleProduct2('JARABE PARA GRIPA');
        
        String jsonToSend = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            con.AccountId + '","TipoDePedido": "Soporte de Vida","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' +
            p2.Id + '","CantidadSolicitada": 5}]}]';
        
        System.runAs(user) {
            Test.startTest();
            List<Order__c> orders = controladorGeneracionPedidos.deserializeOrders(jsonToSend);
            List<Id> orderIds = new List<Id>{orders[0].Id};
            List<Order_Line_Item__c> result = ClassToDelete_RetrieveAccounts.getOrderLineItems(orderIds);
            System.assertEquals(2, result.size(), 'The oli list size must be 2');
            Test.stopTest();
        }
    }
}