unpackaged/main/default/objects/Account/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <label>Delegación</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001-AGUASCALIENTES</fullName>
            </value>
            <value>
                <fullName>002-BAJA CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>003-BAJA CALIFORNIA SUR</fullName>
            </value>
            <value>
                <fullName>004-CAMPECHE</fullName>
            </value>
            <value>
                <fullName>005-COAHUILA</fullName>
            </value>
            <value>
                <fullName>006-COLIMA</fullName>
            </value>
            <value>
                <fullName>007-CHIAPAS</fullName>
            </value>
            <value>
                <fullName>008-CHIHUAHUA</fullName>
            </value>
            <value>
                <fullName>009-DISTRITO FEDERAL</fullName>
            </value>
            <value>
                <fullName>010-DURANGO</fullName>
            </value>
            <value>
                <fullName>011-GUANAJUATO</fullName>
            </value>
            <value>
                <fullName>012-GUERRERO</fullName>
            </value>
            <value>
                <fullName>013-HIDALGO</fullName>
            </value>
            <value>
                <fullName>014-JALISCO</fullName>
            </value>
            <value>
                <fullName>015-ESTADO DE MÉXICO</fullName>
            </value>
            <value>
                <fullName>016-MICHOACAN</fullName>
            </value>
            <value>
                <fullName>017-MORELOS</fullName>
            </value>
            <value>
                <fullName>018-NAYARIT</fullName>
            </value>
            <value>
                <fullName>019-NUEVO LEÓN</fullName>
            </value>
            <value>
                <fullName>020-OAXACA</fullName>
            </value>
            <value>
                <fullName>021-PUEBLA</fullName>
            </value>
            <value>
                <fullName>022-QUERÉTARO</fullName>
            </value>
            <value>
                <fullName>023-QUINTANA ROO</fullName>
            </value>
            <value>
                <fullName>024-SAN LUIS POTOSÍ</fullName>
            </value>
            <value>
                <fullName>025-SINALOA</fullName>
            </value>
            <value>
                <fullName>026-SONORA</fullName>
            </value>
            <value>
                <fullName>027-TABASCO</fullName>
            </value>
            <value>
                <fullName>028-TAMAULIPAS</fullName>
            </value>
            <value>
                <fullName>029-TLAXCALA</fullName>
            </value>
            <value>
                <fullName>030-VERACRUZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Autorizado_Por__c.field-meta.xml
<CustomField>
    <fullName>Autorizado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autorizado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes (Autorizado Por?)</relationshipLabel>
    <relationshipName>Ordenes1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Es_Programa__c.field-meta.xml
<CustomField>
    <fullName>Es_Programa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifica si un pedido es generado a través de una guía.</description>
    <label>Es Programa?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Autorizado_Por__c.field-meta.xml
<CustomField>
    <fullName>Autorizado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autorizado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Autorizado Por)</relationshipLabel>
    <relationshipName>Pedidos2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Es_Programa__c.field-meta.xml
<CustomField>
    <fullName>Es_Programa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Programa?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MisPedidosClassTest.cls
@isTest
public class MisPedidosClassTest { 

    @TestSetup
	static void createTestData() {
        String uniqueUserName = String.ValueOf(System.Now()).replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);

        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];   

        Account acc = [SELECT Id, Delegaci_n__c FROM Account WHERE Id =: accountContactList[0].AccountId];
        System.debug(acc);

        Pedido__c pedido = new Pedido__c();
        pedido.UMU__c = acc.Id;  
        pedido.Es_Programa__c = false;
        pedido.Autorizado_Por__c = user.ContactId;
        insert pedido;

        Order__c order = new Order__c();
        order.Pedido__c = pedido.Id;
        order.UMU__c = acc.Id;
        order.Contacto__c = user.ContactId;
        order.Tipo_de_Pedido__c = 'Ordinario';
        order.Estatus__c = 'Verificando Disponibilidad';
        insert order;
    }

    @isTest
    static void testGetMisPedidos_Ordinario(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];
        
        System.runAs(testUser) {
            List<Pedido__c> pedidoList = MisPedidosClass.getMisPedidos(fechaInicio, fechaFin); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1');
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetMisPedidos_Programa(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];
        
        Order__c orden = [SELECT Id, Tipo_de_Pedido__c FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Programa';
        update orden;

        System.runAs(testUser) {
            List<Pedido__c> pedidoList = MisPedidosClass.getMisPedidos(fechaInicio, fechaFin); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1');
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetMisPedidos_Replaneacion(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];
        
        Order__c orden = [SELECT Id, Tipo_de_Pedido__c FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Replaneación';
        update orden;

        System.runAs(testUser) {
            List<Pedido__c> pedidoList = MisPedidosClass.getMisPedidos(fechaInicio, fechaFin); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1');
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetMisPedidos_EsProgramaExtraordinario_True(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];
        
        Order__c orden = [SELECT Id, Tipo_de_Pedido__c FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Extraordinario';
        update orden;

        Pedido__c pedido = [SELECT Id, Es_Programa__c FROM Pedido__c LIMIT 1];  
        pedido.Es_Programa__c = true;
        update pedido;

        System.runAs(testUser) {
            List<Pedido__c> pedidoList = MisPedidosClass.getMisPedidos(fechaInicio, fechaFin); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1');
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetMisPedidos_EsProgramaExtraordinario_False(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        Order__c orden = [SELECT Id, Tipo_de_Pedido__c FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Extraordinario';
        update orden;

        System.runAs(testUser) {
            List<Pedido__c> pedidoList = MisPedidosClass.getMisPedidos(fechaInicio, fechaFin); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1');
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetFilteredOrdersAndOlis_OLI_Aprobada(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        Pedido__c pedido = [SELECT Id, Estatus__c, Total_de_Claves__c, Total_de_Piezas__c FROM Pedido__c LIMIT 1];  
        pedido.Estatus__c = 'Ver Detalles';
        pedido.Total_de_Claves__c = 0;
        pedido.Total_de_Piezas__c = 0;
        update pedido;

        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];

        Product2 clave = TestDataFactory.createSingleProduct2('Medicina de Prueba'); 

        Order_Line_Item__c orderLineItem = new Order_Line_Item__c();
        orderLineItem.Pedido__c = pedido.Id;
        orderLineItem.Order__c = orden.Id;
        orderLineItem.Product__c = clave.Id;
        insert orderLineItem; 

        List<String> orderIdList = new List<String>{orden.Id}; 
        

        System.runAs(testUser) {
            List<Order__c> pedidoList = MisPedidosClass.getFilteredOrdersAndOlis(orderIdList); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1'); 
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetFilteredOrdersAndOlis_OLI_Rechazada(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        Pedido__c pedido = [SELECT Id, Estatus__c, Total_de_Claves__c, Total_de_Piezas__c FROM Pedido__c LIMIT 1];  
        pedido.Estatus__c = 'Ver Detalles';
        pedido.Total_de_Claves__c = 0;
        pedido.Total_de_Piezas__c = 0;
        update pedido;

        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Extraordinario';
        update orden;

        Product2 clave = TestDataFactory.createSingleProduct2('Medicina de Prueba'); 

        Order_Line_Item__c orderLineItem = new Order_Line_Item__c();
        orderLineItem.Pedido__c = pedido.Id;
        orderLineItem.Order__c = orden.Id;
        orderLineItem.Product__c = clave.Id;
        orderLineItem.Estatus_Autorizaci_n__c = 'Rechazado';
        insert orderLineItem; 

        List<String> orderIdList = new List<String>{orden.Id}; 
        

        System.runAs(testUser) {
            List<Order__c> pedidoList = MisPedidosClass.getFilteredOrdersAndOlis(orderIdList); 
            System.assertEquals(0, pedidoList.size(), 'Valor esperado 0'); 
        }
        Test.stopTest();
    } 

    @isTest
    static void testGetFilteredOrdersAndOlis_OLI_Autorizada(){
        Test.startTest();
        Date hoy = Date.today();
        Date fechaInicio = hoy.addDays(-5);
        Date fechaFin = hoy.addDays(5);

        User testUser = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        Pedido__c pedido = [SELECT Id, Estatus__c, Total_de_Claves__c, Total_de_Piezas__c FROM Pedido__c LIMIT 1];  
        pedido.Estatus__c = 'Ver Detalles';
        pedido.Total_de_Claves__c = 0;
        pedido.Total_de_Piezas__c = 0;
        update pedido;

        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];
        orden.Tipo_de_Pedido__c = 'Extraordinario';
        update orden;

        Product2 clave = TestDataFactory.createSingleProduct2('Medicina de Prueba'); 

        Order_Line_Item__c orderLineItem = new Order_Line_Item__c();
        orderLineItem.Pedido__c = pedido.Id;
        orderLineItem.Order__c = orden.Id;
        orderLineItem.Product__c = clave.Id;
        orderLineItem.Estatus_Autorizaci_n__c = 'Autorizado';
        insert orderLineItem; 

        List<String> orderIdList = new List<String>{orden.Id}; 
        

        System.runAs(testUser) {
            List<Order__c> pedidoList = MisPedidosClass.getFilteredOrdersAndOlis(orderIdList); 
            System.assertEquals(1, pedidoList.size(), 'Valor esperado 1'); 
        }
        Test.stopTest();
    } 

    @IsTest
    static void testGetOrderEvidence() {
        Test.startTest(); 
        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];

        ContentVersion cv = new ContentVersion(
            Title = 'Evidencia',
            PathOnClient = 'Evidencia.jpg',
            VersionData = EncodingUtil.base64Decode('AA=='),
            IsMajorVersion = true
        );
        insert cv;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = orden.Id,
            ContentDocumentId = documents[0].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;

        List<String> orderIdList = new List<String>{orden.Id};

        Map<Id, ContentVersion> result = MisPedidosClass.getOrderEvidence(orderIdList); 
        System.assertEquals(result.size(), 1, 'Map should not be empty');
        Test.stopTest(); 
    }

    @IsTest
    static void testCertificateOrder() {
        Test.startTest(); 
        Order__c orden = [SELECT Id FROM Order__c LIMIT 1]; 
        Order__c result = MisPedidosClass.certificateOrder(String.valueOf(orden.Id)); 
        Assert.isNotNull(result, 'result should not be null');
        Test.stopTest(); 
    }

    @IsTest
    static void testRejectOrder() {
        Test.startTest(); 
        Order__c orden = [SELECT Id FROM Order__c LIMIT 1]; 
        Order__c rejectedOrder = MisPedidosClass.rejectOrder(String.valueOf(orden.Id));
        System.assertNotEquals(null, rejectedOrder);
        Test.stopTest(); 
    }

    @IsTest
    static void testGetFieldIdsList() {
        Test.startTest(); 
        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];

        ContentVersion cv = new ContentVersion(
            Title = 'Evidencia',
            PathOnClient = 'Evidencia.jpg',
            VersionData = EncodingUtil.base64Decode('AA=='),
            IsMajorVersion = true
        );
        insert cv;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink cdl = new ContentDocumentLink(
            LinkedEntityId = orden.Id,
            ContentDocumentId = documents[0].Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;

        List<String> result = MisPedidosClass.getFieldIdsList(orden.Id);  
        System.assertNotEquals(null, result);
        Test.stopTest(); 
    }

    @IsTest
    static void testReenviarOrden() {
        Test.startTest(); 
        Order__c orden = [SELECT Id FROM Order__c LIMIT 1];

        MisPedidosClass.reenviarOrden(orden.Id);

        Order__c updatedOrder = [SELECT Id, Estatus__c FROM Order__c WHERE Id =: orden.Id LIMIT 1];
        System.assertEquals('Procesando', updatedOrder.Estatus__c); 
        Test.stopTest(); 
    }
}