unpackaged/main/default/objects/Account/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <label>Tipo UMU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAF</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CMCT</fullName>
            </value>
            <value>
                <fullName>CMF</fullName>
            </value>
            <value>
                <fullName>CMFE</fullName>
            </value>
            <value>
                <fullName>CMN</fullName>
            </value>
            <value>
                <fullName>HG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>UE</fullName>
            </value>
            <value>
                <fullName>UMF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Es_Programa__c.field-meta.xml
<CustomField>
    <fullName>Es_Programa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Programa?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Pedido_Original__c.field-meta.xml
<CustomField>
    <fullName>Pedido_Original__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido Original</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PedidoFields.cls
public class PedidoFields {
    private static Integer contadorDeUmus = 1;
    private static final String DEFAULT_ID_ORDINARIO = '000001';
    private static final String DEFAULT_ID_PROGRAMA = '00001';
    private static final String DEFAULT_ID_NO_ORDINARIO_HR_CMN = '-01';

    private static final List<String> UMUS_PRIORIDAD = new List<String>{
        'HR', 'CMN'
    };

    private static final List<String> TIPOS_DE_PEDIDO = new List<String>{
        'Ordinario', 'Extraordinario', 'Urgencia Médica', 'Soporte de Vida', 'Emergencia Sanitaria'
    };

    private static final List<String> TIPOS_DE_PEDIDO_PROGRAMA = new List<String>{
        'Programa', 'Urgencia Médica', 'Soporte de Vida', 'Emergencia Sanitaria'
    };
    
	public static void insertIdDePedido(List<Pedido__c> pedidoList){ 

        List<Pedido__c> lastPedidoIdList = [
            SELECT ID_de_Pedido__c, Es_Programa__c, Tipo_de_Pedido__c, UMU__c, UMU__r.Tipo_UMU__c
            FROM Pedido__c 
            WHERE Tipo_de_Pedido__c IN: TIPOS_DE_PEDIDO
                AND ID_de_Pedido__c != null
                AND Es_Programa__c = false
                AND Pedido_Original__c = null
            ORDER BY Name DESC 
            LIMIT 1
        ]; 

        String lastPedidoId = null;
        if (!lastPedidoIdList.isEmpty()){ 
            lastPedidoId = lastPedidoIdList[0].ID_de_Pedido__c;
        } 
        System.debug(lastPedidoId);

        List<Pedido__c> lastPedidoIdProgramaList = [
            SELECT ID_de_Pedido__c, Tipo_de_Pedido__c
            FROM Pedido__c 
            WHERE Tipo_de_Pedido__c IN: TIPOS_DE_PEDIDO_PROGRAMA
                AND ID_de_Pedido__c != null
                AND Es_Programa__c = true
                AND Pedido_Original__c = null
            ORDER BY Name DESC 
            LIMIT 1
        ];

        String lastPedidoIdPrograma = null;
        if (!lastPedidoIdProgramaList.isEmpty()){ 
            lastPedidoIdPrograma = lastPedidoIdProgramaList[0].ID_de_Pedido__c;
        } 
        System.debug(lastPedidoIdPrograma);
       

        Set<Id> umuIdSet = new Set<Id>();
        for (Pedido__c pedido : pedidoList){
            if (pedido.UMU__c != null){
                umuIdSet.add(pedido.UMU__c);
            }
        }
        System.debug(umuIdSet);
        Map<Id, Account> umuMap = new Map<Id, Account>([
            SELECT Id, Name, UMU__c
            FROM Account 
            WHERE Id IN: umuIdSet 
                AND UMU__c IN: UMUS_PRIORIDAD
        ]);
        System.debug(umuMap);

        if(Trigger.isBefore && Trigger.isInsert){
            contadorDeUmus = 1;
        } 

        for (Pedido__c pedido : pedidoList) { 
            if(String.isBlank(pedido.ID_de_Pedido__c)){
                if(!pedido.Es_Programa__c){
                    switch on pedido.Tipo_de_Pedido__c {
                        when 'Ordinario', 'Extraordinario', 'Urgencia Médica', 'Soporte de Vida', 'Emergencia Sanitaria'{ 
                            if(lastPedidoId != null){ 
                                String firstSixCharsStrId = lastPedidoId.substring(0, 6);
                                Integer newPedidoId = Integer.valueOf(firstSixCharsStrId) + 1;
                                String pedidoIdSuffix = '';
                                if(pedido.Tipo_de_Pedido__c != 'Ordinario' && pedido.UMU__c != null && umuMap.containsKey(pedido.UMU__c)){
                                    pedidoIdSuffix = DEFAULT_ID_NO_ORDINARIO_HR_CMN;
                                } 
                                pedido.ID_de_Pedido__c = String.valueOf(newPedidoId).leftPad(6, '0') + pedidoIdSuffix; 
                                lastPedidoId = String.valueOf(newPedidoId).leftPad(6, '0') + pedidoIdSuffix;
                            } else{ 
                                String pedidoIdSuffix = '';
                                if(pedido.Tipo_de_Pedido__c != 'Ordinario' && pedido.UMU__c != null && umuMap.containsKey(pedido.UMU__c)){
                                    pedidoIdSuffix = DEFAULT_ID_NO_ORDINARIO_HR_CMN;
                                } 
                                pedido.ID_de_Pedido__c = DEFAULT_ID_ORDINARIO + pedidoIdSuffix;  
                                lastPedidoId = DEFAULT_ID_ORDINARIO + pedidoIdSuffix;
                            } 
                        } 
                    }
                } else{
                    switch on pedido.Tipo_de_Pedido__c {
                        when 'Programa', 'Urgencia Médica', 'Soporte de Vida', 'Emergencia Sanitaria'{
                            if(lastPedidoIdPrograma != null){ 
                                String firstFiveCharsStrId = lastPedidoIdPrograma.substring(0, 5);
                                Integer newPedidoId = Integer.valueOf(firstFiveCharsStrId) + 1;
                                String pedidoIdSuffix = String.valueOf(contadorDeUmus).leftPad(4, '0');
                                String idString = String.valueOf(newPedidoId).leftPad(5, '0') + '-' + pedidoIdSuffix;
                                pedido.ID_de_Pedido__c = idString; 
                                contadorDeUmus ++;
                            } else{
                                String idString = DEFAULT_ID_PROGRAMA + '-' + String.valueOf(contadorDeUmus).leftPad(4, '0');
                                pedido.ID_de_Pedido__c = idString;
                                contadorDeUmus ++;
                            } 
                        }
                    }
                }
            } 
        }   
    }
    
}