unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/D_a_de_Pedido__c/D_a_de_Pedido__c.object-meta.xml
<CustomObject>
    <label>Día de Pedido</label>
    <nameField>
        <displayFormat>DP-{00000000}</displayFormat>
        <label>Día de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Días de Pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>Días de Pedido</relationshipLabel>
    <relationshipName>D_as_de_Pedido</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ID_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Pedido__c</fullName>
    <label>ID de Pedido</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <formula>LEFT(Order_Number__c, 3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero de Subalmacen</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <formula>VALUE(Product__r.Subalmacen__r.Numero_de_Subalmacen__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numero de Subalmacen</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order_Line_Item_Classification__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Item Classification</label>
    <referenceTo>Order_Line_Item_Classification__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item_Classification__c/Order_Line_Item_Classification__c.object-meta.xml
<CustomObject>
    <label>Order Line Item Classification</label>
    <nameField>
        <label>Order Line Item Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Item Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item_Classification__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <label>Número de Subalmacén</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ControladorGeneracionPedidosTest.cls
@isTest
public with sharing class ControladorGeneracionPedidosTest {
    
    @TestSetup
    static void setup() {
        Account acc = TestDataFactory.createSingleAccount('Test Account');
        Account acc2 = TestDataFactory.createSingleAccount('Test Account 2');
        Contact con = TestDataFactory.createSingleContactRelatedToAccount(acc.Id, 'Louise', 'Santana', 'Todas');

        Product2 p1 = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        Product2 p2 = TestDataFactory.createSingleProduct2('JARABE PARA GRIPA');
        
        String jsonToSend = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            acc.Id + '","TipoDePedido": "Ordinario","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' + p2.Id + '","CantidadSolicitada": 5}]}]'; 
        String jsonToSend2 = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": true, "IdUmu": "' +
            acc2.Id + '","TipoDePedido": "Programa","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' + p2.Id + '","CantidadSolicitada": 5}]}]';
        String jsonToSend3 = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": true, "IdUmu": "' +
            acc2.Id + '","TipoDePedido": "Emergencia Sanitaria","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' + p2.Id + '","CantidadSolicitada": 5}]}]';
        String jsonToSend4 = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            acc2.Id + '","TipoDePedido": "Urgencia Médica","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' + p2.Id + '","CantidadSolicitada": 5}]}]';
        String jsonToSend5 = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            acc.Id + '","TipoDePedido": "Extraordinario","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' +
            p2.Id + '","CantidadSolicitada": 5}]}]';
        String jsonToSend6 = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            acc.Id + '","TipoDePedido": "Soporte de Vida","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' +
            p2.Id + '","CantidadSolicitada": 5}]}]';
        
        Test.startTest();
        controladorGeneracionPedidos.deserializeOrders(jsonToSend);
        controladorGeneracionPedidos.deserializeOrders(jsonToSend2);
        controladorGeneracionPedidos.deserializeOrders(jsonToSend3);
        controladorGeneracionPedidos.deserializeOrders(jsonToSend4);
        controladorGeneracionPedidos.deserializeOrders(jsonToSend5);
        controladorGeneracionPedidos.deserializeOrders(jsonToSend6);
        Test.stopTest();
    }
    
    @isTest
    public static void orderTest() { 
        Test.startTest();
        List<Order__c> orders = [
            SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c
            FROM Order__c];
        System.assertEquals(6, orders.size(), 'Expected 6 Order__c record to be created.');
        
        List<Order_Line_Item__c> orderItems = [
            SELECT Id, Product__c, Cantidad_Solicitada__c, Order__c
            FROM Order_Line_Item__c
        ];
        System.assertEquals(12, orderItems.size(),'Expected 12 order_Line_Item__c record to be created.');
        
        System.assertEquals(orders[0].Id, orderItems[0].Order__c, 
                            'Order_Line_Item__c record does not reference the correct Order__c record.');
        System.assertEquals(5, orderItems[0].Cantidad_Solicitada__c,
                            'Order_Line_Item__c record does not have the expected Cantidad_Solicitada__c value.');
        Test.stopTest();
    }
    
    @isTest
    public static void createCSVTest() {
        String title, versionData, pathOnClient, programName, summary;
        title = 'Documento General.csv';
        pathOnClient = 'DocumentoGeneral.csv';
        programName = 'Claves DPN';
        summary = '{"numItems":2,"numCantidadUmus":2,"sumCantidadAutorizada":40}';
        versionData = 'REVMRUdBQ0lPTixVTVUsQ0xBVkUgUFJFU1VQVUVTVEFMLE5PTUJSRSBVTVUsVElQTyBERSBQRURJR'
            + 'E8sRkVDSEEgREUgU09MSUNJVFVELEZPTElPIERFTCBQRURJRE8sQ0xBVkUsREVTQ1JJUENJT04gQ0xBVkUsQ0F'
            + 'OVElEQUQgQVVUT1JJWkFEQSxDQU5USURBRCBDT0xPQ0FEQSBFTiBTQVAsRVNUQVRVUyxGRUNIQSBMSU1JVEUgR'
            + 'EUgRU5UUkVHQSxJRCBERSBQUk9HUkFNQSxQUk9HUkFNQQowMDEtQUdVQVNDQUxJRU5URVMsMDAxLCcwMDEyMDQw'
            + 'MCxIRyBBR1VBU0NBTElFTlRFUyxQcm9ncmFtYSwyMDIzLTA2LTMwLCcwMDA3NzksJzAxMDAwMDU3NDMwMCxMSV'
            + 'JBR0xVVElERS4gU09MVUNJw5NOIElOWUVDVEFCTEUgQ0FEQSBNSUxJTElUUk8gQ09OVElFTkU6IExJUkFHTFVUS'
            + 'URFIChBRE4gUkVDT01CSU5BTlRFKSA2IE1HIEVOVkFTRSBDT04gMiBQTFVNQVMgQ09OIENBUlRVQ0hPIERFIDMg'
            + 'TUwsMTAsMTAsQVVUT1JJWkFETywyMDIzLTA3LTAzLFMyNyxDbGF2ZXMgRFBOCjAwMS1BR1VBU0NBTElFTlRFUyw'
            + 'wMDEsJzAwMTIwNDAwLEhHIEFHVUFTQ0FMSUVOVEVTLFByb2dyYW1hLDIwMjMtMDYtMzAsJzAwMDc3OSwnMDEwMD'
            + 'AwNTg0NTAwLFNJTERFTkFGSUwuIFRBQkxFVEEgQ0FEQSBUQUJMRVRBIENPTlRJRU5FOiBDSVRSQVRPIERFIFNJT'
            + 'ERFTkFGSUwgRVFVSVZBTEVOVEUgQSAyMCBNRyBERSBTSUxERU5BRklMIEVOVkFTRSBDT04gOTAgVEFCTEVUQVMs'
            + 'MTAsMTAsQVVUT1JJWkFETywyMDIzLTA3LTAzLFMyNyxDbGF2ZXMgRFBOCjAwMS1BR1VBU0NBTElFTlRFUywwMDI'
            + 'sJzAwMTIwNTAxLFVNRiBDQUxWSUxMTyxQcm9ncmFtYSwyMDIzLTA2LTMwLCcwMDA3ODAsJzAxMDAwMDU3NDMwMC'
            + 'xMSVJBR0xVVElERS4gU09MVUNJw5NOIElOWUVDVEFCTEUgQ0FEQSBNSUxJTElUUk8gQ09OVElFTkU6IExJUkFHT'
            + 'FVUSURFIChBRE4gUkVDT01CSU5BTlRFKSA2IE1HIEVOVkFTRSBDT04gMiBQTFVNQVMgQ09OIENBUlRVQ0hPIERF'
            + 'IDMgTUwsMTAsMTAsQVVUT1JJWkFETywyMDIzLTA3LTAzLFMyNyxDbGF2ZXMgRFBOCjAwMS1BR1VBU0NBTElFTlR'
            + 'FUywwMDIsJzAwMTIwNTAxLFVNRiBDQUxWSUxMTyxQcm9ncmFtYSwyMDIzLTA2LTMwLCcwMDA3ODAsJzAxMDAwMD'
            + 'U4NDUwMCxTSUxERU5BRklMLiBUQUJMRVRBIENBREEgVEFCTEVUQSBDT05USUVORTogQ0lUUkFUTyBERSBTSUxERU'
            + '5BRklMIEVRVUlWQUxFTlRFIEEgMjAgTUcgREUgU0lMREVOQUZJTCBFTlZBU0UgQ09OIDkwIFRBQkxFVEFTLDEwLD'
            + 'EwLEFVVE9SSVpBRE8sMjAyMy0wNy0wMyxTMjcsQ2xhdmVzIERQTgo=';
        
        Test.startTest();
        Order__c order = [
            SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c, Pedido__r.ID_de_Pedido__c
            FROM Order__c 
            WHERE Tipo_de_Pedido__c = 'Extraordinario' LIMIT 1
        ];
        
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        
        ContentVersion result = controladorGeneracionPedidos.createContentVersion(
            title, versionData, pathOnClient, con.Id, order.Id, programName, summary);
        System.debug('result---> ' + result);
        System.assertEquals('Documento General.csv', result.Title, 'The title not match');
        Test.stopTest();
    }
    
    @isTest
    public static void createCSVFilesTest() {
        Test.startTest();
        Order__c order = [
            SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c, Pedido__r.ID_de_Pedido__c
            FROM Order__c 
            WHERE Tipo_de_Pedido__c = 'Soporte de Vida' LIMIT 1
        ];
        
        List<Order_Line_Item__c> oliList = [
            SELECT Id, Product__r.Name
            FROM Order_Line_Item__c WHERE Order__c = :order.Id
        ];
        
        List<String> productList = new List<String>();
        for(Order_Line_Item__c oli : oliList) {
            if(!productList.contains(oli.Id)) {
                 productList.add(oli.Id);
            }
        }
        
        ContentVersion result = controladorGeneracionPedidos.createCSVFiles(productList, true);
        String contentDocumentTitle = order.Pedido__r.ID_de_Pedido__c + '.csv';
        System.assertEquals(contentDocumentTitle, result.Title, 'The title not match');
        Test.stopTest();
    }
    
    @isTest
    public static void getInfoClavesDPNActivaTest() {
        Account acc = TestDataFactory.createSingleAccount('Test Account');
        Product2 p = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        DPN__c dpn = TestDataFactory.createSingleDPN(acc.Id);
        DPN_Line_Item__c lineItem = TestDataFactory.createSingleDPNLineItem(dpn.Id, p.Id);
        
        test.startTest();
        Integer result = controladorGeneracionPedidos.getInfoClavesDPNActiva(acc.Id, p.Id, true);
        System.assertEquals(50, result, 'The quantity returned is incorrect');
        test.stopTest();
    }
    
    @isTest
    public static void getUltimaFechaActivaDPNTest() {
        Account acc = TestDataFactory.createSingleAccount('Test Account');
        Product2 p = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        DPN__c dpn = TestDataFactory.createSingleDPN(acc.Id);
        D_a_de_Pedido__c orderDate = TestDataFactory.createSingleOrderDate(dpn.Id);
        DPN_Line_Item__c lineItem = TestDataFactory.createSingleDPNLineItem(dpn.Id, p.Id);
        
        test.startTest();
        Date result = controladorGeneracionPedidos.getUltimaFechaActivaDPN(acc.Id, true);
        System.assertEquals(orderDate.Fecha__c, result, 'The date returned is incorrect');
        test.stopTest();
    }
    
    @isTest
    public static void getOrderIdTest() {
        Test.startTest();
        List<Order__c> orders = [
            SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c, Pedido__r.ID_de_Pedido__c
            FROM Order__c 
        ];
        
        Set<Id> result = controladorGeneracionPedidos.getOrderId(orders);
        List<Id> idList = new List<Id>(result);
        System.assertEquals(orders.size(), idList.size(), 'The order list size musb be 6');
        Test.stopTest();
    }
    
    @isTest
    public static void getSubalmacenFilterTest() {
        Test.startTest();
        Order__c order = [
            SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c, Pedido__r.ID_de_Pedido__c
            FROM Order__c 
            WHERE Tipo_de_Pedido__c = 'Soporte de Vida' LIMIT 1
        ];
        
        List<Order_Line_Item__c> oliList = [
            SELECT Id, Name, Order__c, UMU__c, Pedido__c, Numero_de_Subalmacen__c, Order_Line_Item_Classification__c, Product__c 
            FROM Order_Line_Item__c 
            WHERE Order__c = :order.Id
        ];
        
        Map<Id, List<Order_Line_Item__c>> oliMap = new Map<Id, List<Order_Line_Item__c>>();
        for(Order_Line_Item__c oli : oliList) {
            if(!oliMap.containsKey(oli.Order__c)){
                oliMap.put(oli.Order__c, new List<Order_Line_Item__c>());
            }
            oliMap.get(oli.Order__c).add(oli);
               
        }
        
        Map<Decimal, List<Id>> result = controladorGeneracionPedidos.GetSubalmacenFilter(String.valueOf(order.Id), oliMap);
        System.assertEquals(1, result.size(), 'The map size must be 1'); 
    }
    
    /*@isTest
    public static void sendEmailSolicitudNoOrdTest() {
        Account acc = TestDataFactory.createSingleAccount('Test Account');
        Contact con = TestDataFactory.createSingleContactRelatedToAccount(acc.Id, 'Louise', 'Santana', 'Todas');
        
        Product2 p1 = TestDataFactory.createSingleProduct2('LINAGLIPTINA');
        Product2 p2 = TestDataFactory.createSingleProduct2('JARABE PARA GRIPA');
        
        String jsonToSend = '[{"Idcontacto":"' + con.Id + '" , "esPrograma": false, "IdUmu": "' +
            acc.Id + '","TipoDePedido": "Extraordinario","ordenesDetails": [{"insumoId": "' +
            p1.Id + '","CantidadSolicitada": 5},{"insumoId": "' +
            p2.Id + '","CantidadSolicitada": 5}]}]';
        
        User user = TestDataFactory.initCommunityLoginUser('testuser');
        
        System.runAs(user) {
            test.startTest();
            List<Order__c> orders = controladorGeneracionPedidos.deserializeOrders(jsonToSend);
            
            Order__c order = [
                SELECT Id, UMU__c, Tipo_de_Pedido__c, Total_de_Piezas__c, Pedido__r.ID_de_Pedido__c
                FROM Order__c 
                WHERE Id = :orders.get(0).Id LIMIT 1
            ];
            
            List<String> orderIds = new List<String>();
            orderIds.add(order.Id);
            
            controladorGeneracionPedidos.sendEmailSolicitudNoOrd(orderIds);
            
            //System.assertEquals(true, result, 'The result was false');
            test.stopTest();   
        }
    }*/
}