unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ServicioSalidaAlmacenTest.cls
@isTest
private class ServicioSalidaAlmacenTest {
    
    @testSetup 
    static void setup() {
        Account umuTest = TestDataFactory.createSingleAccount('Hospital UMU');
        System.debug(umuTest);
        
        Contact contactTest = TestDataFactory.createSingleContactRelatedToAccount(umuTest.Id,'contact Test FirstName', 'contact Test LastName', 'Todas');
        System.debug(contactTest);
        
        Product2 claveTest = TestDataFactory.createSingleProduct('Aspirina', 'MEDICINE');
        System.debug(claveTest);
        claveTest.Product_Code_ID__c = '12345asdas';
        update claveTest;
            
        Order__c orderTest = new Order__c();
        orderTest.Tipo_de_Pedido__c = 'Ordinario';
        orderTest.order_number__c = '500-1111';
		orderTest.UMU__c = umuTest.Id;
       	orderTest.Contacto__c = contactTest.Id;
        orderTest.Estatus__c = 'Preparando Envío';
        System.debug(orderTest);
        
        
        
		insert orderTest;
        
        Order_Line_Item__c orderLineItemTest = new Order_Line_Item__c();
        orderLineItemTest.Product__c = claveTest.Id;
		orderLineItemTest.Cantidad_Solicitada__c = 10;
        orderLineItemTest.Cantidad_de_Piezas__c = 10;
		orderLineItemTest.Order__c = orderTest.Id;
		orderLineItemTest.UMU__c = umuTest.Id;
        
        insert orderLineItemTest;
        
    }
    
    @isTest
    static void testCreateRecord() {
        Test.startTest();
        IntegrationHttpCalloutMock httpMock = new IntegrationHttpCalloutMock(false);
        Test.setMock(HttpCalloutMock.class, httpMock);

        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/SalidaAlmacen';
        req.httpMethod = 'POST';
        
        List<ServicioSalidaAlmacen.Order> orders = new List<ServicioSalidaAlmacen.Order>();
        
        ServicioSalidaAlmacen.Order order = new ServicioSalidaAlmacen.Order();
        order.order_number = '500-1111';
        order.load = '500-1111';
        order.box_quantity = 10;
        order.skus = new List<ServicioSalidaAlmacen.SkuInfo>();
        
        ServicioSalidaAlmacen.SkuInfo sku = new ServicioSalidaAlmacen.SkuInfo();
        sku.sku = '12345asdas';
        sku.quantity = 5;
        sku.avg_cost = 10.0;
        sku.lote_info = new List<ServicioSalidaAlmacen.LoteInfo>();
        
        ServicioSalidaAlmacen.LoteInfo lote = new ServicioSalidaAlmacen.LoteInfo();
        lote.quantity = 2;
        lote.expiration_date = '05/01/2023';
        lote.lot_number = '5DSA4';
        
        sku.lote_info.add(lote);
        order.skus.add(sku);
        orders.add(order);
        
        String requestBodyJson = JSON.serialize(orders);
        req.requestBody = Blob.valueOf(requestBodyJson);
        
        RestResponse res = new RestResponse();
        
        RestContext.request = req;
        RestContext.response = res;
        try {
            ServicioSalidaAlmacen.createRecord();
        } catch (Exception ex) {
            System.debug('Exception: ' + ex.getMessage());
        }
        
        Test.stopTest();
        
        System.assertEquals(200, res.statusCode);
        
        ServicioSalidaAlmacen.RespuestaTraxion traxionResponse = (ServicioSalidaAlmacen.RespuestaTraxion) JSON.deserialize(res.responseBody.toString(), ServicioSalidaAlmacen.RespuestaTraxion.class);
        
        System.assertEquals(true, traxionResponse.completedSuccessfully);
        System.assertEquals('successful', traxionResponse.response.message);


    }

}