unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <description>Medicamento/Material de Curación.</description>
    <formula>TEXT(Producto__r.Simple_Classification__c)</formula>
    <label>Clasificación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Estatus_de_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Estatus_de_Conteo__c</fullName>
    <description>Estatus del conteo del día.</description>
    <label>Estatus de Conteo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Fecha_Inicio_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Conteo__c</fullName>
    <description>Fecha en que inicia el conteo del día.</description>
    <label>Fecha Inicio Conteo</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <description>Tipo de Insumo para inventarios. Ordinario, Programa, Vacunas, Compra local.</description>
    <formula>TEXT( Producto__r.Programa__r.Inventario__c )</formula>
    <label>Tipo de Insumo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Estatus del inventario.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registrado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Firmado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Firmado_Por__c.field-meta.xml
<CustomField>
    <fullName>Firmado_Por__c</fullName>
    <description>Nombre del usuario que firma el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a Firmado.</description>
    <label>Firmado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Registrado_Por__c.field-meta.xml
<CustomField>
    <fullName>Registrado_Por__c</fullName>
    <description>Nombre del usuario que registra el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a En Firma.</description>
    <label>Registrado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <description>Día en que fue firmado el registro del inventario por el jefe de almacén.</description>
    <label>Fecha De Firma</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Compra Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>UMU en la cual se realiza el registro de inventario.</description>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventarios</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Actual__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Actual__c</fullName>
    <description>Cantidad actual contada en el lote.</description>
    <label>Conteo Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Anterior__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Anterior__c</fullName>
    <description>Cantidad previa contada en el lote.</description>
    <label>Conteo Anterior</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Estatus_Conteo_Lote__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Conteo_Lote__c</fullName>
    <label>Estatus Conteo Lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Caducidad__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Caducidad__c</fullName>
    <description>Fecha de caducidad del insumo en el lote.</description>
    <label>Fecha de Caducidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Modificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Modificaci_n__c</fullName>
    <description>Fecha de última modificación.</description>
    <label>Fecha de Modificación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <description>Texto que identifica al lote.</description>
    <label>Lote</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/InventarioFieldsTest.cls
@isTest
public with sharing class InventarioFieldsTest {
    @TestSetup
    static void createTestData() {
        String uniqueUserName = String.ValueOf(System.Now()).replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);

        List<Id> accountIdList = new List<Id>(); 

        for(AccountContactRelation accConRel : [ SELECT AccountId, Account.Name FROM AccountContactRelation WHERE ContactId =: user.ContactId LIMIT 1]){
            accountIdList.add(accConRel.AccountId);
        }

        List<Product2> listproduct = TestDataFactory.createMultipleProduct2('Producto', 2);

        Inventario__c inventario = new Inventario__c(); 
        inventario.Clasificacion__c = 'Material de Curación';
        inventario.Tipo_de_Insumo__c = 'Ordinario';
        inventario.UMU__c = accountIdList[0]; 
        inventario.Estatus__c = 'Registrado';
        inventario.Registrado_Por__c = null;
        insert inventario;

        Clave_de_Inventario__c cveInventario = new Clave_de_Inventario__c(); 
        cveInventario.Producto__c = listproduct[0].Id;
        cveInventario.Inventario__c = inventario.Id;
        cveInventario.Fecha_Inicio_Conteo__c = null;
        cveInventario.Estatus_de_Conteo__c = null;
        insert cveInventario;

        Lote_de_Inventario__c loteInventario = new Lote_de_Inventario__c(); 
        loteInventario.Conteo_Actual__c = 0;
        loteInventario.Conteo_Anterior__c = 0;
        loteInventario.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInventario.Lote__c = 'LOTE01';
        loteInventario.Clave_de_Inventario__c = cveInventario.Id; 
        loteInventario.Estatus_Conteo_Lote__c = 'Contado';
        //loteInventario.Fecha_de_Modificaci_n__c = System.Today();
        insert loteInventario;

        Lote_de_Inventario__c loteInventario2 = new Lote_de_Inventario__c(); 
        loteInventario2.Conteo_Actual__c = 0;
        loteInventario2.Conteo_Anterior__c = 0;
        loteInventario2.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInventario2.Lote__c = 'LOTE02';
        loteInventario2.Clave_de_Inventario__c = cveInventario.Id;
        loteInventario2.Estatus_Conteo_Lote__c = 'Contado';
        //loteInventario2.Fecha_de_Modificaci_n__c = System.Today();
        insert loteInventario2;

        cveInventario.Estatus_de_Conteo__c = 'Contado';
        update cveInventario;

    }

    @IsTest
    static void testInvEnFirma() {

        Inventario__c inv = [SELECT Id, Estatus__c, Signed_Date__c, Registrado_Por__c FROM Inventario__c LIMIT 1];

        Test.startTest();
            inv.Estatus__c = 'En Firma';
            update inv;
        Test.stopTest();
        System.assertEquals(UserInfo.getName(), [SELECT Id, Estatus__c, Signed_Date__c, Registrado_Por__c FROM Inventario__c LIMIT 1].Registrado_Por__c, 'Registrado Por diferente a UserInfo.getName()');
        
    }

    @IsTest
    static void testInvFirmado() {

        System.debug('testInvFirmado: ' + [SELECT Id, Estatus__c, Signed_Date__c FROM Inventario__c ]);

        Inventario__c invF = [SELECT Id, Estatus__c, Signed_Date__c FROM Inventario__c WHERE Estatus__c = 'Registrado' LIMIT 1];

        Test.startTest();
            invF.Estatus__c = 'En Firma';
            update invF;

            invF.Estatus__c = 'Firmado';
            update invF;
        Test.stopTest();

        System.assertEquals(UserInfo.getName(), [SELECT Id, Estatus__c, Signed_Date__c, Firmado_Por__c FROM Inventario__c LIMIT 1].Firmado_Por__c, 'Firmado Por diferente a UserInfo.getName()');
        
    }
}