unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario ANS al que se le transfirieron las ordenes de la entrega.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informacion_de_Transferencia__c/Informacion_de_Transferencia__c.object-meta.xml
<CustomObject>
    <description>Sirve para guardar los IDs de las ordenes que serán transferidas a un contacto ANS.</description>
    <label>Informacion de Transferencia</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Informacion de Transferencia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informacion de Transferencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_de_Transferencia__c/fields/Codigo_De_Transferencia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_De_Transferencia__c</fullName>
    <description>Guarda el codigio que se utiliza para transferir los records de Ordenes.</description>
    <label>Codigo De Transferencia</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Informacion_de_Transferencia__c/fields/Identificadores_de_Ordenes__c.field-meta.xml
<CustomField>
    <fullName>Identificadores_de_Ordenes__c</fullName>
    <description>Guarda los ID&#39;s de las ordenes que van a ser transferidas.</description>
    <label>Identificadores de Ordenes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Informacion_de_Transferencia__c/fields/Transferido__c.field-meta.xml
<CustomField>
    <fullName>Transferido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transferido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cantidad_de_Cajas_en_la_Orden__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Cajas_en_la_Orden__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de cajas que viene en la orden desde el WMS.</description>
    <label>Cantidad de Cajas en la Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_de_Cajas_en_la_Orden__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Cajas_en_la_Orden__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Este campo dice cuantas cajas vienen en la orden.</description>
    <label>Cantidad de Cajas en la Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Cantidad_de_Cajas_Faltantes_en_la_Orden__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Cajas_Faltantes_en_la_Orden__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Guarda la cantidad de cajas faltantes en la orden.</description>
    <label>Cantidad de Cajas Faltantes en la Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Pedido__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Subalmacen__c</fullName>
    <formula>CASE(
LEFT(Order_Number__c, 3),
&#39;101&#39;, &#39;MEDICAMENTO AG&#39;,
&#39;102&#39;, &#39;MATERIAL CURACION AG&#39;,
&#39;301&#39;, &#39;MEDICAMENTO AE&#39;,
&#39;302&#39;, &#39;MATERIAL DE CURACÍON AE&#39;,
&#39;401&#39;, &#39;MEDICAMENTO CONTROLADO&#39;,
&#39;501&#39;, &#39;MEDICAMENTO REFRIGERADO&#39;,
&#39;502&#39;, &#39;MATERIAL DE CURACIÓN REFRIGERADO&#39;,
&#39;503&#39;, &#39;MEDICAMENTO CONTROLADO REFRIGERADO&#39;,
&#39;601&#39;, &#39;MEDICAMENTO CONGELADO&#39;,
&#39;Almacen Desconocido&#39;
)</formula>
    <label>Subalmacen</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Usuario_ANS__c.field-meta.xml
<CustomField>
    <fullName>Usuario_ANS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Usuario al que el transportista le transfiere las ordenes de la entrega por UMU.</description>
    <label>Usuario ANS</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Ver Detalles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subalmacen__c/Subalmacen__c.object-meta.xml
<CustomObject>
    <description>Almacén que maneja un Stock propio de la Dependencia a la cual está inscrito.</description>
    <label>Subalmacen</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subalmacenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TransferInformationService.cls
public without sharing class TransferInformationService {
  @AuraEnabled
  public static String createTransferInformation(
    String recordIds,
    String UmuId
  ) {
    // Split the incoming record IDs into a list
    List<String> incomingRecordIdsList = recordIds.split(',');

    // Convert the list to a set of Ids
    Set<String> incomingRecordIdsSet = new Set<String>();

    for (String recordId : incomingRecordIdsList) {
      incomingRecordIdsSet.add((String) recordId);
    }
    // TODO: Add try catch block and manage exception and throw aura exceptions

    // Query all TransferInformation records that have not been transferred yet
    List<Informacion_de_Transferencia__c> existingTransferInfos = [
      SELECT Id, Codigo_De_Transferencia__c, Identificadores_de_Ordenes__c
      FROM Informacion_de_Transferencia__c
      WHERE Transferido__c = FALSE
    ];

    // Iterate over the existing TransferInformation records
    for (
      Informacion_de_Transferencia__c existingTransferInfo : existingTransferInfos
    ) {
      // Split the stored record IDs into a list and convert to a set
      Set<String> storedRecordIdsSet = new Set<String>();
      List<String> storedRecordIdsList = existingTransferInfo.Identificadores_de_Ordenes__c.split(
        ','
      );
      for (String recordId : storedRecordIdsList) {
        storedRecordIdsSet.add((String) recordId);
      }

      // If the sets are equal, return the existing unique code
      if (storedRecordIdsSet.equals(incomingRecordIdsSet)) {
        return existingTransferInfo.Codigo_De_Transferencia__c;
      }
    }
    // If no matching TransferInformation record was found, create a new one
    Informacion_de_Transferencia__c transferInfo = new Informacion_de_Transferencia__c();
    transferInfo.Identificadores_de_Ordenes__c = recordIds;
    // transferInfo.UmuId = UmuId;

    insert transferInfo;

    // Generate a unique number
    String formattedNum = generateRandomNumber();
    System.debug(formattedNum);
    String uniqueCode = generateUniqueCode(formattedNum);

    // Update the transfer information record with the unique code
    transferInfo.Codigo_De_Transferencia__c = uniqueCode;
    update transferInfo;

    return uniqueCode;
  }

  private static String generateRandomNumber() {
    // Generate a unique code
    Integer randomNum = (Integer) Math.floor(
      Math.random() * (999999999 - 100000000 + 1) + 100000000
    );
    String numString = String.valueOf(randomNum);
    String formattedNum = numString.leftPad(9, '0');
    System.debug(formattedNum);

    return formattedNum;
  }

  public static String generateUniqueCode(String randomNumberString) {
    String uniqueCode = '';
    String possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

    for (Integer i = 0; i < 4; i++) {
      Integer idx = Math.mod(
        Math.abs(Crypto.getRandomInteger()),
        possible.length()
      );
      uniqueCode += possible.substring(idx, idx + 1);
    }

    return randomNumberString + uniqueCode;
  }

  @AuraEnabled
  public static String getOrdersBeforeTransfer(String uniqueCode) {
    // Query for the TransferInformation record
    List<Informacion_de_Transferencia__c> transferInfo = [
      SELECT Id, Identificadores_de_Ordenes__c, Transferido__c
      FROM Informacion_de_Transferencia__c
      WHERE Codigo_De_Transferencia__c = :uniqueCode
      LIMIT 1
    ];

    // If the records have already been transferred, exit the method
    if (transferInfo.size() == 0) {
      return 'Las ordenes ya fueron transferidas anteriormente o el codigo no fue generado.';
    }

    List<String> recordIds = new List<String>();
    for (
      String recordId : transferInfo[0].Identificadores_de_Ordenes__c.split(',')
    ) {
      System.debug(recordId);
      recordIds.add(recordId.normalizeSpace());
    }

    // Query for the records to transfer
    List<Order__c> recordsToTransfer = [
      SELECT
        Id,
        Order_Number__c,
        OwnerId,
        Estatus__c,
        UMU__c,
        Usuario_ANS__c,
        Cantidad_de_Cajas_en_la_Orden__c,
        Cantidad_de_Cajas_Faltantes_en_la_Orden__c,
        Pedido__r.Fecha_Limite_de_Entrega__c,
        Entrega__r.Estado__c,
        Subalmacen__c,
        UMU__r.Name
      FROM Order__c
      WHERE Id IN :recordIds
    ];

    if (recordsToTransfer.size() > 0) {
      return JSON.serialize(recordsToTransfer);
    }

    throw new AuraHandledException('Error al traer los records');
  }

  @AuraEnabled
  public static String transferOwnership(
    String uniqueCode,
    String newOwnerId,
    String ordenCantidadDeCajasFaltantesJSON
  ) {
    // Query for the TransferInformation record
    List<Informacion_de_Transferencia__c> transferInfo = [
      SELECT Id, Identificadores_de_Ordenes__c, Transferido__c
      FROM Informacion_de_Transferencia__c
      WHERE Codigo_De_Transferencia__c = :uniqueCode
      LIMIT 1
    ];

    // If the records have already been transferred, exit the method
    if (transferInfo.isEmpty()) {
      return 'Las ordenes ya fueron transferidas anteriormente o el codigo no fue generado.';
    }

    List<String> recordIds = new List<String>();
    for (
      String recordId : transferInfo[0].Identificadores_de_Ordenes__c.split(',')
    ) {
      System.debug(recordId);
      recordIds.add(recordId.normalizeSpace());
    }

    // Query for the records to transfer
    List<Order__c> recordsToTransfer = [
      SELECT
        Id,
        OwnerId,
        Estatus__c,
        UMU__c,
        Usuario_ANS__c,
        Order_Number__c,
        Cantidad_de_Cajas_Faltantes_en_la_Orden__c
      FROM Order__c
      WHERE Id IN :recordIds
    ];

    // TODO: Add a database savepoint
    if (!recordsToTransfer.isEmpty()) {
      // Create a method to check if the current user contact is part of the UMU, if the user is not part of that UMU, throw an exception.
      String umu = recordsToTransfer[0].UMU__c;
      Boolean canTransfer = isContactPartOfUmu(newOwnerId, umu);
      if (!canTransfer) {
        throw new AuraHandledException(
          'Error: El usuario no es parte de la UMU.'
        );
      }

      OrderUpdates ordersCajas = (OrderUpdates) JSON.deserialize(
        ordenCantidadDeCajasFaltantesJSON,
        OrderUpdates.class
      );

      for (Order__c record : recordsToTransfer) {
        Integer cantidadDeCajasFaltantes = ordersCajas.orders.get(
          record.Order_Number__c
        );
        record.OwnerId = newOwnerId;
        record.Estatus__c = 'Transferido';
        record.Usuario_ANS__c = newOwnerId;
        // TODO: agregar la cantidad de cajas faltantes en la orden
        // ordenCantidadDeCajasFaltantes es un mapa con el id de la orden y la cantidad de cajas faltantes.
        // Integer cantidadDeCajasFaltantes = ordenCantidadDeCajasFaltantes.get('OrderID');
        // record.Cantidad_de_Cajas_Faltantes_en_la_Orden__c = cantidadDeCajasFaltantes;
        record.Cantidad_de_Cajas_Faltantes_en_la_Orden__c = cantidadDeCajasFaltantes !=
          null
          ? cantidadDeCajasFaltantes
          : 0;
        System.debug(record);
      }

      try {
        update recordsToTransfer;
        delete transferInfo;
        return 'Transferencia exitosa';
      } catch (Exception e) {
        // TODO: Add a database savepoint
        System.debug(e.getMessage());
        system.debug(e.getStackTraceString());
        throw new AuraHandledException('Error: ' + e.getMessage());
      }
    } else {
      throw new AuraHandledException(
        'Error: No se encontraron ordenes para transferir'
      );
    }
  }

  private static Boolean isContactPartOfUmu(String userId, String umuId) {
    // Fetch User with related Contact
    User userRecord = [
      SELECT Id, ContactId
      FROM User
      WHERE Id = :userId
      LIMIT 1
    ];

    // If there is no contact related to the user, return false
    if (userRecord.ContactId == null) {
      return false;
    }

    // Fetch AccountContactRelation records where AccountId is the provided accountId and ContactId is the user's ContactId
    List<AccountContactRelation> acrList = [
      SELECT Id, AccountId, ContactId
      FROM AccountContactRelation
      WHERE AccountId = :umuId AND ContactId = :userRecord.ContactId
    ];

    // If the list is not empty, the contact is associated with the account
    if (!acrList.isEmpty()) {
      return true;
    }

    // Otherwise, return false
    return false;
  }

  @AuraEnabled(cacheable=true)
  public static Boolean doesUserHavePermissionSetWithCustomPermission(
    String userId,
    String permissionSetName,
    String customPermissionName
  ) {
    // Query PermissionSetAssignment to see if the user has the specific permission set assigned
    PermissionSetAssignment psa = [
      SELECT Id, PermissionSetId
      FROM PermissionSetAssignment
      WHERE AssigneeId = :userId AND PermissionSet.Name = :permissionSetName
      LIMIT 1
    ];

    // If there is no PermissionSetAssignment record, return false
    if (psa == null) {
      return false;
    }

    // Query SetupEntityAccess to see if the permission set includes the custom permission
    SetupEntityAccess sea = [
      SELECT Id
      FROM SetupEntityAccess
      WHERE
        ParentId = :psa.PermissionSetId
        AND SetupEntityId IN (
          SELECT Id
          FROM CustomPermission
          WHERE DeveloperName = :customPermissionName
        )
      LIMIT 1
    ];

    // If the SetupEntityAccess record exists, return true; otherwise, return false
    return sea != null;
  }

  public class OrderUpdates {
    // Order number -> Cantidad de cajas
    public Map<String, Integer> orders;
  }
}