unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OrderControllerTest.cls
@isTest
public class OrderControllerTest {

    @TestSetup
    static void setup() {
        // TODO: Create any required records and insert them
        // This could include Products, if required
    }
    
    @isTest
    static void testCreateOrder() {
        Account umuTest = TestDataFactory.createSingleAccount('Hospital UMU');
        Contact contactTest = TestDataFactory.createSingleContactRelatedToAccount(umuTest.Id,'contact Test FirstName', 'contact Test LastName', 'Todas');
        Product2 claveTest = TestDataFactory.createSingleProduct('Aspirina', 'MEDICINE');
        
        OrderController.OrderWrapper testOrderWrapper = new OrderController.OrderWrapper();
        testOrderWrapper.umu = umuTest.Id;
        testOrderWrapper.tipoDePedido = 'Ordinario';
        testOrderWrapper.totalDePiezas = 5;
        testOrderWrapper.status = 'Procesando';
        testOrderWrapper.contactId = contactTest.Id;
        testOrderWrapper.orderItems = new List<OrderController.OrderItemWrapper>();
        
        OrderController.OrderItemWrapper testOrderItem = new OrderController.OrderItemWrapper();
        testOrderItem.productId = claveTest.Id; // TODO: replace with a real product Id
        testOrderItem.cantidadSolicitada = 5;
        testOrderItem.umu = umuTest.Id;
        
        testOrderWrapper.orderItems.add(testOrderItem);

        String jsonData = JSON.serialize(testOrderWrapper);
        
        Test.startTest();
        String result = OrderController.createOrder(jsonData);
        Test.stopTest();
        
        // Assertions to check the result and also to check if an Order__c record got created
        System.assertEquals('Order created successfully!', result);
    }

    @isTest
    static void testRegistrarOrden() {
        Entrega__c delivery = TestDataFactory.createSingleDelivery('Asignado');
        Account acc = TestDataFactory.createSingleAccount('AGUASCALIENTES');
        Contact contact = TestDataFactory.createSingleContactRelatedToAccount(acc.Id, 'Louise', 'Santana', 'Todas');
        Datetime limitDate = Datetime.newInstanceGMT(2023, 6, 30, 0, 0, 0);
        
        Order__c newOrder = new Order__c(
            Fecha_Limite_de_Entrega__c = limitDate,
            Tipo_de_Pedido__c = 'Ordinario',
            Total_de_Piezas__c = 0,
            Estatus__c = 'Procesando',
            Contacto__c = contact.Id,
            UMU__c = acc.Id,
            Entrega__c = delivery.Id
        );

        insert newOrder;

        Test.startTest();
        String result = OrderController.registrarOrden(newOrder.Id, 'En Firma');
        Test.stopTest();
        
        // Assertions to check the result and also to check if the Order__c record got updated
        System.assertEquals('Enviado correctamente.', result);
    }



    @isTest
    static void testRegistrarOrdenParcial() {
        Entrega__c delivery = TestDataFactory.createSingleDelivery('Asignado');
        Account acc = TestDataFactory.createSingleAccount('AGUASCALIENTES');
        Contact contact = TestDataFactory.createSingleContactRelatedToAccount(acc.Id, 'Louise', 'Santana', 'Todas');
        Datetime limitDate = Datetime.newInstanceGMT(2023, 6, 30, 0, 0, 0);
        
        Order__c newOrder = new Order__c(
            Fecha_Limite_de_Entrega__c = limitDate,
            Tipo_de_Pedido__c = 'Ordinario',
            Total_de_Piezas__c = 0,
            Estatus__c = 'Procesando',
            Contacto__c = contact.Id,
            UMU__c = acc.Id,
            Entrega__c = delivery.Id
        );

        insert newOrder;
        
        // create order line item
        
        Order_Line_Item__c orderLineItem = new Order_Line_Item__c(
        	Order__c = newOrder.Id
        );
        
        insert orderLineItem;
        
        // crear lote
        Informacion_De_Lote__c loteTest = new Informacion_De_Lote__c(
            Name = 'LOTE-001',
            Order_Line_Item__c = orderLineItem.Id
        );
        
        insert loteTest;
        

        // Create OrderUpdates test data
        OrderController.OrderUpdates testUpdates = new OrderController.OrderUpdates();
        testUpdates.desviacion = '';
        testUpdates.descripcion = '';
        testUpdates.rejectionImage = '';
        testUpdates.orderItemsUpdates = new List<OrderController.OrderItemUpdate>();
        
        OrderController.OrderItemUpdate testOrderItemUpdate = new OrderController.OrderItemUpdate();
        testOrderItemUpdate.name = '';
        testOrderItemUpdate.id = orderLineItem.Id; // TODO: replace with a real id
        testOrderItemUpdate.lotes = new List<OrderController.Lote>();
        
        OrderController.Lote lote = new OrderController.Lote();
        lote.id = loteTest.Id;
        lote.cantidadDePiezasFaltantes = 2;
        testOrderItemUpdate.lotes.add(lote);
        
        testUpdates.orderItemsUpdates.add(testOrderItemUpdate);

        String ordenParcialJson = JSON.serialize(testUpdates);

        Test.startTest();
        	String result = OrderController.registrarOrdenParcial(newOrder.Id, 'Recibido Parcial', ordenParcialJson);
        Test.stopTest();

        // Assertions to check the result and also to check if the Order__c record got updated
        System.assertEquals('Enviado correctamente.', result);
    }
    
    
    
}