unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/ID_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Viaje__c</fullName>
    <externalId>true</externalId>
    <label>ID de Viaje</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Cantidad_de_Piezas_Recibidas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas_Recibidas__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Guarda la cantidad de piezas recibidas por el auxiliar de farmacia.</description>
    <label>Cantidad de Piezas Faltantes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Numero de Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Maxima_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Maxima_de_Entrega__c</fullName>
    <formula>Pedido__r.Fecha_Limite_de_Entrega__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha Maxima de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/ID_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Pedido__c</fullName>
    <label>ID de Pedido</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Id_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Viaje__c</fullName>
    <formula>Entrega__r.Name</formula>
    <label>Id de Viaje</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/isRecibida__c.field-meta.xml
<CustomField>
    <fullName>isRecibida__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRecibida</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <formula>Cantidad_de_Piezas__c -  Piezas_Faltantes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de Piezas Recibidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Número de Lote</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/BP_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>BP_Product_Code__c</fullName>
    <label>BP Product Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/AnsTransporteController.cls
public with sharing class AnsTransporteController {
  @AuraEnabled(cacheable=true)
  public static List<AccountContactRelation> getUmu(String userId) {
    try {
      List<Id> accId = new List<Id>();
      List<User> activeUser = [
        SELECT ContactId
        FROM User
        WHERE Id = :userId
        WITH SECURITY_ENFORCED
      ];

      Id contactId = activeUser[0].ContactId;
      List<Contact> conList = [
        SELECT AccountId
        FROM Contact
        WHERE id = :contactId
        WITH SECURITY_ENFORCED
      ];

      for (Contact con : conList) {
        accId.add(con.AccountId);
      }

      return [
        SELECT AccountId, Account.Name
        FROM AccountContactRelation
        WHERE ContactId = :contactId
        WITH SECURITY_ENFORCED
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Order__c> getUmuOrders(String umuName, String userId) {
    //Need revision to pass the Entrega Name
    try {
      List<Order__c> ordList = [
        SELECT
          id,
          Fecha_Limite_de_Entrega__c,
          Tipo_de_Pedido__c,
          Total_de_Piezas__c,
          UMU__r.Name,
          Estatus__c,
          Entrega__r.Estado__c,
          Id_de_Viaje__c,
          isRecibida__c
        FROM Order__c
        WHERE
          UMU__r.Name = :umuName
          AND Entrega__r.Estado__c = 'Asignado'
          AND Entrega__r.ownerId = :userId
        WITH SECURITY_ENFORCED
      ];

      return ordList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static List<Order_Line_Item__c> getOrderItems() {
    try {
      List<Order_Line_Item__c> items = new List<Order_Line_Item__c>();
      return items;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Order__c> getOrdersAns(String userId) {
    try {
      List<Order__c> ordList = [
        SELECT
          id,
          Order_Number__c,
          ID_de_Pedido__c,
          Fecha_Maxima_de_Entrega__c,
          Tipo_de_Pedido__c,
          Total_de_Piezas__c,
          UMU__r.Name,
          UMU__r.Estado__c,
          Estatus__c,
          Entrega__r.Estado__c,
          Id_de_Viaje__c,
          isRecibida__c
        FROM Order__c
        WHERE ownerId = :userId // 0053K000002z5leQAA WHERE UMU__r.Name = :umuName AND Entrega__r.Estado__c = 'Asignado'
        WITH SECURITY_ENFORCED
      ];

      return ordList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled
  public static List<Order_Line_Item__c> getProductsOrder(String orderId) {
    try {
      List<Order_Line_Item__c> productList = [
        SELECT
          id,
          Product__c,
          Product__r.Name,
          Product__r.BP_Product_Code__c,
          Product__r.Product_Code_ID__c,
          Numero_de_Lote__c,
          Cantidad_de_Piezas__c,
          (SELECT Id, Name, Cantidad__c, Numero_de_Lote__c, Cantidad_de_Piezas_Recibidas__c FROM Informacion_De_Lotes__r)
        FROM Order_Line_Item__c
        WHERE Order__c = :orderId
        WITH SECURITY_ENFORCED
      ];

      return productList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}