unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Fecha_de_Expiracion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Expiracion__c</fullName>
    <label>Fecha de Expiracion</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Numero de Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Costo_Total__c.field-meta.xml
<CustomField>
    <fullName>Costo_Total__c</fullName>
    <label>Costo Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Costo_Total__c.field-meta.xml
<CustomField>
    <fullName>Costo_Total__c</fullName>
    <label>Costo Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Limite_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_Entrega__c</fullName>
    <label>Fecha Limite de Entrega</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_Maxima_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Maxima_de_Entrega__c</fullName>
    <formula>Pedido__r.Fecha_Limite_de_Entrega__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha Maxima de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <formula>Cantidad_de_Piezas__c -  Piezas_Faltantes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de Piezas Recibidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Entregada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Entregada__c</fullName>
    <label>Cantidad Entregada</label>
    <summarizedField>Informacion_De_Lote__c.Piezas_Recibidas__c</summarizedField>
    <summaryForeignKey>Informacion_De_Lote__c.Order_Line_Item__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Recibida__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Recibida__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad recibida en UMU al momento de recibir la entrega.</description>
    <label>Cantidad Recibida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Costo_Promedio__c.field-meta.xml
<CustomField>
    <fullName>Costo_Promedio__c</fullName>
    <label>Costo Promedio</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Costo_Total__c.field-meta.xml
<CustomField>
    <fullName>Costo_Total__c</fullName>
    <formula>Costo_Promedio__c  *  Cantidad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Costo Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Fecha_de_Expiracion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Expiracion__c</fullName>
    <label>Fecha de Expiración</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Número de Lote</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ReplaneacionController.cls
public without sharing class ReplaneacionController {
    
    public class OrderInformationWrapper {
        public String order_Number { get; set; }
        public String orderId { get; set; }
        public String motivo { get; set; }
        public String orderStatus { get; set; }
        public String IdTransporte { get; set; }
        public String orderUMU { get; set; }
        public String umuId { get; set; }
        public String Ciudad { get; set; }
        public String Estado { get; set; }
        public Datetime FechaEntrega { get; set; }
        public String Evidencia { get; set; }
        public String Comentario { get; set; }
        public TransportistaInfo informacionDeTransportista { get; set; }
    }
    
    public class TransportistaInfo {
        public String IdTransportista { get; set; }
        public String Nombre { get; set; }
        public String Telefono { get; set; }
        public String Email { get; set; }
        public String FotoChecking { get; set; }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Order_Line_Item__c> getOrderProduct(String orderId) {
        try {
            List<Order_Line_Item__c> ordList = [
                SELECT
                Id,
                Product__r.Name,
                Product__r.Product_Code_ID__c,
                Numero_de_Lote__c,
                Cantidad_de_Piezas__c,
                Cantidad_Recibida__c,
                Cantidad__c,
                Costo_Total__c,
                Costo_Promedio__c,
                Cantidad_Solicitada__c, Cantidad_Entregada__c,	
                (SELECT Name, Cantidad__c, Fecha_de_Expiracion__c, Numero_de_Lote__c FROM Informacion_De_Lotes__r)
                FROM Order_Line_Item__c
                WHERE Order__c = :orderId
            ];
            
            return ordList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static String getReplaneacionData(String userId) {  
        try {
            Id contactId = UserContactClass.getContactIdFromUser();
            
            System.debug('contactId---> ' + contactId);
            
            Set<String> umuIds = new Set<String>();
            
            List<AccountContactRelation> umuList = [
                SELECT AccountId, Account.Name
                FROM AccountContactRelation
                WHERE ContactId = :contactId
            ];
            
            System.debug('umuList---> ' + umuList);
            
            for (AccountContactRelation umuRelation : umuList) {
                umuIds.add(umuRelation.AccountId);
            }
            
            System.debug('umuId---> ' + umuIds);
            
            List<Order__c> orderList = [
                SELECT
                id,
                Order_Number__c,
                Fecha_Maxima_de_Entrega__c,
                Fecha_Limite_de_Entrega__c,
                Tipo_de_Pedido__c,
                Total_de_Piezas__c,
                UMU__r.Name,
                UMU__c,
                UMU__r.Estado__c,
                Motivo__c,
                Estatus__c,
                Entrega__r.Estado__c,
                Entrega__r.Name,
                Entrega__c,
                Entrega__r.ID_de_Viaje__c,
                Entrega__r.OwnerId,
                Entrega__r.owner.Name,
                Entrega__r.owner.Email,
                Entrega__r.owner.Phone,
                isRecibida__c,
                Descripcion__c,
                (SELECT Id, ContentDocument.Id FROM ContentDocumentLinks)
                FROM Order__c
                // TODO: Change the status for testing, the encargado de campo solo ve las ordenes Recibidas Parcial
                WHERE
                UMU__r.id IN :umuIds
                AND Entrega__c != NULL
                AND Estatus__c = 'Recibido Parcial'
            ];
            
            List<OrderInformationWrapper> orderInformationWrapperList = new List<OrderInformationWrapper>();
            
            for (Order__c order : orderList) {
                OrderInformationWrapper singleOrderInformation = new OrderInformationWrapper();
                TransportistaInfo singleTransportistaInfo = new TransportistaInfo();
                
                singleOrderInformation.orderId = order.Id;
                singleOrderInformation.order_Number = order.Order_Number__c;
                singleOrderInformation.orderStatus = order?.Estatus__c;
                singleOrderInformation.IdTransporte = order?.Entrega__r.Name;
                singleOrderInformation.orderUMU = order?.UMU__r.Name;
                singleOrderInformation.umuId = order?.UMU__c;
                singleOrderInformation.Comentario = order?.Descripcion__c;
                singleOrderInformation.motivo = order?.Motivo__c;
                singleOrderInformation.Estado = order?.UMU__r.Estado__c;
                singleOrderInformation.FechaEntrega = order?.Fecha_Limite_de_Entrega__c;
                
                if (order.ContentDocumentLinks.size() > 0) {
                    singleOrderInformation.Evidencia = order.ContentDocumentLinks[0]
                        ?.ContentDocument
                        ?.id;
                    System.debug(order.ContentDocumentLinks[0]?.ContentDocument?.id);
                }
                
                singleTransportistaInfo.IdTransportista = order?.Entrega__r.OwnerId;
                singleTransportistaInfo.Nombre = order?.Entrega__r.owner?.Name;
                singleTransportistaInfo.Email = order?.Entrega__r.owner?.Email;
                singleTransportistaInfo.Telefono = order?.Entrega__r.owner?.Phone;
                
                singleOrderInformation.informacionDeTransportista = singleTransportistaInfo;
                System.debug(order);
                System.debug(singleOrderInformation);
                orderInformationWrapperList.add(singleOrderInformation);
            }
            
            // System.debug(orderInformationWrapperList);
            
            return JSON.serialize(orderInformationWrapperList);
        } catch (Exception e) {
            System.debug(e.getStackTraceString());
            System.debug(e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static String firmarOrden(String orderId) {
        try {
            List<Order__c> orders = [
                SELECT Id, Estatus__c
                FROM Order__c
                WHERE Id = :orderId
                LIMIT 1
            ];
            
            if (orders.size() > 0) {
                orders[0].Estatus__c = 'En Firma Parcial';
                update orders;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
        return 'Firmada correctamente';
    }
    
    @AuraEnabled
    public static String editarOrdenParaEnviarAFirma(
        String orderId,
        String ordenParcialJson
    ) {
        OrderController.OrderUpdates orderUpdates = (OrderController.OrderUpdates) JSON.deserialize(
            ordenParcialJson,
            OrderController.OrderUpdates.class
        );
        
        System.debug(orderUpdates);
        
        List<Order__c> orders = [
            SELECT
            Id,
            Estatus__c,
            (
                SELECT
                Id,
                Estatus__c,
                Cantidad_Solicitada__c,
                Cantidad_Recibida__c,
                Cantidad_de_Piezas__c
                FROM Order_Line_Items__r
            )
            FROM Order__c
            WHERE Id = :orderId
            LIMIT 1
        ];
        
        List<Order_Line_Item__c> itemsToUpdate = new List<Order_Line_Item__c>();
        
        try {
            if (orders.size() > 0) {
                for (Order__c orden : orders) {
                    if (orderUpdates.descripcion != '') {
                        orden.Descripcion__c = orderUpdates.descripcion;
                    }
                    
                    if (orderUpdates.desviacion != '') {
                        orden.Motivo__c = orderUpdates.desviacion;
                    }
                    
                    orden.Fecha_De_Entrega__c = orderUpdates.selectedDate;
                    orden.Hora_De_Entrega__c = orderUpdates.selectedTime;
                    
                    Map<String, OrderController.OrderItemUpdate> itemsMap = new Map<String, OrderController.OrderItemUpdate>();
                    for (
                        OrderController.OrderItemUpdate itemUpdate : orderUpdates.orderItemsUpdates
                    ) {
                        itemsMap.put(itemUpdate.id, itemUpdate);
                    }
                    
                    for (Order_Line_Item__c lineItem : orden.Order_Line_Items__r) {
                        OrderController.OrderItemUpdate itemUpdate = itemsMap.get(
                            lineItem.Id
                        );
                        
                        if (itemUpdate != null) {
                            lineItem.Piezas_Faltantes__c = itemUpdate.cantidadDePiezasFaltantes;
                            
                            itemsToUpdate.add(lineItem);
                        }
                    }
                }
                
                update orders;
                
                update itemsToUpdate;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            // TODO: change this for an aura exception
            throw new AuraHandledException(
                'Error al enviar registro: ' + e.getMessage()
            );
        }
        
        return JSON.Serialize(orders);
    }
    
    @AuraEnabled(cacheable=true)
    public static ContentDocumentLink getFiles(String orderId) {
        try {
            ContentDocumentLink datos = [
                SELECT
                Id,
                LinkedEntityId,
                ContentDocumentId,
                ContentDocument.Title,
                ContentDocument.FileType
                FROM ContentDocumentLink
                WHERE
                LinkedEntityId = :orderId
                AND ContentDocument.FileType != 'CSV'
                AND ContentDocument.FileType != 'PDF'
                LIMIT 1
            ];
            
            return datos;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}