unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/Pedido__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pedido Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pedido__c/fields/Autorizado_Por__c.field-meta.xml
<CustomField>
    <fullName>Autorizado_Por__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autorizado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Autorizado Por)</relationshipLabel>
    <relationshipName>Pedidos2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Es_Programa__c.field-meta.xml
<CustomField>
    <fullName>Es_Programa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Programa?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pedido__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PedidoTriggerTest.cls
@isTest
public with sharing class PedidoTriggerTest {

    @TestSetup
	static void createTestData() {
        String uniqueUserName = String.ValueOf(System.Now()).replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);
    }

    @isTest 
    static void testBeforeInsertPedido_Ordinario_Juntos_HR() {
        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Account acc = [SELECT Id, UMU__c FROM Account WHERE Id =: accountIdList[0]];
        acc.UMU__c = 'HR';
        update acc; 

        List<Pedido__c> pedidoList = new List<Pedido__c>();
        for (Integer i = 0; i < 2; i++) {
            Pedido__c pedido = new Pedido__c();
            pedido.UMU__c = acc.Id;  
            pedido.Es_Programa__c = false;
            pedido.Autorizado_Por__c = user.ContactId;
            pedido.Tipo_de_Pedido__c = 'Ordinario';
            pedidoList.add(pedido);
        }
        insert pedidoList;

        Test.startTest();
        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '000001'];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '000001');

        Pedido__c updatedPedido2 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '000002'];
        System.assertEquals(updatedPedido2.ID_de_Pedido__c, '000002');

        Test.stopTest();
    }

    @isTest 
    static void testBeforeInsertPedido_Ordinario_Separados() {
        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Pedido__c pedido1 = new Pedido__c();
        pedido1.UMU__c = accountIdList[0];  
        pedido1.Es_Programa__c = false;
        pedido1.Autorizado_Por__c = user.ContactId;
        pedido1.Tipo_de_Pedido__c = 'Ordinario';
        insert pedido1;

        Pedido__c pedido2 = new Pedido__c();
        pedido2.UMU__c = accountIdList[0];  
        pedido2.Es_Programa__c = false;
        pedido2.Autorizado_Por__c = user.ContactId;
        pedido2.Tipo_de_Pedido__c = 'Ordinario';
        insert pedido2;

        Test.startTest();
        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE Id =: pedido1.Id];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '000001');

        Pedido__c updatedPedido2 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE Id =: pedido2.Id];
        System.assertEquals(updatedPedido2.ID_de_Pedido__c, '000002');

        Test.stopTest();
    }


    @isTest 
    static void testBeforeInsertPedido_Extraordinario_HR() {
        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Account acc = [SELECT Id, UMU__c FROM Account WHERE Id =: accountIdList[0]];
        acc.UMU__c = 'HR';
        update acc; 

        Pedido__c pedido1 = new Pedido__c();
        pedido1.UMU__c = accountIdList[0];  
        pedido1.Es_Programa__c = false;
        pedido1.Autorizado_Por__c = user.ContactId;
        pedido1.Tipo_de_Pedido__c = 'Extraordinario';
        insert pedido1;

        Test.startTest();
        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE Id =: pedido1.Id];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '000001-01');

        Test.stopTest();
    }
    
    @isTest 
    static void testBeforeInsertPedido_Extraordinario_Juntos() {
        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Account acc = [SELECT Id, UMU__c FROM Account WHERE Id =: accountIdList[0]];
        acc.UMU__c = 'HR';
        update acc; 

        List<Pedido__c> pedidoList = new List<Pedido__c>();
        for (Integer i = 0; i < 100; i++) {
            Pedido__c pedido = new Pedido__c();
            pedido.UMU__c = acc.Id;  
            pedido.Es_Programa__c = false;
            pedido.Autorizado_Por__c = user.ContactId;
            pedido.Tipo_de_Pedido__c = 'Extraordinario';
            pedidoList.add(pedido);
        }
        insert pedidoList;

        Test.startTest(); 

        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '000001-01'];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '000001-01');

        Pedido__c updatedPedido2 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '000002-01'];
        System.assertEquals(updatedPedido2.ID_de_Pedido__c, '000002-01');

        Pedido__c updatedPedido99 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '000099-01'];
        System.assertEquals(updatedPedido99.ID_de_Pedido__c, '000099-01');

        Test.stopTest();
    }

    @isTest 
    static void testBeforeInsertPedido_Programa() {
        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];
        
        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Account acc = [SELECT Id, UMU__c FROM Account WHERE Id =: accountIdList[0]];
        acc.UMU__c = 'HR';
        update acc; 

        List<Pedido__c> pedidoList = new List<Pedido__c>();
        for (Integer i = 0; i < 100; i++) {
            Pedido__c pedido = new Pedido__c();
            pedido.UMU__c = acc.Id;  
            pedido.Es_Programa__c = true;
            pedido.Autorizado_Por__c = user.ContactId;
            pedido.Tipo_de_Pedido__c = 'Programa';
            pedidoList.add(pedido);
        }
        insert pedidoList;

        Test.startTest(); 
        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00001-0001'];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '00001-0001');

        Pedido__c updatedPedido2 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00001-0002'];
        System.assertEquals(updatedPedido2.ID_de_Pedido__c, '00001-0002');

        Pedido__c updatedPedido99 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00001-0099'];
        System.assertEquals(updatedPedido99.ID_de_Pedido__c, '00001-0099');
        
        Test.stopTest();
    }

    @isTest 
    static void testBeforeInsertPedido_Programa_Doble_Insercion() {

        Test.startTest(); 

        User user = [SELECT Id, ContactId FROM User WHERE Alias = 'testUser' LIMIT 1];

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        Account acc = [SELECT Id, UMU__c FROM Account WHERE Id =: accountIdList[0]];
        acc.UMU__c = 'HR';
        update acc; 

        List<Pedido__c> pedidoList = new List<Pedido__c>();
        for (Integer i = 0; i < 99; i++) {
            Pedido__c pedido = new Pedido__c();
            pedido.UMU__c = acc.Id;  
            pedido.Es_Programa__c = true;
            pedido.Autorizado_Por__c = user.ContactId;
            pedido.Tipo_de_Pedido__c = 'Programa';
            pedidoList.add(pedido);
        }
        insert pedidoList;

        Pedido__c pedido2 = new Pedido__c();
        pedido2.UMU__c = acc.Id;  
        pedido2.Es_Programa__c = true;
        pedido2.Autorizado_Por__c = user.ContactId;
        pedido2.Tipo_de_Pedido__c = 'Urgencia Médica';
        insert pedido2;

        List<Pedido__c> pedidoList3 = new List<Pedido__c>();
        for (Integer i = 0; i < 99; i++) {
            Pedido__c pedido = new Pedido__c();
            pedido.UMU__c = acc.Id;  
            pedido.Es_Programa__c = true;
            pedido.Autorizado_Por__c = user.ContactId;
            pedido.Tipo_de_Pedido__c = 'Programa';
            pedidoList3.add(pedido);
        }
        insert pedidoList3;

        

        Pedido__c updatedPedido1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00001-0001'];
        System.assertEquals(updatedPedido1.ID_de_Pedido__c, '00001-0001');

        Pedido__c updatedPedido99 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00001-0099'];
        System.assertEquals(updatedPedido99.ID_de_Pedido__c, '00001-0099');

        Pedido__c updatedPedido2 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c LIKE: '00002-0001'];
        System.assertEquals(updatedPedido2.ID_de_Pedido__c, '00002-0001');

       Pedido__c updatedPedido3_1 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00003-0001'];
        System.assertEquals(updatedPedido3_1.ID_de_Pedido__c, '00003-0001');

        Pedido__c updatedPedido3_99 = [SELECT Id, ID_de_Pedido__c FROM Pedido__c WHERE ID_de_Pedido__c = '00003-0099'];
        System.assertEquals(updatedPedido3_99.ID_de_Pedido__c, '00003-0099');

        Test.stopTest();
    }

}