unpackaged/main/default/objects/Account/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <externalId>true</externalId>
    <label>UMU</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <description>Medicamento/Material de Curación.</description>
    <formula>TEXT(Producto__r.Simple_Classification__c)</formula>
    <label>Clasificación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Estatus_de_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Estatus_de_Conteo__c</fullName>
    <description>Estatus del conteo del día.</description>
    <label>Estatus de Conteo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <description>Tipo de Insumo para inventarios. Ordinario, Programa, Vacunas, Compra local.</description>
    <formula>TEXT( Producto__r.Programa__r.Inventario__c )</formula>
    <label>Tipo de Insumo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Estatus del inventario.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registrado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Firmado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fecha_Registrado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Registrado__c</fullName>
    <description>Fecha y hora en que se registró el conteo de inventario por el ANS.</description>
    <label>Fecha Registrado</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Compra Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>UMU en la cual se realiza el registro de inventario.</description>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventarios</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Actual__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Actual__c</fullName>
    <description>Cantidad actual contada en el lote.</description>
    <label>Conteo Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Anterior__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Anterior__c</fullName>
    <description>Cantidad previa contada en el lote.</description>
    <label>Conteo Anterior</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Estatus_Conteo_Lote__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Conteo_Lote__c</fullName>
    <label>Estatus Conteo Lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Caducidad__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Caducidad__c</fullName>
    <description>Fecha de caducidad del insumo en el lote.</description>
    <label>Fecha de Caducidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <description>Texto que identifica al lote.</description>
    <label>Lote</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/LoteInventarioFieldsTest.cls
@isTest
public with sharing class LoteInventarioFieldsTest {
    
    @TestSetup
    static void createTestData() {
        String uniqueUserName = String.ValueOf(System.Now()).replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);

        List<Id> accountIdList = new List<Id>(); 

        for(AccountContactRelation accConRel : [ SELECT AccountId, Account.Name FROM AccountContactRelation WHERE ContactId =: user.ContactId LIMIT 1]){
            accountIdList.add(accConRel.AccountId);
        }

        List<Product2> listproduct = TestDataFactory.createMultipleProduct2('Producto', 2);

        Inventario__c inventario = new Inventario__c(); 
        inventario.Clasificacion__c = 'Material de Curación';
        inventario.Tipo_de_Insumo__c = 'Ordinario';
        inventario.UMU__c = accountIdList[0]; 
        insert inventario;

        Clave_de_Inventario__c cveInventario = new Clave_de_Inventario__c(); 
        cveInventario.Producto__c = listproduct[0].Id;
        cveInventario.Inventario__c = inventario.Id; 
        insert cveInventario;

        Clave_de_Inventario__c cveInventario2 = new Clave_de_Inventario__c(); 
        cveInventario2.Producto__c = listproduct[1].Id;
        cveInventario2.Inventario__c = inventario.Id; 
        insert cveInventario2;

        Lote_de_Inventario__c loteInventario = new Lote_de_Inventario__c(); 
        loteInventario.Conteo_Actual__c = 0;
        loteInventario.Conteo_Anterior__c = 0;
        loteInventario.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInventario.Lote__c = 'LOTE01';
        loteInventario.Clave_de_Inventario__c = cveInventario.Id; 
        insert loteInventario;

        Lote_de_Inventario__c loteInventario2 = new Lote_de_Inventario__c(); 
        loteInventario2.Conteo_Actual__c = 0;
        loteInventario2.Conteo_Anterior__c = 0;
        loteInventario2.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInventario2.Lote__c = 'LOTE02';
        loteInventario2.Clave_de_Inventario__c = cveInventario.Id; 
        insert loteInventario2;

        Lote_de_Inventario__c loteInventario3 = new Lote_de_Inventario__c(); 
        loteInventario3.Conteo_Actual__c = 0;
        loteInventario3.Conteo_Anterior__c = 0;
        loteInventario3.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInventario3.Lote__c = 'LOTE01';
        loteInventario3.Clave_de_Inventario__c = cveInventario2.Id; 
        insert loteInventario3;

        Inventario__c invEnFirma = new Inventario__c(); 
        invEnFirma.Clasificacion__c = 'Material de Curación';
        invEnFirma.Tipo_de_Insumo__c = 'Compra Local';
        invEnFirma.UMU__c = accountIdList[0]; 
        invEnFirma.Fecha_Registrado__c = System.Now() - 1;
        invEnFirma.Estatus__c = null;
        insert invEnFirma;

        Clave_de_Inventario__c cveInvFirma = new Clave_de_Inventario__c(); 
        cveInvFirma.Producto__c = listproduct[0].Id;
        cveInvFirma.Inventario__c = invEnFirma.Id; 
        insert cveInvFirma;

        Lote_de_Inventario__c loteInvFirma = new Lote_de_Inventario__c(); 
        loteInvFirma.Conteo_Actual__c = 0;
        loteInvFirma.Conteo_Anterior__c = 0;
        loteInvFirma.Fecha_de_Caducidad__c = System.Today() + 5;
        loteInvFirma.Lote__c = 'LOTE01';
        loteInvFirma.Clave_de_Inventario__c = cveInvFirma.Id; 
        insert loteInvFirma;

        loteInvFirma.Estatus_Conteo_Lote__c = 'Contado';
        update loteInvFirma;

        cveInvFirma.Estatus_de_Conteo__c = 'Contado';
        update cveInvFirma;

        invEnFirma.Estatus__c = 'En Firma';
        update invEnFirma;
    }

    @IsTest
    static void testConteoLoteInicial() {

        List<Lote_de_Inventario__c> loteInvUpd = New List<Lote_de_Inventario__c>();
        List<Clave_de_Inventario__c > cveInvList = [SELECT Id, Inventario__c 
                                                    FROM Clave_de_Inventario__c 
                                                    LIMIT 1];

        List<Lote_de_Inventario__c> loteList = [SELECT Conteo_Actual__c, Clave_de_Inventario__c, Conteo_Anterior__c, Fecha_de_Caducidad__c, Lote__c, Estatus_Conteo_Lote__c
                                                FROM Lote_de_Inventario__c 
                                                WHERE Clave_de_Inventario__c = :cveInvList[0].Id];
                    
        for(Lote_de_Inventario__c lote : loteList ){
            lote.Conteo_Actual__c = 10;
            lote.Conteo_Anterior__c = 5;
            lote.Estatus_Conteo_Lote__c = 'Contado';
            loteInvUpd.add(lote);
        }
        Test.startTest();
            update loteInvUpd;
        Test.stopTest();

        Id claveInventario;
        for(Lote_de_Inventario__c lot : loteInvUpd ){
            claveInventario = lot.Clave_de_Inventario__c;
            break;
        }

        System.assertEquals('Iniciado', [SELECT Estatus_de_Conteo__c FROM Clave_de_Inventario__c WHERE Id = : claveInventario].Estatus_de_Conteo__c, 'Estatus de Clave de Inventario diferente a Iniciado');
    }

    @IsTest
    static void testConteoLoteInvEnFirma() {

        List<Lote_de_Inventario__c> loteInvUpdList = New List<Lote_de_Inventario__c>();
        List<Inventario__c> invUpdList = New List<Inventario__c>();

        List<Clave_de_Inventario__c > cveInvList = [SELECT Id, Inventario__c FROM Clave_de_Inventario__c WHERE Inventario__r.Tipo_de_Insumo__c = 'Compra Local' LIMIT 1];

        
        List<Lote_de_Inventario__c> loteList = [SELECT Conteo_Actual__c, Conteo_Anterior__c, Fecha_de_Caducidad__c, Lote__c, Estatus_Conteo_Lote__c
                                                FROM Lote_de_Inventario__c 
                                                WHERE Clave_de_Inventario__c = :cveInvList[0].Id];
                    
        for(Lote_de_Inventario__c lote : loteList ){
            lote.Conteo_Actual__c = 8;
            lote.Conteo_Anterior__c = 8;
            lote.Estatus_Conteo_Lote__c = 'Contado';
            loteInvUpdList.add(lote);
        }
        Test.startTest();
            try {
                update loteInvUpdList;
            } catch (Exception e){
                System.debug('Update Error Message: ' + e.getMessage());
            }
            try {
                delete loteInvUpdList;
            } catch (Exception e){
                System.debug('Delete Error Message: ' + e.getMessage());
            }
        Test.stopTest();

        //System.debug('loteList.Size: ' + loteList.Size());
        System.assertEquals(loteInvUpdList.Size(), [SELECT Count() 
                                                    FROM Lote_de_Inventario__c 
                                                    WHERE Clave_de_Inventario__c = :cveInvList[0].Id], 'Se elimino el lote de un inventario En Firma');
    
    }
}