unpackaged/main/default/objects/Product2/fields/BP_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>BP_Product_Code__c</fullName>
    <label>BP Product Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Enable__c.field-meta.xml
<CustomField>
    <fullName>Enable__c</fullName>
    <label>Enable</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Fraction__c.field-meta.xml
<CustomField>
    <fullName>Fraction__c</fullName>
    <label>Fraction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Controlado 1</fullName>
            </value>
            <value>
                <fullName>Controlado 2</fullName>
            </value>
            <value>
                <fullName>Controlado 3</fullName>
            </value>
            <value>
                <fullName>No Controlado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Package_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Package_Capacity__c</fullName>
    <label>Package Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Partida_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Partida_Presupuestal__c</fullName>
    <label>Partida Presupuestal</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>Programas__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Sicora_Classification__c.field-meta.xml
<CustomField>
    <fullName>Sicora_Classification__c</fullName>
    <label>Sicora Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REGULAR</fullName>
            </value>
            <value>
                <fullName>HIGH VALUE</fullName>
            </value>
            <value>
                <fullName>HIGH_VALUE</fullName>
                <isActive>false</isActive>
                <label>HIGH_VALUE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Simple_Classification__c.field-meta.xml
<CustomField>
    <fullName>Simple_Classification__c</fullName>
    <label>Simple Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MEDICINE</fullName>
            </value>
            <value>
                <fullName>HEALING MATERIAL</fullName>
            </value>
            <value>
                <fullName>HEALING_MATERIAL</fullName>
                <isActive>false</isActive>
                <label>HEALING_MATERIAL</label>
            </value>
            <value>
                <fullName>HIGH VALUE</fullName>
                <isActive>false</isActive>
                <label>HIGH VALUE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Subalmacen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subalmacen</label>
    <referenceTo>Subalmacen__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Programas__c/Programas__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Programas__c/fields/Programa_ID__c.field-meta.xml
<CustomField>
    <fullName>Programa_ID__c</fullName>
    <label>Programa ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Subalmacen__c/Subalmacen__c.object-meta.xml
<CustomObject>
    <description>Almacén que maneja un Stock propio de la Dependencia a la cual está inscrito.</description>
    <label>Subalmacen</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subalmacenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SuppliesController.cls
public without sharing class SuppliesController {
    @AuraEnabled(cacheable=true)
    public static List<Product2> getSupplies(){
        List<Product2> suppliesList = new List<Product2>();
        List<Id> programsIdList = new List<Id>();
        try {
            suppliesList = [SELECT Id, Product_Code_ID__c, Name, Partida_Presupuestal__c, 
                            BP_Product_Code__c, Programa__c, Sicora_Classification__c, 
                            Simple_Classification__c, Subalmacen__c, Package_Capacity__c,
                            Description__c, Fraction__c, Enable__c
                            FROM Product2 
                            WHERE Programa__c IN :programsIdList
                            LIMIT 50];
            return suppliesList;
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Product2 getSuppliesByCode(String productCode){
        try {
            return [SELECT Id, Product_Code_ID__c, Name, Partida_Presupuestal__c,
                            BP_Product_Code__c, Programa__c, Sicora_Classification__c,
                            Simple_Classification__c, Subalmacen__c, Package_Capacity__c,
                            Description__c, Fraction__c, Enable__c
                            FROM Product2
                            WHERE Product_Code_ID__c = :productCode
                            LIMIT 1];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getSuppliesBySearch(String search, String programId) {

        List<Product2> suppliesList = new List<Product2>();
        String searchTerm = '%' + String.escapeSingleQuotes(search.trim()) + '%';

        try {
            suppliesList = [SELECT Id, Product_Code_ID__c, Name, Partida_Presupuestal__c,
                            BP_Product_Code__c, Programa__c, Sicora_Classification__c,
                            Simple_Classification__c, Subalmacen__c, Package_Capacity__c,
                            Description__c, Fraction__c, Enable__c
                            FROM Product2
                            WHERE Programa__c = :programId
                            AND (Name LIKE :searchTerm
                            OR Product_Code_ID__c LIKE :searchTerm)];
            return suppliesList;
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Product2> getSuppliesByProgram(String programId) {

        List<Product2> suppliesList = new List<Product2>();
        try {
            suppliesList = [SELECT Id, Product_Code_ID__c, Name, Partida_Presupuestal__c,
                            BP_Product_Code__c, Programa__r.Programa_ID__c, Sicora_Classification__c,
                            Simple_Classification__c, Subalmacen__c, Package_Capacity__c,
                            Description__c, Fraction__c, Enable__c
                            FROM Product2
                            WHERE Programa__r.Programa_ID__c = :programId];
            return suppliesList;
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class ProductsWrapper {
        public Integer pageSize {get;set;}
        public Integer pageNumber {get;set;}
        public Integer totalRecords {get;set;}
        public Integer recordStart {get;set;}
        public Integer recordEnd {get;set;}
        public List<Product2> products {get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static String getSuppliesBySearch2(String search, String programId, Integer pageSize, Integer pageNumber) {
        String suppliesList = '';
        String searchTerm = '%' + String.escapeSingleQuotes(search.trim()) + '%';
                                                        
        //Offset for SOQL
        Integer offset = (pageNumber - 1) * pageSize;
         
        //Total Records
        Integer totalRecords = [SELECT COUNT() FROM Product2
                            	WHERE Programa__c = :programId];
        Integer recordEnd = pageSize * pageNumber;
                                                        
        ProductsWrapper objDT =  new ProductsWrapper();  
        objDT.pageSize = pageSize;
        objDT.pageNumber = pageNumber;
        objDT.recordStart = offset + 1;
        objDT.recordEnd = totalRecords >= recordEnd ? recordEnd : totalRecords;
        objDT.totalRecords = totalRecords;
        objDT.products = [SELECT Id, Product_Code_ID__c, Name, Partida_Presupuestal__c,
                          BP_Product_Code__c, Programa__c, Sicora_Classification__c,
                          Simple_Classification__c, Subalmacen__c, Package_Capacity__c,
                          Description__c, Fraction__c, Enable__c
                          FROM Product2
                          WHERE Programa__c = :programId
                          AND (Name LIKE :searchTerm
                          OR Product_Code_ID__c LIKE :searchTerm)
                          LIMIT :pageSize OFFSET :offset];
        suppliesList = JSON.serialize(objDT);                       
        try {
            return suppliesList;
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
}