unpackaged/main/default/objects/Account/recordTypes/UMU.recordType-meta.xml
<RecordType>
    <fullName>UMU</fullName>
    <active>true</active>
    <label>UMU</label>
</RecordType>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs (UMU)</relationshipLabel>
    <relationshipName>DPNs1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Historico</fullName>
            </value>
            <value>
                <fullName>No Ordinario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Consumido__c.field-meta.xml
<CustomField>
    <fullName>Consumido__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Consumido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Fraction__c.field-meta.xml
<CustomField>
    <fullName>Fraction__c</fullName>
    <label>Fraction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Controlado 1</fullName>
            </value>
            <value>
                <fullName>Controlado 2</fullName>
            </value>
            <value>
                <fullName>Controlado 3</fullName>
            </value>
            <value>
                <fullName>No Controlado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Simple_Classification__c.field-meta.xml
<CustomField>
    <fullName>Simple_Classification__c</fullName>
    <label>Simple Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MEDICINE</fullName>
            </value>
            <value>
                <fullName>HEALING MATERIAL</fullName>
            </value>
            <value>
                <fullName>HEALING_MATERIAL</fullName>
                <isActive>false</isActive>
                <label>HEALING_MATERIAL</label>
            </value>
            <value>
                <fullName>HIGH VALUE</fullName>
                <isActive>false</isActive>
                <label>HIGH VALUE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestBatchDPNLineItemProcessor.cls
@isTest
private class TestBatchDPNLineItemProcessor{

	@testSetup static void setup(){

        Account acc = TestDataFactory.createSingleAccount(
            'Test UMU - UserContactClassTest'
        );
        
        Contact con = TestDataFactory.createSingleContactRelatedToAccount(
            acc.Id,
            'Test',
            'UserContactClassTest',
            'Medicina'
        );
        
        String uniqueUserName = String.ValueOf(System.Now())
            .replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);
        
        Product2 clave = new Product2();
        clave.Name = 'Medicamento de Prueba';
        clave.Simple_Classification__c = 'MEDICINE';
        clave.Fraction__c = 'Controlado 1';
        insert clave;
        
        DPN__c dpn = new DPN__c();
        dpn.Account__c = acc.Id;
        dpn.Estatus__c = 'Activo';
        insert dpn;
        
        DPN_Line_Item__c dpnLineItem = new DPN_Line_Item__c();
        dpnLineItem.DPN__c = dpn.Id;
        dpnLineItem.Product__c = clave.Id;
        dpnLineItem.Consumido__c = 1.1;
        insert dpnLineItem;
		 
	}

	@isTest static void testMethod1() {
		Test.startTest();
        BatchDPNLineItemProcessor ba= new BatchDPNLineItemProcessor();
        Id jobid= Database.executeBatch(ba,5);
        Test.stopTest();
	}
}