unpackaged/main/default/objects/Contactos_y_Programas__c/Contactos_y_Programas__c.object-meta.xml
<CustomObject>
    <label>Contactos y Programas</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contactos y Programas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos y Programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contactos_y_Programas__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos y Programas</relationshipLabel>
    <relationshipName>Contactos_y_Programas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contactos_y_Programas__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programas__c</referenceTo>
    <relationshipLabel>Contactos y Programas</relationshipLabel>
    <relationshipName>Contactos_y_Programas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ContactsProgramsTriggerTest.cls
@isTest
public class ContactsProgramsTriggerTest {
	@isTest
    public static void testBeforeInsertTrigger() {
        List<Contactos_y_Programas__c> cpList = TestDataFactory.createMultipleContactsAndPrograms(3);
        
        Test.startTest();
        Database.SaveResult[] result = Database.insert(cpList);
        System.assertEquals(3, result.size(), 'SaveResult list size must be 3');
        
        Contactos_y_Programas__c cp = [
            SELECT Id, Contact__c, Programa__c
            FROM Contactos_y_Programas__c LIMIT 1
        ];
        
        Contactos_y_Programas__c conProg = new Contactos_y_Programas__c(
            Contact__c = cp.Contact__c,
            Programa__c = cp.Programa__c
        );
        
        try {
            Database.SaveResult resultInvalid = Database.insert(conProg);
            System.assertEquals(false, resultInvalid.isSuccess(), 'SaveResult was no success');
        } catch (Exception e) {
            system.debug(e.getMessage());
        }
        
        Test.stopTest();
    }
}