unpackaged/main/default/objects/Contactos_y_Programas__c/Contactos_y_Programas__c.object-meta.xml
<CustomObject>
    <label>Contactos y Programas</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contactos y Programas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos y Programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contactos_y_Programas__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contactos y Programas</relationshipLabel>
    <relationshipName>Contactos_y_Programas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contactos_y_Programas__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <referenceTo>Programas__c</referenceTo>
    <relationshipLabel>Contactos y Programas</relationshipLabel>
    <relationshipName>Contactos_y_Programas</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Programas__c/Programas__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ContactsProgramsFields.cls
public with sharing class ContactsProgramsFields {
    public static void insertRecords(List<Contactos_y_Programas__c> newContactsProgramsList) {
        if(Trigger.isInsert){
            Map<String, Contactos_y_Programas__c> contactProgMap = New Map<String, Contactos_y_Programas__c>();
            
            for (List<Contactos_y_Programas__c> cpl : [SELECT Id, Contact__c, Contact__r.Name, Programa__c, Programa__r.Name
                                                       FROM Contactos_y_Programas__c]){
                for(Contactos_y_Programas__c cp : cpl)  {
                    contactProgMap.put(cp.Contact__c+''+cp.Programa__c, cp);
                }
            }

            for(Contactos_y_Programas__c contactProg : newContactsProgramsList) {
                if(contactProgMap.containsKey(contactProg.Contact__c+''+contactProg.Programa__c)){
                    Contactos_y_Programas__c existingCP = contactProgMap.get(contactProg.Contact__c+''+contactProg.Programa__c);
                    String errorMessage = 'El contacto ' + existingCP.Contact__r.Name + ' ya tiene asociado el programa ' + existingCP.Programa__r.Name;
                    contactProg.addError(errorMessage);
                }
            }
        }
    }
}