unpackaged/main/default/objects/Contactos_y_Programas__c/Contactos_y_Programas__c.object-meta.xml
<CustomObject>
    <label>Contactos y Programas</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contactos y Programas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contactos y Programas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Historico</fullName>
            </value>
            <value>
                <fullName>No Ordinario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Asignado</fullName>
                <default>true</default>
                <label>No Asignado</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Seguimiento__c.field-meta.xml
<CustomField>
    <fullName>Seguimiento__c</fullName>
    <label>Seguimiento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Programas__c/Programas__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TestAnsTransporteController.cls
@isTest
private class TestAnsTransporteController {
    @testSetup static void setup(){
        Account acc = TestDataFactory.createSingleAccount('Test');
        
        Contact con = TestDataFactory.createSingleContactRelatedToAccount(
            acc.Id,
            'Test',
            'UserContactClassTest',
            'Medicina'
        );
        
        Product2 product =  TestDataFactory.createSingleProduct2('test');
        
        List<Product2> listproduct = TestDataFactory.createMultipleProduct2('test2',5);
        
        Order__c ord = TestDataFactory.createSingleOrder();
        
        DPN__c dpn = TestDataFactory.createSingleDPN(acc.Id);
        
        DPN_Line_Item__c dpnLineItem = TestDataFactory.createSingleDPNLineItem(dpn.Id, product.Id); 
        
        Entrega__c entrega = TestDataFactory.createSingleDelivery('No Asignado');
        
        List<Contactos_y_Programas__c> listcontactosProgramas = TestDataFactory.createMultipleContactsAndPrograms(3);
    }
    
    @isTest static void testMethod1() {
        Test.startTest();
        Account account = [SELECT Id FROM Account LIMIT 1];
        User testUser = [SELECT Id FROM User LIMIT 1];
        Order__c order = [SELECT Id,Estatus__c,Seguimiento__c FROM Order__c LIMIT 1];
        System.runAs(testUser) {
            List<AccountContactRelation> listAccountRelation = AnsTransporteController.getUmu(testUser.Id);
            List<Order__c> listOrders = AnsTransporteController.getUmuOrders('test', testUser.Id);
            List<Order_Line_Item__c> listOrderLineItems = AnsTransporteController.getOrderItems();
            List<Order__c> listOrderAns = AnsTransporteController.getOrdersAns(testUser.Id);
            List<Order_Line_Item__c> listProducts = AnsTransporteController.getProductsOrder(testUser.Id);
            List<DPN_Line_Item__c> listorderItem = VerDpnPedidoController.getDpn(account.Id);
            List<Contactos_y_Programas__c> listcontactosProgramas = TestDataFactory.createMultipleContactsAndPrograms(3);
            insert listcontactosProgramas;
            
            insert listOrders;
            insert listOrderLineItems;
        }
        Test.stopTest();
    }
   @isTest static void testMethod2() {
        Test.startTest();
       
        
        User testUser = [SELECT Id, Username FROM User LIMIT 1];
       	Entrega__c entrega = [SELECT Id, Name, Estado__c FROM Entrega__c LIMIT 1];
       
        System.runAs(testUser) {
            List<Object> listEntregas = AsignadoTransporteController.getEntregas(entrega.Name);
            AsignadoTransporteController.updateEntregaAsignar(entrega.Name, testUser.Id);
            AsignadoTransporteController.desasignarEntrega(entrega.Id);
            AsignadoTransporteController.finalizarEntrega(entrega.Id);
            List<Object> listaentrega = EntreAsignadaController.getEntregasAsignadas(testUser.Id);
        }
        Test.stopTest();
    }
    
    @isTest static void testMethod3() {
        Test.startTest();
        User testUser = [SELECT Id, Username FROM User LIMIT 1];
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'CustomerPortal' Limit 1];
        User usr = [Select Id,UserRoleId, Username from User where UserRoleId=:portalRole.Id LIMIT 1];
        Order__c order = [SELECT Id,Estatus__c,Seguimiento__c FROM Order__c LIMIT 1];
        System.RunAs(usr) {
            CustomForgotFormController.forgotPassowrd(usr.Username);
            LightningLoginFormController.getForgotPasswordUrl();
            LightningLoginFormController.setExperienceId('test');
            LightningLoginFormController.getIsSelfRegistrationEnabled();
            LightningLoginFormController.getSelfRegistrationUrl();
            LightningLoginFormController.getIsUsernamePasswordEnabled();
            LightningLoginFormController.login('username','password','test');
            LightningForgotPasswordController.setExperienceId('test');
            LightningForgotPasswordController.forgotPassword('test','test');
        }
        Test.stopTest();
    }
    
   @isTest static void testMethod4() {
        Test.startTest();
        User testUser = [SELECT Id, Username FROM User LIMIT 1];
       	Product2 productSingle = [SELECT Id, productCode FROM Product2 LIMIT 1];
        System.RunAs(testUser) {
            List<Product2> listaproductos = SuppliesController.getSupplies();
            //Product2 product = SuppliesController.getSuppliesByCode(productSingle.productCode);
            Programas__c program = [SELECT Id FROM Programas__c LIMIT 1];
            List<Product2> listaproductosbysearch = SuppliesController.getSuppliesBySearch('test', program.Id);
            List<Product2> listaproductosbyprogram = SuppliesController.getSuppliesByProgram(program.Id);
            String testtext =  SuppliesController.getSuppliesBySearch2('test', program.Id, 5, 5);
        }
        Test.stopTest();
    }
    @isTest static void testMethod5() {
        Test.startTest();
        User testUser = [SELECT Id, Username FROM User LIMIT 1];
       	Order__c order = [SELECT Id,Tipo_de_Pedido__c FROM Order__c LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        System.RunAs(testUser) {
            List<Order_Line_Item__c> listOrderItems = ReplaneacionController.getOrderProduct(order.Id);
            String replaData = ReplaneacionController.getReplaneacionData(testUser.Id);
            String firma = ReplaneacionController.firmarOrden(order.Id);
			List<ContentVersion> listaContent  = new List<ContentVersion>();        
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
             
            listaContent.add(contentVersion);
            insert contentVersion; 
            List<ContentDocument> documents = [
                SELECT Id, Title, LatestPublishedVersionId 
                FROM ContentDocument
            ];
            
            List<ContentDocumentLink> contentDoclist = new List<ContentDocumentLink>();
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = order.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            
            contentDoclist.add(cdl);
            
            insert cdl;
            
            ContentDocumentLink contentl = ReplaneacionController.getFiles(order.Id);
            
            String test = ImageUploadController.saveImage('Test', 'test', order.Id, false);
            List<DocumentWrapper> listDocuments = RelatedRecordAttachmentsController.getAllDocumentsAndRelatedFiles();
            ContentDistribution contentDist = RelatedRecordAttachmentsController.getContentDistributionForFile(cdl.ContentDocumentId);
        }
        Test.stopTest();
    }
}