unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <description>Medicamento/Material de Curación.</description>
    <formula>TEXT(Producto__r.Simple_Classification__c)</formula>
    <label>Clasificación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Codigo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto__c</fullName>
    <formula>Producto__r.Product_Code_ID__c</formula>
    <label>Codigo de Producto</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Estatus_de_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Estatus_de_Conteo__c</fullName>
    <description>Estatus del conteo del día.</description>
    <label>Estatus de Conteo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Fecha_Inicio_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Conteo__c</fullName>
    <description>Fecha en que inicia el conteo del día.</description>
    <label>Fecha Inicio Conteo</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Nombre_UMU__c.field-meta.xml
<CustomField>
    <fullName>Nombre_UMU__c</fullName>
    <description>Nombre de la UMU almacenado en objeto relacionado Inventario</description>
    <formula>Inventario__r.Nombre_UMU__c</formula>
    <label>Nombre UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <description>Tipo de Insumo para inventarios. Ordinario, Programa, Vacunas, Compra local.</description>
    <formula>TEXT( Producto__r.Programa__r.Inventario__c )</formula>
    <label>Tipo de Insumo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <description>Clave Presupuestal almacenada en objeto Cuenta.</description>
    <formula>UMU__r.Clave_Presupuestal__c</formula>
    <label>Clave Presupuestal</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Codigo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Codigo_UMU__c</fullName>
    <description>Código de identificación de la Unidad Médica.</description>
    <formula>UMU__r.UMU__c</formula>
    <label>Código UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <description>Delegación de la UMU relacionada. Utilizado para mostrar su valor en InventarioPDF</description>
    <formula>UMU__r.Delegacion__c</formula>
    <label>Delegación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Estatus del inventario.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registrado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Firmado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fecha_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio__c</fullName>
    <description>Fecha en que inicia el conteo de claves de inventario.</description>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fecha_Registrado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Registrado__c</fullName>
    <description>Fecha y hora en que se registró el conteo de inventario por el ANS.</description>
    <label>Fecha Registrado</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Firmado_Por__c.field-meta.xml
<CustomField>
    <fullName>Firmado_Por__c</fullName>
    <description>Nombre del usuario que firma el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a Firmado.</description>
    <label>Firmado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Nombre_UMU__c.field-meta.xml
<CustomField>
    <fullName>Nombre_UMU__c</fullName>
    <description>Campo de ayuda para usar en la Plantilla de Email: Inventario En Firma.</description>
    <formula>UMU__r.Name</formula>
    <label>Nombre UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Numero_de_Insumos__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Insumos__c</fullName>
    <description>Numero total de claves de inventario.</description>
    <label>Numero de Insumos</label>
    <summaryForeignKey>Clave_de_Inventario__c.Inventario__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Registrado_Por__c.field-meta.xml
<CustomField>
    <fullName>Registrado_Por__c</fullName>
    <description>Nombre del usuario que registra el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a En Firma.</description>
    <label>Registrado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Registrado_Por_Email__c.field-meta.xml
<CustomField>
    <fullName>Registrado_Por_Email__c</fullName>
    <description>Email del usuario que pone el inventario En Firma. (ANS). Se utiliza para el envío de la notificación.</description>
    <label>Registrado Por Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <description>Día en que fue firmado el registro del inventario por el jefe de almacén.</description>
    <label>Fecha De Firma</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Compra Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Actual__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Actual__c</fullName>
    <description>Cantidad actual contada en el lote.</description>
    <label>Conteo Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Caducidad__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Caducidad__c</fullName>
    <description>Fecha de caducidad del insumo en el lote.</description>
    <label>Fecha de Caducidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <description>Texto que identifica al lote.</description>
    <label>Lote</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/InventarioFields.cls
public with sharing class InventarioFields {

    public static void updateInventarioFirmado( List<Inventario__c> invList, Map<Id, Inventario__c> oldInvMap ){
        for( Inventario__c inv : invList ){
            System.debug('inv.Estatus__c inv- ' + inv.Estatus__c);
            System.debug('oldInvMap inv- ' + oldInvMap.get(inv.Id).Estatus__c);
            if( inv.Estatus__c == 'Firmado' && oldInvMap.get(inv.Id).Estatus__c == 'En Firma' ){
                inv.Firmado_por__c = UserInfo.getName();
                inv.Signed_Date__c = System.Now();
            }
            System.debug('updateInventarioFirmado inv- ' + inv);
        }
    }

    public static void updateEstatusInventario( List<Inventario__c> invList, Map<Id, Inventario__c> oldInvMap ){
        
        Set<Id> invIdSet = New Set<Id>();
        Map<Id, Date> invFechaMap = New Map<Id, Date>();
        Map<Id, Inventario__c> invToClaveInvMap = New Map<Id, Inventario__c>(); 
        Map<Id, Decimal> invNumCvesMap = New Map<Id, Decimal>();
        List<Clave_de_Inventario__c> cveInvList = New List<Clave_de_Inventario__c>();
        String currentUserEmail = [Select Email From User where Id = : UserInfo.getUserId() limit 1].Email;

        for( Inventario__c inv : invList ){
            if( inv.Estatus__c == 'En Firma' && inv.Estatus__c != oldInvMap.get(inv.Id).Estatus__c ){
                invIdSet.add( inv.Id );
                invFechaMap.put( inv.Id, inv.Fecha_Inicio__c );
            }
        }

        if ( invIdSet.size() > 0 ){
            invToClaveInvMap = new  Map<Id, Inventario__c>([ SELECT Fecha_Inicio__c, (SELECT Inventario__c, Fecha_Inicio_Conteo__c, Estatus_de_Conteo__c, Tipo_de_Insumo__c, Clasificacion__c FROM Claves_de_Inventario__r)
                                                             FROM Inventario__c
                                                             WHERE Id IN : invIdSet ]);

            for( Inventario__c inv : invToClaveInvMap.values() ){          
                for( Clave_de_Inventario__c cveInv : inv.Claves_de_Inventario__r ){
                    if( inv.id == cveInv.Inventario__c && invFechaMap.get(inv.Id) == cveInv.Fecha_Inicio_Conteo__c ){
                        cveInvList.add(cveInv);
                    }
                }
                invNumCvesMap.put(inv.id, cveInvList.size());
            }
            System.debug('invNumCvesMap- ' + invNumCvesMap);

            for( Inventario__c inv : invList ){
                for( Clave_de_Inventario__c claveInv : cveInvList ){
                    if( claveInv.Estatus_de_Conteo__c != 'Contado' || inv.Numero_de_Insumos__c != cveInvList.size()) { 
                        String errorMessage = 'Aun tiene Claves sin actualizar o en estatus diferente a Contado el día de hoy';
                        inv.addError(errorMessage);
                    }
                }
            }
        }

        if( cveInvList.size() > 0 ) {   
            for( Inventario__c inventario : invList ){
                System.debug('inventario.Numero_de_Insumos__c: ' + inventario.Numero_de_Insumos__c);
                System.debug('invNumCvesMap.get(inventario.Id) ' + invNumCvesMap.get(inventario.Id));
                if( inventario.Numero_de_Insumos__c == invNumCvesMap.get(inventario.Id) ){
                    System.debug('Result: ' + inventario.Numero_de_Insumos__c +' | '+ invNumCvesMap.get(inventario.Id));
                    System.debug('USer ' + UserInfo.getName());
                    //inventario.Estatus__c = 'En Firma';
                    inventario.Registrado_Por__c = UserInfo.getName();
                    inventario.Registrado_Por_Email__c = currentUserEmail;
                    inventario.Fecha_Registrado__c = System.Now();
                } 
            }
        }
    }

    public static void attachPDFToInventario( List<Inventario__c> invList, Map<Id, Inventario__c> oldInvMap ){
        System.debug('attachPDFToInventario');
        
        Set<id> invId = New Set<id>();
        for(Inventario__c inv : invList){
            System.debug('inv.Estatus__c: ' + inv.Estatus__c);
            if( ( inv.Estatus__c == 'En Firma' || inv.Estatus__c == 'Firmado' ) && inv.Estatus__c != oldInvMap.get(inv.Id).Estatus__c ){
                System.debug('Inventario' + inv);
                invId.add(inv.Id);
            }
        }
        if(invId.size() > 0){
            String netId = network.getNetworkId();
            addPDFToRecord(invId, netId);
        }
    }

    @Future(callout=true)
    public static void addPDFToRecord(Set<id> inventarioIdList, String networkId){

        String estatus;
        String templateId;
        String htmlBody;
        String body;
        String subject;
        String inventarioId;
        String firmadoPor;
        DateTime fechaFirmado;
        String registradoPor;
        DateTime fechaRegistrado;
        Double offset;

        Set<String> csvRows = new Set<String>();

        List<ContentVersion> contentVerToInsList = New List<ContentVersion>();
        List<Clave_de_Inventario__c> claves = new List<Clave_de_Inventario__c>();

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        Messaging.EmailFileAttachment attachmentCSV = new Messaging.EmailFileAttachment();

        TimeZone tz = UserInfo.getTimeZone();
        //User currentUser = [Select Email From User where Id = : UserInfo.getUserId() limit 1];
        //String registradoPorEmail;
        
        EmailTemplate template = [SELECT Id, HtmlValue, Body, Subject, DeveloperName FROM EmailTemplate WHERE DeveloperName = 'Inventario_En_Firma']; 
        EmailTemplate templateFirmado = [SELECT Id, HtmlValue, Body, Subject, DeveloperName FROM EmailTemplate WHERE DeveloperName = 'Inventario_Firmado'];

        List<Lote_de_Inventario__c> lotes = [ SELECT Lote__c, Fecha_de_Caducidad__c, Conteo_Actual__c, Clave_de_Inventario__c
                                              FROM Lote_de_Inventario__c 
                                              WHERE Clave_de_Inventario__r.Inventario__r.Id = : inventarioIdList ];
  
        if( lotes.size() > 0 ) {
            system.debug('CSV');
            system.debug(lotes);

            Set<Id> clavesIds = new Set<Id>();
            for( Lote_de_Inventario__c li : lotes ) {
                clavesIds.add(li.Clave_de_Inventario__c);
            }
            
            claves = [ SELECT Inventario__r.Codigo_UMU__c, Inventario__r.Clave_Presupuestal__c, Nombre_UMU__c, Inventario__r.Delegaci_n__c,
                                Inventario__r.Name, Tipo_de_Insumo__c, Clasificacion__c, Codigo_de_Producto__c, Producto__r.Description__c,
                                Inventario__r.Fecha_Registrado__c, Inventario__r.Registrado_Por__c, Inventario__r.Signed_Date__c,
                                Inventario__r.Firmado_Por__c, Inventario__r.Estatus__c
                       FROM Clave_de_Inventario__c
                       WHERE Id IN :clavesIds ];

            System.debug('claves: ' + claves);
             
            for(Clave_de_Inventario__c clave : claves) {

                inventarioId = clave.Inventario__c;
                for (Lote_de_Inventario__c lote : lotes) {
                    if(clave.Id == lote.Clave_de_Inventario__c) {
                        if( clave.Inventario__r.Estatus__c == 'En Firma' ){
                            //firmadoPor = '';
                            //fechaFirmado = null;
                            //registradoPorEmail = clave.Inventario__r.Registrado_Por_Email__c;
                            registradoPor = clave.Inventario__r.Registrado_Por__c;
                            fechaRegistrado = clave.Inventario__r.Fecha_Registrado__c + tz.getOffset( clave.Inventario__r.Fecha_Registrado__c ) / (1000 * 3600 * 24.0);
                        } else if ( clave.Inventario__r.Estatus__c == 'Firmado' ){
                            firmadoPor = clave.Inventario__r.Firmado_Por__c;
                            fechaFirmado = clave.Inventario__r.Signed_Date__c + tz.getOffset( clave.Inventario__r.Signed_Date__c ) / (1000 * 3600 * 24.0);
                            //registradoPorEmail = clave.Inventario__r.Registrado_Por_Email__c;
                            registradoPor = clave.Inventario__r.Registrado_Por__c;
                            fechaRegistrado = clave.Inventario__r.Fecha_Registrado__c + tz.getOffset( clave.Inventario__r.Fecha_Registrado__c ) / (1000 * 3600 * 24.0);
                        }
                        csvRows.add('\'' + clave.Inventario__r.Codigo_UMU__c + ',' + '\'' + clave.Inventario__r.Clave_Presupuestal__c + ',' + clave.Nombre_UMU__c
                        + ',' + clave.Inventario__r.Delegaci_n__c + ',' + clave.Inventario__r.Name + ',' + clave.Tipo_de_Insumo__c
                        + ',' + clave.Clasificacion__c + ',' + '\'' + clave.Codigo_de_Producto__c + ',' + clave.Producto__r.Description__c.remove(',')
                        + ',' + lote.Lote__c + ',' + lote.Fecha_de_Caducidad__c
                        + ',' + lote.Conteo_Actual__c + ',' + fechaRegistrado + ',' + registradoPor + ',' + fechaFirmado
                        + ',' + firmadoPor + ',' + clave.Inventario__r.Estatus__c );
                    }
                }
            }
        }

        List<String> csvList = new List<String>(csvRows);
        List<String> headers = new List<String>{'UMU','CLAVE PRESUPUESTAL UMU','NOMBRE UMU','DELEGACIÓN','FOLIO DEL INVENTARIO',
                                                'TIPO DE INSUMO','CLASIFICACIÓN DE INSUMO','CLAVE','DESCRIPCIÓN CLAVE','LOTE','FECHA DE CADUCIDAD',
                                                'PIEZAS CONTADAS','FECHA DE REGISTRO','REGISTRADO POR','FECHA DE REVISIÓN','FIRMADO POR','ESTATUS' };

        String csvString = String.join(headers, ',') + '\n' + String.join(csvList, '\n');
        Blob contentCSVBlob = Blob.valueOf(csvString);

        for (Inventario__c inventario : [SELECT ID, Name, Nombre_UMU__c, Clave_Presupuestal__c, Owner.Name, Owner.Email, Codigo_UMU__c, Estatus__c, Registrado_Por_Email__c
                                         FROM Inventario__c 
                                         WHERE id IN : inventarioIdList]){
            // 
            PageReference inventarioPDFRef = new PageReference('/apex/InventarioPDF?id=' + inventario.Id + '&estatus=' + inventario.Estatus__c);
            Blob contentBlob;
            if( !Test.isRunningTest() ) { 
                contentBlob = inventarioPDFRef.getContentAsPDF();
            } else {
                contentBlob = blob.valueOf('Unit.Test');
            }          
            
            if( inventario.Estatus__c == 'En Firma' ){
                estatus = 'REGISTRADO-';
                templateId = template.Id;
                htmlBody = template.HtmlValue;
                body = template.Body;
                subject = template.Subject;
            } else if ( inventario.Estatus__c == 'Firmado' ){
                estatus = 'FIRMADO-';
                templateId = templateFirmado.Id;
                htmlBody = templateFirmado.HtmlValue;
                body = templateFirmado.Body;
                subject = templateFirmado.Subject;
            }

            ContentVersion contVersion = new ContentVersion();
            contVersion.Title = estatus+inventario.Clave_Presupuestal__c+'-'+inventario.Nombre_UMU__c;
            contVersion.PathOnClient = estatus+inventario.Clave_Presupuestal__c+'-'+inventario.Nombre_UMU__c+'.pdf';
            contVersion.VersionData = contentBlob;
            contVersion.FirstPublishLocationId = inventario.Id;
            contVersion.NetworkId = networkId;
            contentVerToInsList.add(contVersion);

            ContentVersion contVersionCSV = new ContentVersion();
            contVersionCSV.Title = estatus+inventario.Clave_Presupuestal__c+'-'+inventario.Nombre_UMU__c;
            contVersionCSV.PathOnClient = estatus+inventario.Clave_Presupuestal__c+'-'+inventario.Nombre_UMU__c+'.csv';
            contVersionCSV.VersionData = contentCSVBlob;
            contVersionCSV.FirstPublishLocationId = inventario.Id;
            contVersionCSV.NetworkId = networkId;
            contentVerToInsList.add(contVersionCSV);
            
            htmlBody = htmlBody.replace('{INVENTARIO_OWNER}', inventario.Owner.Name);
            htmlBody = htmlBody.replace('{UMU}', inventario.Nombre_UMU__c);
            htmlBody = htmlBody.replace('{CLAVE_UMU}', inventario.Codigo_UMU__c);
            
            subject = subject.replace('{ESTATUS}', inventario.Estatus__c);
			
			attachment.setFileName(contVersion.pathOnClient); 
            attachment.setBody(contVersion.versionData);

            attachmentCSV.setFileName(contVersionCSV.pathOnClient); 
            attachmentCSV.setBody(contVersionCSV.versionData);
			
            email.setSubject(subject);
            email.setHtmlBody(htmlBody);
            email.setPlainTextBody(body);
            email.setToAddresses(new List<String>{inventario.Owner.Email, inventario.Registrado_Por_Email__c});
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {attachment, attachmentCSV});
            System.debug('Inventario Email: ' + email);
            try {
                Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
                System.debug('Inventario Email Sent: ' + results);
            } catch (Exception e) {
                System.debug('Error sending email: ' + e.getMessage());
            }
        }
                  
        if(contentVerToInsList.size() > 0){
            insert contentVerToInsList; 
        }
    }

    public static void clearEstatusClave( List<Inventario__c> invList, Map<Id, Inventario__c> oldInvMap ){
        
        Set<Id> invIdSet = New Set<Id>();
        Set<Id> invToUpdateSet = New Set<Id>();

        List<Clave_de_Inventario__c> claveClearStList = New List<Clave_de_Inventario__c>();

        for( Inventario__c inv : invList ){
            System.debug('Inventario 01: ' + inv.Estatus__c);
            if( inv.Estatus__c == 'En Firma' && inv.Estatus__c != oldInvMap.get(inv.Id).Estatus__c ){
                invIdSet.add( inv.Id );
            }
        }

        if ( invIdSet.size() > 0 ){
            for(List<Clave_de_Inventario__c> claveList : [SELECT Inventario__c, Estatus_de_Conteo__c 
                                                          FROM Clave_de_Inventario__c
                                                          WHERE Inventario__c in : invIdSet]){  
                for( Clave_de_Inventario__c clave : claveList ){
                    clave.Estatus_de_Conteo__c = null;
                    claveClearStList.add(clave);
                }                
            }
        }
    
        if(claveClearStList.size() > 0){
            update claveClearStList;
        } 
        
    }
}