unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Estatus_de_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Estatus_de_Conteo__c</fullName>
    <description>Estatus del conteo del día.</description>
    <label>Estatus de Conteo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Fecha_Inicio_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Conteo__c</fullName>
    <description>Fecha en que inicia el conteo del día.</description>
    <label>Fecha Inicio Conteo</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Numero_Total_de_Lotes__c.field-meta.xml
<CustomField>
    <fullName>Numero_Total_de_Lotes__c</fullName>
    <description>Contiene el numero de lotes que hay para la clave de insumo.</description>
    <label>Numero Total de Lotes</label>
    <summaryForeignKey>Lote_de_Inventario__c.Clave_de_Inventario__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Estatus del inventario.</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registrado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Firmado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fecha_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio__c</fullName>
    <description>Fecha en que inicia el conteo de claves de inventario.</description>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Estatus_Conteo_Lote__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Conteo_Lote__c</fullName>
    <label>Estatus Conteo Lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Modificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Modificaci_n__c</fullName>
    <description>Fecha de última modificación.</description>
    <label>Fecha de Modificación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ClaveInventarioFields.cls
public with sharing class ClaveInventarioFields {
    public static void updateEstatusConteo(List<Clave_de_Inventario__c> claveInvList, Map<Id, Clave_de_Inventario__c> oldClaveMap){
        
        Set<Id> cveInvIdSet = New Set<Id>();
        Set<Id> invToUpdateSet = New Set<Id>();

        Map<Id, Clave_de_Inventario__c> cveInvToLoteInvMap = New Map<Id, Clave_de_Inventario__c>(); 
        Map<Id, Date> cveInvFechaMap = New Map<Id, Date>();
        Map<Id, Decimal> cveInvNumLotesMap = New Map<Id, Decimal>();

        List<Lote_de_Inventario__c> loteInvList = New List<Lote_de_Inventario__c>();
        List<Inventario__c> invToUpdList = New List<Inventario__c>();

        for( Clave_de_Inventario__c claveInv : claveInvList ){
            System.debug('claveInv.InvnetarioStatus- ' + claveInv.Inventario__r.Estatus__c);
            if( claveInv.Estatus_de_Conteo__c == 'Contado' && claveInv.Estatus_de_Conteo__c != oldClaveMap.get(claveInv.Id).Estatus_de_Conteo__c ){
                cveInvIdSet.add( claveInv.Id );
                cveInvFechaMap.put( claveInv.Id, claveInv.Fecha_Inicio_Conteo__c );
                System.debug('cveInvFechaMap- ' + cveInvFechaMap);
            }
        }

        if ( cveInvIdSet.size() > 0 ){
            cveInvToLoteInvMap = new  Map<Id, Clave_de_Inventario__c>([ SELECT Fecha_Inicio_Conteo__c, (SELECT Clave_de_Inventario__c, Fecha_de_Modificaci_n__c, Estatus_Conteo_Lote__c FROM Lotes_de_Inventario__r)
                                                                        FROM Clave_de_Inventario__c
                                                                        WHERE Id IN : cveInvIdSet ]);

            for(Clave_de_Inventario__c ci:cveInvToLoteInvMap.values()){          
                for(Lote_de_Inventario__c li : ci.Lotes_de_Inventario__r){                  
                    if(ci.id == li.Clave_de_Inventario__c && cveInvFechaMap.get(ci.Id) == li.Fecha_de_Modificaci_n__c ){
                        loteInvList.add(li);
                    }
                }
                cveInvNumLotesMap.put(ci.id, loteInvList.size());
                System.debug('loteInvList- ' + loteInvList);
            }
            System.debug('cveInvNumLotesMap- ' + cveInvNumLotesMap);
            for( Clave_de_Inventario__c claInv : claveInvList ){
                for( Lote_de_Inventario__c loteInv : loteInvList ){
                    if( loteInv.Estatus_Conteo_Lote__c != 'Contado' || claInv.Numero_Total_de_Lotes__c != loteInvList.size() ){ 
                        String errorMessage = 'Aun tiene Lotes sin actualizar o en estatus diferente a Contado el día de hoy';
                        claInv.addError(errorMessage);
                    }
                }
            }
        }
        
        if( loteInvList.size() > 0 ) {   
            for( Clave_de_Inventario__c claveInv : claveInvList ){
                System.debug('claveInv.Numero_Total_de_Lotes__c ' + claveInv.Numero_Total_de_Lotes__c);
                System.debug('cveInvNumLotesMap.get(claveInv.Id) ' + cveInvNumLotesMap.get(claveInv.Id));
                if( claveInv.Numero_Total_de_Lotes__c == cveInvNumLotesMap.get(claveInv.Id) ){
                    System.debug('Result: ' + claveInv.Numero_Total_de_Lotes__c +' | '+ cveInvNumLotesMap.get(claveInv.Id));
                    //claveInv.Estatus_de_Conteo__c = 'Contado';
                    invToUpdateSet.add(claveInv.Inventario__c);
                }
            }
        }  
        
        for(Inventario__c inv : [SELECT Estatus__c FROM Inventario__c WHERE Id IN : invToUpdateSet] ){
            inv.Estatus__c = 'Registrado';
            inv.Fecha_Inicio__c = System.Today();
            invToUpdList.add(inv);
        }
    
        if(invToUpdList.size() > 0){
            update invToUpdList;
        } 
        
    }

    public static void clearEstatusLote(List<Clave_de_Inventario__c> claveInvList, Map<Id, Clave_de_Inventario__c> oldClaveMap){
        
        Set<Id> cveInvIdSet = New Set<Id>();
        Set<Id> invToUpdateSet = New Set<Id>();

        List<Lote_de_Inventario__c> loteClearStList = New List<Lote_de_Inventario__c>();

        for( Clave_de_Inventario__c claveInv : claveInvList ){
            System.debug('H0000: ' + claveInv.Inventario__r.Estatus__c);
            if( claveInv.Estatus_de_Conteo__c == 'Contado' && claveInv.Estatus_de_Conteo__c != oldClaveMap.get(claveInv.Id).Estatus_de_Conteo__c ){
                cveInvIdSet.add( claveInv.Id );
            }
        }

        if ( cveInvIdSet.size() > 0 ){
            for(List<Lote_de_Inventario__c> loteList : [SELECT Clave_de_Inventario__c, Estatus_Conteo_Lote__c 
                                                        FROM Lote_de_Inventario__c
                                                        WHERE Clave_de_Inventario__c in : cveInvIdSet]){  
                for( Lote_de_Inventario__c lote : loteList ){
                    lote.Estatus_Conteo_Lote__c = null;
                    loteClearStList.add(lote);
                }                
            }
        }
    
        if(loteClearStList.size() > 0){
            update loteClearStList;
        } 
        
    }
}