unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Estatus_de_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Estatus_de_Conteo__c</fullName>
    <description>Estatus del conteo del día.</description>
    <label>Estatus de Conteo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Fecha_Inicio_Conteo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Conteo__c</fullName>
    <description>Fecha en que inicia el conteo del día.</description>
    <label>Fecha Inicio Conteo</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Estatus_Conteo_Lote__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Conteo_Lote__c</fullName>
    <label>Estatus Conteo Lote</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Iniciado</fullName>
            </value>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Estatus_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Inventario__c</fullName>
    <description>Estatus del Inventario Relacionado.</description>
    <formula>TEXT(Clave_de_Inventario__r.Inventario__r.Estatus__c)</formula>
    <label>Estatus Inventario</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Modificaci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Modificaci_n__c</fullName>
    <description>Fecha de última modificación.</description>
    <label>Fecha de Modificación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_Inicio_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_Inventario__c</fullName>
    <description>Campo de ayuda para las validar si el Inventario relacionado esta en estatus En Firma el día actual.</description>
    <formula>Clave_de_Inventario__r.Inventario__r.Fecha_Inicio__c</formula>
    <label>Fecha Inicio Inventario</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/LoteInventarioFields.cls
public with sharing class LoteInventarioFields {

    public static void updateInsertFechaModif( List<Lote_de_Inventario__c> loteInvList ){
        for( Lote_de_Inventario__c loteInv : loteInvList ){
            loteInv.Fecha_de_Modificaci_n__c = System.today();
            System.debug('loteInv.Fecha_de_Modificaci_n__c 1: ' + loteInv.Fecha_de_Modificaci_n__c);
        }
    }

    public static void updateInsertCveInventario( List<Lote_de_Inventario__c> loteInvList ){

        Set<Id> cveInvIdSet = New Set<Id>();
        Set<Id> cveInvIdFutureSet = New Set<Id>();
        Map<Id, Clave_de_Inventario__c> claveInvMap = new Map<Id, Clave_de_Inventario__c>();
        Map<Id, Clave_de_Inventario__c> claveInvToUpdMap = new Map<Id, Clave_de_Inventario__c>();

        for( Lote_de_Inventario__c loteInv : loteInvList ){
            cveInvIdSet.add(loteInv.Clave_de_Inventario__c);
        }

        claveInvMap = new Map<Id, Clave_de_Inventario__c>([SELECT Id, Estatus_de_Conteo__c, Fecha_Inicio_Conteo__c 
                                                           FROM Clave_de_Inventario__c 
                                                           WHERE ID IN :cveInvIdSet]); 

        for( Lote_de_Inventario__c loteInve : loteInvList ){
            System.debug( 'fecha inve : ' + loteInve.Fecha_Inicio_Inventario__c );
            if( loteInve.Estatus_Inventario__c != 'En Firma' || ( loteInve.Estatus_Inventario__c == 'En Firma' && loteInve.Fecha_Inicio_Inventario__c != System.Today() ) ){
                if( loteInve.Estatus_Conteo_Lote__c != null ){
                    Clave_de_Inventario__c cveInv = claveInvMap.get(loteInve.Clave_de_Inventario__c);

                    System.debug('cveInv.Estatus_de_Conteo__c: ' + cveInv.Estatus_de_Conteo__c);
                    
                    if(( cveInv.Estatus_de_Conteo__c == 'Iniciado' || cveInv.Estatus_de_Conteo__c == 'Contado' || cveInv.Estatus_de_Conteo__c == null ) && cveInv.Fecha_Inicio_Conteo__c != loteInve.Fecha_de_Modificaci_n__c ){
                        cveInv.Estatus_de_Conteo__c = cveInv.Estatus_de_Conteo__c != 'Iniciado' ? 'Iniciado' : cveInv.Estatus_de_Conteo__c;
                        cveInv.Fecha_Inicio_Conteo__c = loteInve.Fecha_de_Modificaci_n__c;
                        //cveInvToUpdateList.add(cveInv);
                        if ( !claveInvToUpdMap.containsKey( loteInve.Clave_de_Inventario__c )){
                            claveInvToUpdMap.put(loteInve.Clave_de_Inventario__c, cveInv);
                        }
                        System.debug('claveInvToUpdMap 1: ' + claveInvToUpdMap.values());
                    } else if( cveInv.Estatus_de_Conteo__c == 'Iniciado' && cveInv.Fecha_Inicio_Conteo__c == loteInve.Fecha_de_Modificaci_n__c ){
                        if ( !claveInvToUpdMap.containsKey( loteInve.Clave_de_Inventario__c )){
                            claveInvToUpdMap.put(loteInve.Clave_de_Inventario__c, cveInv);
                        }
                        System.debug('claveInvToUpdMap 2: ' + claveInvToUpdMap.values());
                    } else if( ( cveInv.Estatus_de_Conteo__c == 'Contado' ) && cveInv.Fecha_Inicio_Conteo__c == loteInve.Fecha_de_Modificaci_n__c ){
                        String errorMessage = 'No se puede iniciar un nuevo conteo el mismo dia. Estatus del Conteo: ' + cveInv.Estatus_de_Conteo__c ;
                        loteInve.addError(errorMessage);
                    }
                }
            } else {
                String errorMessage = 'No se puede iniciar un conteo para un Inventario que se encuentra En Firma';
                loteInve.addError(errorMessage);
            }
        }

        if(claveInvToUpdMap.values().size() > 0){
            System.debug('claveInvToUpdMap 3: ' + claveInvToUpdMap.values());
            update claveInvToUpdMap.values();
        }  
    }

    public static void deleteCurrentLote( List<Lote_de_Inventario__c> oldLoteList ){
        for( Lote_de_Inventario__c lotInventario : oldLoteList ){
            System.debug('Fecha: ' + lotInventario.CreatedDate.Date() + ' | ' + lotInventario.Fecha_de_Modificaci_n__c);
            System.debug('User: ' + UserInfo.getUserId()  + ' | ' + lotInventario.CreatedById);
            if( lotInventario.CreatedDate.Date() != System.Today() || lotInventario.Estatus_Inventario__c == 'En Firma' ){
                String errorMessage = 'Solo se permite borrar un Lote que haya sido creado el dia del conteo y que no se encuentre En Firma';
                lotInventario.addError(errorMessage);
            }
        }
    }
}