unpackaged/main/default/objects/Clave_de_Inventario__c/Clave_de_Inventario__c.object-meta.xml
<CustomObject>
    <label>Clave de Inventario</label>
    <nameField>
        <displayFormat>CVEINV-{000000}</displayFormat>
        <label>Clave de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claves de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <description>Medicamento/Material de Curación.</description>
    <formula>TEXT(Producto__r.Simple_Classification__c)</formula>
    <label>Clasificación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Codigo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto__c</fullName>
    <formula>Producto__r.Product_Code_ID__c</formula>
    <label>Codigo de Producto</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Conteo_Actual_Total__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Actual_Total__c</fullName>
    <description>Cantidad actual total del producto por Insumo.</description>
    <label>Conteo Actual Total</label>
    <summarizedField>Lote_de_Inventario__c.Conteo_Actual__c</summarizedField>
    <summaryForeignKey>Lote_de_Inventario__c.Clave_de_Inventario__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Nombre_UMU__c.field-meta.xml
<CustomField>
    <fullName>Nombre_UMU__c</fullName>
    <description>Nombre de la UMU almacenado en objeto relacionado Inventario</description>
    <formula>Inventario__r.Nombre_UMU__c</formula>
    <label>Nombre UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Claves de Inventario</relationshipLabel>
    <relationshipName>Claves_de_Inventario</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clave_de_Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <description>Tipo de Insumo para inventarios. Ordinario, Programa, Vacunas, Compra local.</description>
    <formula>TEXT( Producto__r.Programa__r.Inventario__c )</formula>
    <label>Tipo de Insumo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Clave_Presupuestal__c.field-meta.xml
<CustomField>
    <fullName>Clave_Presupuestal__c</fullName>
    <description>Clave Presupuestal almacenada en objeto Cuenta.</description>
    <formula>UMU__r.Clave_Presupuestal__c</formula>
    <label>Clave Presupuestal</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Codigo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Codigo_UMU__c</fullName>
    <description>Código de identificación de la Unidad Médica.</description>
    <formula>UMU__r.UMU__c</formula>
    <label>Código UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Conteo_Total_Actual__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Total_Actual__c</fullName>
    <description>Conteo total de piezas por inventario. Campo utilizado en la creación de PDFs.</description>
    <label>Conteo Total Actual</label>
    <summarizedField>Clave_de_Inventario__c.Conteo_Actual_Total__c</summarizedField>
    <summaryForeignKey>Clave_de_Inventario__c.Inventario__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Conteo_Total_Lotes__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Total_Lotes__c</fullName>
    <description>Conteo total de lotes por inventario. Campo utilizado en la creación de PDFs.</description>
    <label>Conteo Total Lotes</label>
    <summarizedField>Clave_de_Inventario__c.Numero_Total_de_Lotes__c</summarizedField>
    <summaryForeignKey>Clave_de_Inventario__c.Inventario__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Delegaci_n__c.field-meta.xml
<CustomField>
    <fullName>Delegaci_n__c</fullName>
    <description>Delegación de la UMU relacionada. Utilizado para mostrar su valor en InventarioPDF</description>
    <formula>UMU__r.Delegacion__c</formula>
    <label>Delegación</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fecha_Registrado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Registrado__c</fullName>
    <description>Fecha y hora en que se registró el conteo de inventario por el ANS.</description>
    <label>Fecha Registrado</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Firmado_Por__c.field-meta.xml
<CustomField>
    <fullName>Firmado_Por__c</fullName>
    <description>Nombre del usuario que firma el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a Firmado.</description>
    <label>Firmado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Nombre_UMU__c.field-meta.xml
<CustomField>
    <fullName>Nombre_UMU__c</fullName>
    <description>Campo de ayuda para usar en la Plantilla de Email: Inventario En Firma.</description>
    <formula>UMU__r.Name</formula>
    <label>Nombre UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Registrado_Por__c.field-meta.xml
<CustomField>
    <fullName>Registrado_Por__c</fullName>
    <description>Nombre del usuario que registra el inventario. Se llena en automático mediante el trigger cuando el usuario cambia el estatus a En Firma.</description>
    <label>Registrado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_Date__c</fullName>
    <description>Día en que fue firmado el registro del inventario por el jefe de almacén.</description>
    <label>Fecha De Firma</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Vacunas</fullName>
            </value>
            <value>
                <fullName>Compra Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Tipo_UMU__c.field-meta.xml
<CustomField>
    <fullName>Tipo_UMU__c</fullName>
    <description>Campo que contiene el tipo de UMU almacenado en el objeto relacionado Account.</description>
    <formula>CASE(UMU__r.Tipo_UMU__c, 
&quot;CAF&quot;, &quot;CONSULTORIO ATENCIÓN FAMILIA&quot;,
&quot;CC&quot;, &quot;CENTRO DE CANJE&quot;,
&quot;CE&quot;, &quot;CLÍNICA DE ESPECIALIDADES&quot;,
&quot;CH&quot;, &quot;CLÍNICA HOSPITAL&quot;,
&quot;CMCT&quot;, &quot;CONSULTORIO MÉDICO EN CENTRO DE TRABAJO&quot;,
&quot;CMF&quot;, &quot;CLÍNICA MEDICINA FAMILIAR&quot;,
&quot;CMFE&quot;, &quot;CLÍNICA DE MEDICINA FAMILIAR CON ESPECIALIDADES&quot;,
&quot;CMN&quot;, &quot;CENTRO MÉDICO NACIONAL&quot;,
&quot;HG&quot;, &quot;HOSPITAL GENERAL&quot;,
&quot;HR&quot;, &quot;HOSPITAL REGIONAL&quot;,
&quot;NA&quot;, &quot;NO APLICA&quot;,
&quot;UE&quot;, &quot;UNIDAD ESPECIAL&quot;,
&quot;UMF&quot;, &quot;UNIDAD DE MEDICINA FAMILIAR&quot;, 
&quot;&quot;)</formula>
    <label>Tipo UMU</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/Lote_de_Inventario__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los conteos de productos por lote.</description>
    <label>Lote de Inventario</label>
    <nameField>
        <displayFormat>LINV-{0000000}</displayFormat>
        <label>Lote de Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Inventario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Clave_de_Inventario__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Inventario__c</fullName>
    <label>Clave de Inventario</label>
    <referenceTo>Clave_de_Inventario__c</referenceTo>
    <relationshipLabel>Lotes de Inventario</relationshipLabel>
    <relationshipName>Lotes_de_Inventario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Conteo_Actual__c.field-meta.xml
<CustomField>
    <fullName>Conteo_Actual__c</fullName>
    <description>Cantidad actual contada en el lote.</description>
    <label>Conteo Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Fecha_de_Caducidad__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Caducidad__c</fullName>
    <description>Fecha de caducidad del insumo en el lote.</description>
    <label>Fecha de Caducidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lote_de_Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <description>Texto que identifica al lote.</description>
    <label>Lote</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tipo_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Insumo__c</fullName>
    <label>Tipo de Insumo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/InventarioPDFController.cls
public with sharing class InventarioPDFController {

    public Clave_de_Inventario__c inventario { get; set; }
    private String inventarioId {get;set;}
    public String estatusInventario {get;set;}
    public Decimal clavesContadas {get;set;}
    public Decimal lotesContados {get;set;}
    public Decimal piezasContadas {get;set;}
    public List<Clave_de_Inventario__c> claves {get;set;}
    public List<InventarioWrapper> inventarioDataList {get;set;}
    public String cadenaContenido {get;set;}
    public Double offsetR {get;set;}
    public Double offsetF {get;set;}

    public InventarioPDFController() {

        //String loteInfo;
        //Date caducidadInfo;
        //Decimal piezasInfo;
        String registradoPorEmail;
        String firmadoPorEmail;
        TimeZone tz = UserInfo.getTimeZone();

        User currentUser = [Select Email From User where Id = : UserInfo.getUserId() limit 1];
        registradoPorEmail = currentUser.Email;

        try{ 
            inventarioId = ApexPages.currentPage().getParameters().get('id'); 
            estatusInventario = ApexPages.currentPage().getParameters().get('estatus');
            System.debug('estatusInventario' + estatusInventario);
        } catch(Exception e){
            System.debug(e.getMessage());
        } 

        try{
            inventario = [  SELECT Inventario__r.Fecha_Registrado__c, Tipo_de_Insumo__c, Clasificacion__c, Nombre_UMU__c, Inventario__r.Codigo_UMU__c, 
                                    Inventario__r.Clave_Presupuestal__c, Inventario__r.Delegaci_n__c, Inventario__r.Signed_Date__c, Inventario__r.Tipo_UMU__c,
                                    Inventario__r.Name, Inventario__r.Firmado_Por__c, Inventario__r.Registrado_Por__c, Inventario__r.Conteo_Total_Actual__c,
                                    Inventario__r.Conteo_Total_Lotes__c, Inventario__r.Owner.Email
                            FROM Clave_de_Inventario__c
                            WHERE Inventario__c = :inventarioId
                            LIMIT 1 ];
            
            offsetR = tz.getOffset(inventario.Inventario__r.Fecha_Registrado__c) / (1000 * 3600 * 24.0);
            offsetF = tz.getOffset(inventario.Inventario__r.Signed_Date__c) / (1000 * 3600 * 24.0);

        } catch(Exception e) {
            System.debug(e.getMessage());
        }

        try{ 
            claves = [ SELECT Codigo_de_Producto__c, Clasificacion__c, Producto__r.Description__c, Tipo_de_Insumo__c, Conteo_Actual_Total__c, 
                                ( SELECT Lote__c, Fecha_de_Caducidad__c, Conteo_Actual__c FROM Lotes_de_Inventario__r )
                        FROM Clave_de_Inventario__c
                        WHERE Inventario__c = :inventarioId ];
            
            Integer contador = 1;

            inventarioDataList = new List<InventarioWrapper>(); 
            for(Integer i = 0; i < claves.size(); i++){

                InventarioWrapper invData = new InventarioWrapper();
                invData.clave = claves[i].Codigo_de_Producto__c;
                invData.descripcion = claves[i].Producto__r.Description__c;
                invData.conteoTotal = claves[i].Conteo_Actual_Total__c;

                List<String> loteList = new List<String>(); 
                List<String> caducidadList = new List<String>(); 
                List<String> piezasList = new List<String>(); 

                if(!claves[i].Lotes_de_Inventario__r.isEmpty()){
                    for(Integer j = 0; j < claves[i].Lotes_de_Inventario__r.size(); j++){

                        String loteInfo = claves[i].Lotes_de_Inventario__r[j].Lote__c;
                        Date caducidadInfo = claves[i].Lotes_de_Inventario__r[j].Fecha_de_Caducidad__c;
                        Decimal piezasInfo = claves[i].Lotes_de_Inventario__r[j].Conteo_Actual__c;

                        if(!String.isBlank(loteInfo)){ 
                            loteList.add(loteInfo);
                        } else{
                            loteList.add('N/A');
                        }

                        if(caducidadInfo != null){
                            caducidadList.add(String.valueOf(caducidadInfo));
                        } else{
                            caducidadList.add('N/A');
                        } 

                        if(piezasInfo != null){
                            piezasList.add(String.valueOf(piezasInfo));
                        } else{
                            piezasList.add('N/A');
                        } 
                    } 
                } else {
                    loteList.add('N/A');
                    caducidadList.add('N/A');
                    piezasList.add('N/A');
                }
                invData.loteList = loteList; 
                invData.caducidadList = caducidadList;
                invData.piezasList = piezasList;
                inventarioDataList.add(invData);
            }
            
            clavesContadas = claves.size(); 
            piezasContadas = inventario.Inventario__r.Conteo_Total_Actual__c;
            lotesContados = inventario.Inventario__r.Conteo_Total_Lotes__c;
            firmadoPorEmail = inventario.Inventario__r.Owner.Email;
            cadenaContenido = inventario.Inventario__r.Name + ',' + inventario.Inventario__r.Clave_Presupuestal__c + ',' + clavesContadas  + ',' +
                              piezasContadas + ',' + inventario.Inventario__r.Registrado_Por__c + ',' + registradoPorEmail + ',' + inventario.Inventario__r.Firmado_Por__c + ',' + 
                              firmadoPorEmail + ',' + inventario.Inventario__r.Fecha_Registrado__c + ',' + inventario.Inventario__r.Signed_Date__c;
            
        } catch(Exception e){
            System.debug(e.getMessage());
        } 
    }

    public class InventarioWrapper{
        public String clave {get;set;}
        public String descripcion {get;set;}
        public Decimal conteoTotal {get;set;}
        public List<String> loteList {get;set;}
        public List<String> caducidadList {get;set;}
        public List<String> piezasList {get;set;}
    }
}