unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>La funcion de este field es poder mostrar la clave al usuario.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DPNLIConsumidoUpdateBatchTest.cls
@IsTest
public with sharing class DPNLIConsumidoUpdateBatchTest {

    @TestSetup
	static void createTestData() {
        String uniqueUserName = String.ValueOf(System.Now()).replaceAll('[^a-zA-Z0-9]', '');
        User user = TestDataFactory.initCommunityLoginUser(uniqueUserName);

        List<Id> accountIdList = new List<Id>();
        List<AccountContactRelation> accountContactList = [
            SELECT AccountId, Account.Name  
            FROM AccountContactRelation 
            WHERE ContactId =: user.ContactId
        ];  
        for(AccountContactRelation accConRel : accountContactList){
            accountIdList.add(accConRel.AccountId);
        }

        DPN__c dpn = TestDataFactory.createSingleDPN(accountIdList[0]);
    }

    @IsTest
    static void testDPNLIConsumidoUpdateBatch() {
        Test.startTest();

        DPN__c dpn = [SELECT Id FROM DPN__c LIMIT 1 FOR UPDATE];

        Product2 clave = TestDataFactory.createSingleProduct2('Medicina de Prueba'); 

        // Create test data
        List<DPN_Line_Item__c> dpnliList = new List<DPN_Line_Item__c>();
        for (Integer i = 0; i < 200; i++) {
            DPN_Line_Item__c dpnli = new DPN_Line_Item__c();
            dpnli.DPN__c = dpn.Id;
            dpnli.Product__c = clave.Id;
            dpnliList.add(dpnli);
        }
        insert dpnliList;
        
        // Create an instance of the batch class
        DPNLIConsumidoUpdateBatch batch = new DPNLIConsumidoUpdateBatch();
        String batchableContext = Database.executeBatch(batch, 200);
        
        // Perform assertions to verify the result
        List<DPN_Line_Item__c> updatedDpnliList = [
            SELECT Id, Activo__c
            FROM DPN_Line_Item__c
            WHERE Id IN :dpnliList
        ];
        for (DPN_Line_Item__c dpnli : updatedDpnliList) {
            System.assertEquals(true, dpnli.Activo__c);
        }
    }
}