unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN_Line_Item__c/DPN_Line_Item__c.object-meta.xml
<CustomObject>
    <label>DPN Line Item</label>
    <nameField>
        <displayFormat>DPNLI-{00000000}</displayFormat>
        <label>DPN Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPN Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN_Line_Item__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>DPN Line Items</relationshipLabel>
    <relationshipName>DPN_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/DPNControllerTest.cls
@IsTest
public with sharing class DPNControllerTest {

    // CONSIDERAR HACER MODIFICACIONES EN LA CLASE, VER NOTAS EN CADA MÉTODO

    @TestSetup
	static void createTestData() {
  
        Account account = TestDataFactory.createSingleAccount('AGUASCALIENTESTEST');
        Product2 product = TestDataFactory.createSingleProduct2('Acetaminofen');
        DPN__c dpn = TestDataFactory.createSingleDPN(account.Id);
        DPN_Line_Item__c dpnLineItem = TestDataFactory.createSingleDPNLineItem(dpn.Id, product.Id);
        List<Contact> contactList = TestDataFactory.createMultipleContactRelatedToAccount(account.Id, 'Tester', 'Class', 2);
    }

  	@isTest
    static void getDPNTest(){
        
        Test.startTest();
        	List<Account> accountList = DPNController.getDPN('AGUAS');
        Test.stopTest();
        
        Assert.areEqual(1, accountList.size());
        
    }
    
    @isTest
    static void getDpnListTest(){
        DPN__c dpn = [SELECT Id FROM DPN__c LIMIT 1];
        
        Test.startTest();
        	List<DPN_Line_Item__c> dpnLineItemTest = DPNController.getDpnList(dpn.Id);
        Test.stopTest();
        
        Assert.isNotNull(dpnLineItemTest);
    }
    
    @isTest
    static void getDataFromContactTest(){
        
        
        Test.startTest();
        	List<Contact> contactList = DPNController.getDataFromContact();
        Test.stopTest();
        
        Assert.isNotNull(contactList);
    }
  
}