unpackaged/main/default/objects/Subalmacen__c/Subalmacen__c.object-meta.xml
<CustomObject>
    <description>Almacén que maneja un Stock propio de la Dependencia a la cual está inscrito.</description>
    <label>Subalmacen</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subalmacenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subalmacen__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <label>Numero de Subalmacen</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SubalmacenControllerTest.cls
@isTest
public class SubalmacenControllerTest {

    @IsTest
    static void GetSubalmacenByIdTest() {
        Subalmacen__c subalmacen = TestDataFactory.createSingleSubalmacen('100', 'GENERAL');

        Test.startTest();
        Subalmacen__c result = SubalmacenController.getSubalmacenById(subalmacen.Id);
        Test.stopTest();

        System.assertEquals(subalmacen.Id, result.Id);
        System.assertEquals(subalmacen.Numero_de_Subalmacen__c, result.Numero_de_Subalmacen__c);
        System.assertEquals(subalmacen.Name, result.Name);
    }
    
    @IsTest
    static void GetSubalmacenById_ExceptionTest() {
        Test.startTest();
        try {
            SubalmacenController.getSubalmacenById('InvalidId');
            System.assert(false, 'No se lanzó una excepción esperada');
        } catch (AuraHandledException e) {
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
        Test.stopTest();
    }
}