unpackaged/main/default/objects/Subalmacen__c/Subalmacen__c.object-meta.xml
<CustomObject>
    <description>Almacén que maneja un Stock propio de la Dependencia a la cual está inscrito.</description>
    <label>Subalmacen</label>
    <nameField>
        <label>Sub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subalmacenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subalmacen__c/fields/Numero_de_Subalmacen__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Subalmacen__c</fullName>
    <label>Numero de Subalmacen</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SubalmacenController.cls
public without sharing class SubalmacenController {
    @AuraEnabled(cacheable=true)
    public static Subalmacen__c getSubalmacenById(String subalmacenId) {
        try {
            return [SELECT Id, Numero_de_Subalmacen__c, Name
                    FROM Subalmacen__c
                    WHERE Id = :subalmacenId
                    LIMIT 1];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
}