unpackaged/main/default/objects/D_a_de_Pedido__c/D_a_de_Pedido__c.object-meta.xml
<CustomObject>
    <label>Día de Pedido</label>
    <nameField>
        <displayFormat>DP-{00000000}</displayFormat>
        <label>Día de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Días de Pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>Días de Pedido</relationshipLabel>
    <relationshipName>D_as_de_Pedido</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CalendarioDeValidacionesControllerTest.cls
@isTest
public class CalendarioDeValidacionesControllerTest {
  @isTest
  public static void testGetCalendarioValidaciones() {
      Account acc = TestDataFactory.createSingleAccount('Test Account');
      DPN__c dpn = TestDataFactory.createSingleDPN(acc.Id);
      D_a_de_Pedido__c orderDate = TestDataFactory.createSingleOrderDate(dpn.Id);
      
      Test.startTest();
      List<D_a_de_Pedido__c> calendarioVal = CalendarioDeValidacionesController.getCalendarioValidaciones(acc.Id);
      Test.stopTest();
      
      System.assertEquals(1, calendarioVal.size());
      System.assertEquals(orderDate.Id, calendarioVal[0].Id);
  }
}