unpackaged/main/default/objects/D_a_de_Pedido__c/D_a_de_Pedido__c.object-meta.xml
<CustomObject>
    <label>Día de Pedido</label>
    <nameField>
        <displayFormat>DP-{00000000}</displayFormat>
        <label>Día de Pedido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Días de Pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <label>DPN</label>
    <referenceTo>DPN__c</referenceTo>
    <relationshipLabel>Días de Pedido</relationshipLabel>
    <relationshipName>D_as_de_Pedido</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/Hora_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Hora_de_Fin__c</fullName>
    <defaultValue>TIMEVALUE(&quot;16:00:00.000&quot;)</defaultValue>
    <label>Hora de Fin</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/D_a_de_Pedido__c/fields/Hora_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Hora_de_Inicio__c</fullName>
    <defaultValue>TIMEVALUE(&quot;07:00:00.000&quot;)</defaultValue>
    <label>Hora de Inicio</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/DPN__c.object-meta.xml
<CustomObject>
    <description>Demanda Programada Nacional</description>
    <label>DPN</label>
    <nameField>
        <displayFormat>DPN-{00000000}</displayFormat>
        <label>DPN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DPNs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DPN__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs (UMU)</relationshipLabel>
    <relationshipName>DPNs1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/DPN__c.field-meta.xml
<CustomField>
    <fullName>DPN__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DPN</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DPNs</relationshipLabel>
    <relationshipName>DPNs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DPN__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Historico</fullName>
            </value>
            <value>
                <fullName>No Ordinario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CalendarioDeValidacionesController.cls
public with sharing class CalendarioDeValidacionesController {
  @AuraEnabled(cacheable=true)
  public static List<D_a_de_Pedido__c> getCalendarioValidaciones(String accId) {
    try {
      String status = 'Activo';
     

      List<D_a_de_Pedido__c> calendarioVal = [
        SELECT DPN__c, Name, Fecha__c, Hora_de_Inicio__c, Hora_de_Fin__c
        FROM D_a_de_Pedido__c
        WHERE DPN__r.Account__c = :accId AND DPN__r.Estatus__c = :status
        ORDER BY Fecha__c ASC
      ];

      return calendarioVal;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}