unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Cantidad_de_Piezas_Recibidas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas_Recibidas__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Guarda la cantidad de piezas recibidas por el auxiliar de farmacia.</description>
    <label>Cantidad de Piezas Faltantes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripcion</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Creado Por</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripcion</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Fecha_De_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Fecha_De_Entrega__c</fullName>
    <label>Fecha De Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Hora_De_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Hora_De_Entrega__c</fullName>
    <label>Hora De Entrega</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <label>Tipo de Pedido</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Extraordinario</fullName>
            </value>
            <value>
                <fullName>Programa</fullName>
            </value>
            <value>
                <fullName>Replaneación</fullName>
            </value>
            <value>
                <fullName>Soporte de Vida</fullName>
            </value>
            <value>
                <fullName>Urgencia Médica</fullName>
            </value>
            <value>
                <fullName>Emergencia Sanitaria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Total_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Total_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Recibida__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Recibida__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad recibida en UMU al momento de recibir la entrega.</description>
    <label>Cantidad Recibida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_Solicitada__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_Solicitada__c</fullName>
    <label>Cantidad Solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Piezas_Faltantes__c.field-meta.xml
<CustomField>
    <fullName>Piezas_Faltantes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Aqui se guardan las piezas faltantes al momento de registrar una entrega parcial.</description>
    <label>Piezas Faltantes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Tipo_de_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pedido__c</fullName>
    <formula>TEXT(Order__r.Tipo_de_Pedido__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Pedido</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/UMU__c.field-meta.xml
<CustomField>
    <fullName>UMU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UMU</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Line Items (UMU)</relationshipLabel>
    <relationshipName>Order_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/OrderController.cls
public with sharing class OrderController {
  public class OrderWrapper {
    public String umu;
    public String tipoDePedido;
    public Integer totalDePiezas;
    public String contactId;
    public String status;
    public List<OrderItemWrapper> orderItems;
  }

  public class OrderItemWrapper {
    public String productId;
    public Integer cantidadSolicitada;
    public String umu;
  }

  @AuraEnabled
  public static String createOrder(String jsonData) {
    // Parse the JSON data into an Apex object
    OrderWrapper orderWrapper = (OrderWrapper) JSON.deserialize(
      jsonData,
      OrderWrapper.class
    );

    Order__c newOrder = new Order__c();
    newOrder.UMU__c = orderWrapper.umu;
    newOrder.Tipo_de_Pedido__c = orderWrapper.tipoDePedido;
    newOrder.Total_de_Piezas__c = orderWrapper.totalDePiezas;
    newOrder.Contacto__c = orderWrapper.contactId;
    newOrder.Estatus__c = orderWrapper.status;

    // Create a list to hold the Order_Line_Item__c records
    List<Order_Line_Item__c> orderItems = new List<Order_Line_Item__c>();

    for (OrderItemWrapper itemWrapper : orderWrapper.orderItems) {
      Order_Line_Item__c newItem = new Order_Line_Item__c();
      newItem.Product__c = itemWrapper.productId;
      newItem.Cantidad_Solicitada__c = itemWrapper.cantidadSolicitada;
      newItem.Order__c = newOrder.Id; // Set the Order__c field on the Order_Line_Item__c record

      orderItems.add(newItem);
    }

    try {
      insert newOrder;
      insert orderItems;
      return 'Order created successfully!';
    } catch (DmlException e) {
      // TODO: change this for an aura exception
      return 'Error creating order: ' + e.getMessage();
    }
  }

  @AuraEnabled
  public static String registrarOrden(String orderId, String status) {
    Set<String> setName = new Set<String>{ 'En Firma', 'Rechazado' };

    if (!setName.contains(status)) {
      return 'El estado proporcionado es incorrecto.';
    }

    List<Order__c> orders = [
      SELECT Id, Estatus__c, Fecha_De_Entrega__c, Hora_De_Entrega__c
      FROM Order__c
      WHERE Id = :orderId
    ];

    try {
      if (orders.size() > 0) {
        for (Order__c orden : orders) {
          orden.Estatus__c = status;
          orden.Fecha_De_Entrega__c = System.now().date(); 
          orden.Hora_De_Entrega__c = System.now().time();
        }

        update orders;
      }
    } catch (Exception e) {
      System.debug(e.getMessage());
      System.debug(e.getStackTraceString());
      // TODO: change this for an aura exception
      return 'Error al enviar registro: ' + e.getMessage();
    }
    return 'Enviado correctamente.';
  }

  @AuraEnabled
  public static String registrarOrdenParcial(
    String orderId,
    String status,
    String ordenParcialJson
  ) {
    Set<String> setName = new Set<String>{ 'Recibido Parcial' };

    if (!setName.contains(status)) {
      return 'El estado proporcionado es incorrecto.';
    }

    OrderUpdates orderUpdates = (OrderUpdates) JSON.deserialize(
      ordenParcialJson,
      OrderUpdates.class
    );

    List<Order__c> orders = [
      SELECT
        Id,
        Estatus__c,
        (
          SELECT Id, Estatus__c, Cantidad_Solicitada__c, Cantidad_Recibida__c, Piezas_Faltantes__c,  Cantidad_de_Piezas__c
          FROM Order_Line_Items__r
        )
      FROM Order__c
      WHERE Id = :orderId
      LIMIT 1
    ];

    List<Informacion_De_Lote__c> lotesUpdateList = new List<Informacion_De_Lote__c>();
    try {
      if (orders.size() > 0) {
        for (Order__c orden : orders) {
          orden.Estatus__c = status;
          orden.Descripcion__c = orderUpdates.descripcion;
          orden.Motivo__c = orderUpdates.desviacion;

          // TODO: Check this to confirm its ok.
          orden.Fecha_De_Entrega__c = orderUpdates.selectedDate;
          orden.Hora_De_Entrega__c = orderUpdates.selectedTime;

          Map<Id, Integer> getQuantityPerLote = new Map<Id, Integer>();

          for (OrderItemUpdate itemUpdate : orderUpdates.orderItemsUpdates) {
            for(Lote lote: itemUpdate.lotes){
                getQuantityPerLote.put(lote.Id, lote.cantidadDePiezasFaltantes);
            }
          }
         
          for(Informacion_De_Lote__c lote: [SELECT Id,Cantidad_de_Piezas_Recibidas__c
                                            FROM  Informacion_De_Lote__c
                                            WHERE Id 
                                            IN: getQuantityPerLote.keySet()]){

            lote.Cantidad_de_Piezas_Recibidas__c = getQuantityPerLote.get(lote.Id);                       
            lotesUpdateList.add(lote);
          }
        }

        update orders;
        try {
           ImageUploadController.saveImage('Imagen de Rechazo', orderUpdates.rejectionImage, orderId, false);
        } catch (Exception e) {
          System.debug(e.getMessage() + e.getStackTraceString());
        }
      
        update lotesUpdateList;
      }
    } catch (Exception e) {
      System.debug(e.getMessage());
      System.debug(e.getStackTraceString());
      // TODO: change this for an aura exception
      return 'Error al enviar registro: ' + e.getMessage();
    }

    
    return 'Enviado correctamente.';
  }

  public class OrderUpdates {
    public String desviacion;
    public String descripcion;
    public String rejectionImage;
    public List<OrderItemUpdate> orderItemsUpdates;
    public Date selectedDate;
    public Time selectedTime;
  }

  public class OrderItemUpdate {
    public String name;
    public String id;
    public List<Lote> lotes;
    public Integer cantidadDePiezasFaltantes;
  }

  public class Lote{
    public String id;
    public Integer cantidadDePiezasFaltantes;
  }
}