unpackaged/main/default/objects/MuleSoft_Integration_Settings__mdt/MuleSoft_Integration_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Esta metadata contine los parametros utilizados para la integracion con Mulesoft.</description>
    <label>MuleSoft Integration Settings</label>
    <pluralLabel>MuleSoft Integration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/MuleSoft_Integration_Settings__mdt/fields/AccessToken_Url__c.field-meta.xml
<CustomField>
    <fullName>AccessToken_Url__c</fullName>
    <description>Contiene la URL que se utiliza para obtener el access token para autenticar las diferentes requests.</description>
    <label>AccessToken Url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/MuleSoft_Integration_Settings__mdt/fields/Api_Base_Url__c.field-meta.xml
<CustomField>
    <fullName>Api_Base_Url__c</fullName>
    <description>El URL base para hacer los request.</description>
    <label>Api Base Url</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/IntegrationHttpCalloutMock.cls
@isTest
public class IntegrationHttpCalloutMock implements HttpCalloutMock {
    public Boolean failResponse { get; set; } 
    
    MuleSoft_Integration_Settings__mdt settings =  [SELECT Api_Base_Url__c, AccessToken_Url__c 
                                                            FROM  MuleSoft_Integration_Settings__mdt
                                                            WHERE DeveloperName = 'Traxion'];

    public IntegrationHttpCalloutMock(Boolean failResponse) {
        this.failResponse = failResponse;
    }

    public HttpResponse respond(HttpRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');

        if (req.getEndpoint().contains(settings.Api_Base_Url__c)) {
            if (failResponse) {
                res.setStatusCode(400);
                res.setBody('{"error": "Failed to get availability."}');
            } else {
                res.setStatusCode(200);
                res.setBody('[{"sku": "sku1", "availability": 10, "package_key": "package1", "packages_details": [{"quantity_pieces_package": 1, "availability": 2}]}]');
            }
        } else if (req.getEndpoint().contains(settings.AccessToken_Url__c)) {
            res.setStatusCode(200);
            res.setBody('{"access_token": "YOUR_ACCESS_TOKEN", "token_type": "Bearer", "expires_in": 3600}');
        } else {
            res.setStatusCode(404);
        }
        return res;
    }
}