unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Entrega Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/ID_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>ID_de_Viaje__c</fullName>
    <externalId>true</externalId>
    <label>ID de Viaje</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/Informacion_De_Lote__c.object-meta.xml
<CustomObject>
    <description>Guarda la informacion de los lotes que se utilizaron para surtir la clave.</description>
    <label>Informacion De Lote</label>
    <nameField>
        <label>Nombre de Informacion De Lotes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informacion De Lotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Fecha_de_Expiracion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Expiracion__c</fullName>
    <label>Fecha de Expiracion</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Numero de Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_De_Lote__c/fields/Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Item__c</fullName>
    <label>Order Line Item</label>
    <referenceTo>Order_Line_Item__c</referenceTo>
    <relationshipLabel>Informacion De Lotes</relationshipLabel>
    <relationshipName>Informacion_De_Lotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Cantidad_de_Cajas_en_la_Orden__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Cajas_en_la_Orden__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de cajas que viene en la orden desde el WMS.</description>
    <label>Cantidad de Cajas en la Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Orden</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordenes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Cantidad_de_Cajas_en_la_Orden__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Cajas_en_la_Orden__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Este campo dice cuantas cajas vienen en la orden.</description>
    <label>Cantidad de Cajas en la Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Ordenes</relationshipLabel>
    <relationshipName>Ordenes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Procesando</fullName>
            </value>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Llegada de Transporte</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Recibido</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>En Firma Parcial</fullName>
            </value>
            <value>
                <fullName>Certificado</fullName>
            </value>
            <value>
                <fullName>Certificado Parcial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Id_de_Viaje__c.field-meta.xml
<CustomField>
    <fullName>Id_de_Viaje__c</fullName>
    <formula>Entrega__r.Name</formula>
    <label>Id de Viaje</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{00000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <formula>Cantidad_de_Piezas__c -  Piezas_Faltantes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cantidad de Piezas Recibidas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Cantidad_de_Piezas__c.field-meta.xml
<CustomField>
    <fullName>Cantidad_de_Piezas__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad de Piezas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Costo_Promedio__c.field-meta.xml
<CustomField>
    <fullName>Costo_Promedio__c</fullName>
    <label>Costo Promedio</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verificando Disponibilidad</fullName>
            </value>
            <value>
                <fullName>Preparando Envío</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>En Firma</fullName>
            </value>
            <value>
                <fullName>Recibido Parcial</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
                <isActive>false</isActive>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>Rechazado</fullName>
                <isActive>false</isActive>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Fecha_de_Expiracion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Expiracion__c</fullName>
    <label>Fecha de Expiración</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Numero_de_Lote__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Lote__c</fullName>
    <label>Número de Lote</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Censo</fullName>
            </value>
            <value>
                <fullName>Censo DPN</fullName>
            </value>
            <value>
                <fullName>Consumible</fullName>
            </value>
            <value>
                <fullName>Consumo</fullName>
            </value>
            <value>
                <fullName>Material de Curación</fullName>
            </value>
            <value>
                <fullName>Material de Laboratorio</fullName>
            </value>
            <value>
                <fullName>Material Radiológico</fullName>
            </value>
            <value>
                <fullName>Medicamento</fullName>
            </value>
            <value>
                <fullName>Ropa Quirúrgica Desechable</fullName>
            </value>
            <value>
                <fullName>#N/D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Code_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Clave</inlineHelpText>
    <label>Product Code ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/ServicioSalidaAlmacen.cls
@RestResource(urlMapping='/SalidaAlmacen/*')
global class ServicioSalidaAlmacen {

    @HttpPost
    global static void createRecord() {
        RestRequest pedido = RestContext.request;
        System.debug(pedido);
        RestResponse respuesta = RestContext.response;
        try {
            List<Order> orders = (List<Order>)JSON.deserialize(pedido.requestBody.toString(), List<Order>.class);
            System.debug('here');
			System.debug(orders);
            RespuestaTraxion respuestaTraxion = new RespuestaTraxion();
            respuestaTraxion.completedSuccessfully = true;
            respuestaTraxion.response = new ResponseData();
            respuestaTraxion.response.message = 'successful';
            respuestaTraxion.response.data = new DataInfo();

 

            Map<String, Entrega__c> entregaMap = new Map<String, Entrega__c>();
            Map<String, Order> orderMap = new Map<String, Order>();
            Set<String> allSkus = new Set<String>();

 

            for(Order orderRequest : orders){
                String loadNumber = orderRequest.load;

 

                Entrega__c entrega = new Entrega__c();
                entrega.Name = loadNumber;
                entrega.ID_de_Viaje__c = loadNumber;

 

                entregaMap.put(loadNumber, entrega);
                orderMap.put(orderRequest.order_number, orderRequest);

 

                for(SkuInfo sku : orderRequest.skus) {
                    allSkus.add(sku.sku);
                }
            }

 

            // upserting Entrega__c using External Id field
            Database.UpsertResult[] urList = Database.upsert(entregaMap.values(), Entrega__c.Fields.ID_de_Viaje__c, true);

 

            for(Database.UpsertResult ur : urList) {
                if(!ur.isSuccess()) {
                    respuesta.responseBody = Blob.valueOf('Error: ' + ur.getErrors());
                    respuesta.statusCode = 500;
                    return;
                }
            }

 

            List<Order__c> existingOrders = [SELECT Id, Order_Number__c, Estatus__c, Entrega__c,
                                             Cantidad_de_Cajas_en_la_Orden__c,
                                             (SELECT Id, Product__r.Product_Code_ID__c, Cantidad_de_Piezas__c, Numero_de_Lote__c, Fecha_de_Expiracion__c, Estatus__c 
                                              FROM Order_Line_Items__r WHERE Product__r.Product_Code_ID__c IN :allSkus) 
                                             FROM Order__c WHERE Order_Number__c IN :orderMap.keySet()];

 

            List<Order_Line_Item__c> itemsToUpdate = new List<Order_Line_Item__c>();
            List<Informacion_De_Lote__c> lotesToUpdate = new List<Informacion_De_Lote__c>();

 

            for(Order__c existingOrder : existingOrders){
                Order orderRequest = orderMap.get(existingOrder.Order_Number__c);
                existingOrder.Entrega__c = entregaMap.get(orderRequest.load).Id;
                existingOrder.Estatus__c = 'Enviado';
                existingOrder.Cantidad_de_Cajas_en_la_Orden__c = orderRequest.box_quantity;


 

                Map<String, Order_Line_Item__c> skuToOrderLineItem = new Map<String, Order_Line_Item__c>();
                for(Order_Line_Item__c oli : existingOrder.Order_Line_Items__r){
                    skuToOrderLineItem.put(oli.Product__r.Product_Code_ID__c, oli);
                }

 

                for(SkuInfo sku : orderRequest.skus){
                    Order_Line_Item__c lineItem = skuToOrderLineItem.get(sku.sku);
                    if(lineItem != null){
                        for(loteInfo lote : sku.lote_info){
                            Informacion_De_Lote__c loteToUpdate = new Informacion_De_Lote__c();
                            
                            // Date is coming in the format DD/MM/YYYY and we need to transform it into MM/DD/YYYY
                            String[] dateParts = lote.expiration_date.split('/');
							// String reformattedDate = dateParts[1] + '/' + dateParts[0] + '/' + dateParts[2];

                            // Date parsedDate = Date.parse(reformattedDate);

                            Integer year = Integer.valueOf(dateParts[2]);
                            Integer month = Integer.valueOf(dateParts[1]);
                            Integer day = Integer.valueOf(dateParts[0]);

                            Date parsedDate = Date.newInstance(year, month, day); 
							
                            
                            loteToUpdate.Fecha_de_Expiracion__c = parsedDate;
                            loteToUpdate.Cantidad__c = lote.quantity;
                            loteToUpdate.Numero_de_Lote__c = lote.lot_number;
                            loteToUpdate.Order_Line_Item__c = lineItem.Id;
                            lotesToUpdate.add(loteToUpdate);
                        }
                        lineItem.Cantidad_de_Piezas__c = sku.quantity;
                        lineItem.Costo_Promedio__c = sku.avg_cost;

                        lineItem.Estatus__c = 'Enviado';
                        itemsToUpdate.add(lineItem);
                    }
                }
            }

 

            update existingOrders;
            update itemsToUpdate;
            insert lotesToUpdate;

 

            String responseBody = JSON.serialize(respuestaTraxion);

            respuesta.responseBody = Blob.valueOf(responseBody);
            respuesta.statusCode = 200;
        } catch (Exception ex) {
            respuesta.responseBody = Blob.valueOf('Error: ' + ex.getMessage());
            respuesta.statusCode = 500;
        }
    }

 

    global class RespuestaTraxion {
        public Boolean completedSuccessfully;
        public ResponseData response;
    }

    global class ResponseData {
        public String message;
        public DataInfo data;
    }

    global class DataInfo {
    }

    global class Order {
        public String order_number;
        public String umu;
        public String load;
        public Integer box_quantity;
        public String umu_name;
        public String route;
        public List<SkuInfo> skus;
    }

    global class SkuInfo {
        public String sku;
        public Integer quantity;
        public Double avg_cost;
        public List<LoteInfo> lote_info;
    }

 

    global class LoteInfo {
        public Integer quantity;
        public String expiration_date;
        public String lot_number;
    }
}