unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <description>Registros de inventario por UMU, tipo de insumo y clasificación.</description>
    <label>Inventario</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Inventario</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Programas__c/Programas__c.object-meta.xml
<CustomObject>
    <label>Programa</label>
    <nameField>
        <label>Programas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Programas__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <label>Inventario</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Programa</fullName>
                <default>true</default>
                <label>Programa</label>
            </value>
            <value>
                <fullName>Vacuna</fullName>
            </value>
            <value>
                <fullName>Ordinario</fullName>
            </value>
            <value>
                <fullName>Compras Locales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Programas__c/fields/Programa_ID__c.field-meta.xml
<CustomField>
    <fullName>Programa_ID__c</fullName>
    <label>Programa ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ProgramController.cls
public without sharing class ProgramController {
	@AuraEnabled(cacheable=true)
    public static Programas__c getProgramById(String programId) {
        try {
            return [SELECT Id, Programa_ID__c, Name, Inventario__c 
                    FROM Programas__c
                    WHERE Id = :programId
                    LIMIT 1];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Programas__c> getProgramsByContact() {
    	List<Id> programsIdList = new List<Id>();
        try {
            programsIdList = UserContactClass.getProgramIdsByContact();
            return [SELECT Id, Programa_ID__c, Name 
                    FROM Programas__c
                    WHERE Id IN :programsIdList];
        } catch (Exception e) {
            System.debug('Query error: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
}